# # Code Generated by Sidekick is for learning and experimentation purposes only.
# """
# Chroma adapter for Workflow 2.

# Isolates the planning subgraph from ChromaService internals.
# If your M1/M2 ChromaService uses different method names, edit ONLY this file.

# Every retrieval call enforces project_id as a mandatory filter —
# cross-project RAG leakage is treated as a defect.
# """
# from __future__ import annotations

# import logging
# from typing import Any, Dict, List

# logger = logging.getLogger(__name__)


# class PlanningChromaAdapter:
#     """
#     Wraps ChromaService and exposes exactly what the planning subgraph needs.
#     Instantiated fresh per-call (ChromaService manages its own connection).
#     """

#     def __init__(self) -> None:
#         # Import here to avoid circular imports at module load time
#         from app.services.chroma_service import ChromaService
#         self._chroma = ChromaService()

#     # ── Document RAG ──────────────────────────────────────────────────

#     async def query_documents(
#         self,
#         query: str,
#         project_id: str,
#         n_results: int = 8,
#     ) -> List[Dict[str, Any]]:
#         """
#         Retrieves document chunks from the 'documents' ChromaDB collection.
#         ALWAYS filters by project_id — never returns cross-project chunks.

#         Returns list of:
#           {
#             "document": "<chunk text>",
#             "metadata": {
#               "section_id": "...",
#               "section_title": "...",
#               "document_id": "...",
#               "project_id": "...",
#               "page": 1,
#               "kind": "BRD|PRD|TRD|other"
#             }
#           }
#         """
#         try:
#             # ── Adapt to your actual ChromaService method name ──────────
#             # Option A: if your service has query_documents(query, project_id, n_results)
#             if hasattr(self._chroma, "query_documents"):
#                 results = await self._chroma.query_documents(
#                     query=query,
#                     project_id=project_id,
#                     n_results=n_results,
#                 )

#             # Option B: if your service has search_documents(query, filters, limit)
#             elif hasattr(self._chroma, "search_documents"):
#                 results = await self._chroma.search_documents(
#                     query=query,
#                     filters={"project_id": project_id},
#                     limit=n_results,
#                 )

#             # Option C: direct collection query (fallback)
#             else:
#                 collection = await self._chroma.get_collection("documents")
#                 raw = collection.query(
#                     query_texts=[query],
#                     n_results=n_results,
#                     where={"project_id": project_id},
#                 )
#                 results = _normalize_chroma_raw(raw)

#             # Safety: double-check project_id filter was honoured
#             filtered = [
#                 r for r in results
#                 if r.get("metadata", {}).get("project_id") == project_id
#             ]
#             if len(filtered) != len(results):
#                 logger.warning(
#                     "ChromaService returned %d results but only %d match project_id=%s — "
#                     "cross-project leak prevented",
#                     len(results), len(filtered), project_id,
#                 )
#             return filtered

#         except Exception as e:
#             logger.error("query_documents failed [project=%s]: %s", project_id, e)
#             return []

#     # ── Pattern KB RAG ────────────────────────────────────────────────

#     async def query_patterns(
#         self,
#         query: str,
#         n_results: int = 6,
#         tags: List[str] | None = None,
#     ) -> List[Dict[str, Any]]:
#         """
#         Retrieves pattern entries from the 'patterns' ChromaDB collection.
#         Optionally filtered by tags.

#         Returns list of:
#           {
#             "document": "<intent + structure + when_to_use text>",
#             "metadata": {"name": "...", "tags": [...], "source": "..."}
#           }
#         """
#         try:
#             # ── Adapt to your actual ChromaService method name ──────────
#             if hasattr(self._chroma, "query_patterns"):
#                 return await self._chroma.query_patterns(
#                     query=query,
#                     n_results=n_results,
#                 )

#             elif hasattr(self._chroma, "search_patterns"):
#                 return await self._chroma.search_patterns(
#                     query=query,
#                     tags=tags,
#                     top_k=n_results,
#                 )

#             else:
#                 collection = await self._chroma.get_collection("patterns")
#                 where = {"tags": {"$in": tags}} if tags else None
#                 raw = collection.query(
#                     query_texts=[query],
#                     n_results=n_results,
#                     where=where,
#                 )
#                 return _normalize_chroma_raw(raw)

#         except Exception as e:
#             logger.error("query_patterns failed: %s", e)
#             return []


# # ─────────────────────────────────────────────────────────────────────
# # Internal helpers
# # ─────────────────────────────────────────────────────────────────────

# def _normalize_chroma_raw(raw: Dict[str, Any]) -> List[Dict[str, Any]]:
#     """
#     Normalises the raw dict returned by collection.query() into the
#     flat list-of-dicts format used throughout the planning subgraph.
#     """
#     results = []
#     documents = raw.get("documents", [[]])[0]
#     metadatas = raw.get("metadatas", [[]])[0]
#     distances = raw.get("distances", [[]])[0]

#     for i, doc in enumerate(documents):
#         meta = metadatas[i] if i < len(metadatas) else {}
#         dist = distances[i] if i < len(distances) else 1.0
#         # ChromaDB distances are L2 by default — convert to similarity score
#         relevance = max(0.0, 1.0 - dist)
#         results.append({
#             "document": doc,
#             "metadata": meta,
#             "relevance": relevance,
#         })
#     return results






# Code Generated by Sidekick is for learning and experimentation purposes only.
"""
Chroma adapter for Workflow 2 — Planning.

Wraps your existing app/storage/vector_store.py so the planning subgraph
never imports it directly. If vector_store internals change, only this
file needs updating.

Document queries:   uses DocumentStore.query() — project_id MANDATORY
Pattern queries:    uses get_patterns_collection().query() directly
                    (same approach as patterns/service.py search_patterns)

Return shapes are normalised so researcher_subgraph.py never touches
raw ChromaDB dicts.
"""
from __future__ import annotations

import logging
from typing import Any, Dict, List, Optional

logger = logging.getLogger(__name__)


class PlanningChromaAdapter:
    """
    Thin adapter over app/storage/vector_store.py.

    Normalises return shapes to:
      Documents : [{"document": str, "metadata": dict}]
      Patterns  : [{"document": str, "metadata": dict}]

    Uses "document" key (not "text") so researcher_subgraph prompt
    formatting is consistent across both collections.
    """

    def __init__(self) -> None:
        # Import inside __init__ to avoid circular imports at module load
        from app.storage.vector_store import document_store, get_patterns_collection
        self._doc_store = document_store
        self._get_patterns_col = get_patterns_collection

    # ── Document RAG ──────────────────────────────────────────────────

    async def query_documents(
        self,
        query: str,
        project_id: str,
        n_results: int = 8,
    ) -> List[Dict[str, Any]]:
        """
        Queries the 'documents' collection via DocumentStore.query().
        ALWAYS scoped by project_id — cross-project leakage is a defect.

        Normalised return shape:
          [{"document": str, "metadata": {...}, "relevance": float}]

        Note: DocumentStore.query() is synchronous (it uses sentence-transformers
        locally). We call it directly — no await needed.
        """
        try:
            raw = self._doc_store.query(
                query_text=query,
                project_id=project_id,
                n_results=n_results,
            )

            if not raw:
                logger.warning(
                    "query_documents: no results [project=%s]", project_id
                )
                return []

            # Normalise: DocumentStore returns "text" key — rename to "document"
            # Also enforce project_id filter (double-check)
            results = []
            for r in raw:
                meta = r.get("metadata", {})
                if meta.get("project_id") != project_id:
                    logger.warning(
                        "cross-project chunk detected and dropped [got=%s expected=%s]",
                        meta.get("project_id"), project_id,
                    )
                    continue
                results.append({
                    "document": r.get("text", ""),      # rename "text" → "document"
                    "metadata": meta,
                    "relevance": float(r.get("score", 0.0)),
                })

            logger.debug(
                "query_documents: %d chunks returned [project=%s]",
                len(results), project_id,
            )
            return results

        except Exception as e:
            logger.error("query_documents failed [project=%s]: %s", project_id, e)
            return []

    # ── Pattern KB RAG ────────────────────────────────────────────────

    async def query_patterns(
        self,
        query: str,
        n_results: int = 6,
        tags: Optional[List[str]] = None,
    ) -> List[Dict[str, Any]]:
        """
        Queries the 'patterns' ChromaDB collection directly.
        Mirrors the approach in patterns/service.py search_patterns().
        Global collection — NOT scoped by project_id.

        Normalised return shape:
          [{"document": str, "metadata": {"name": str, "tags": str, ...}}]
        """
        try:
            collection = self._get_patterns_col()

            # Build optional tag filter (same logic as patterns/service.py)
            where: Optional[dict] = None
            if tags:
                if len(tags) == 1:
                    where = {"tags": {"$contains": tags[0]}}
                else:
                    where = {"$or": [{"tags": {"$contains": t}} for t in tags]}

            count = collection.count()
            if count == 0:
                logger.warning("query_patterns: patterns collection is empty")
                return []

            chroma_kwargs: Dict[str, Any] = dict(
                query_texts=[query],
                n_results=min(n_results, count),
                include=["documents", "metadatas", "distances"],
            )
            if where:
                chroma_kwargs["where"] = where

            raw = collection.query(**chroma_kwargs)

            documents = raw.get("documents", [[]])[0]
            metadatas = raw.get("metadatas", [[]])[0]
            distances = raw.get("distances", [[]])[0]

            results = []
            for doc, meta, dist in zip(documents, metadatas, distances):
                results.append({
                    "document": doc,
                    "metadata": meta,
                    "relevance": round(1.0 - float(dist), 4),
                })

            logger.debug("query_patterns: %d patterns returned", len(results))
            return results

        except Exception as e:
            logger.error("query_patterns failed: %s", e)
            return []
