# # Code Generated by Sidekick is for learning and experimentation purposes only.
# """
# Researcher Subgraph — Workflow 2, Combined Project & Code Planning.

# Implements the PARALLELIZATION pattern:

#     START
#       │
#       ├──► doc_rag_node    ──┐
#       ├──► kb_rag_node     ──┼──► synthesise_node ──► END
#       └──► web_search_node ──┘

# All three branches emit into research_findings via operator.add, so
# LangGraph merges them without any branch overwriting another.

# This compiled subgraph is imported as a single node into the parent
# planning graph (researcher_node in nodes.py calls it via ainvoke).

# Design pattern coverage:
#   - Parallelization  : three branches fan out from START in one superstep
#   - Orchestrator-Worker : each branch is a specialist worker
#   - Tool-Use         : web_search_node uses OpenAI's web_search_preview tool
# """
# from __future__ import annotations

# import json
# import logging
# import operator
# from typing import Annotated, Any, Dict, List, Optional

# from langchain_core.messages import HumanMessage, SystemMessage
# from langchain_openai import ChatOpenAI
# from langgraph.graph import END, START, StateGraph
# from pydantic import BaseModel, Field

# from app.core.config import settings
# from app.schemas.planning import ResearchFinding, ResearchOutput, ResearchSourceKind
# from app.workflows.planning.chroma_adapter import PlanningChromaAdapter
# from app.workflows.planning.prompts import (
#     DOC_RESEARCHER_SYSTEM,
#     DOC_RESEARCHER_USER,
#     KB_RESEARCHER_SYSTEM,
#     KB_RESEARCHER_USER,
#     SYNTHESISER_SYSTEM,
#     SYNTHESISER_USER,
#     WEB_RESEARCHER_SYSTEM,
#     WEB_RESEARCHER_USER,
# )

# logger = logging.getLogger(__name__)


# # ─────────────────────────────────────────────────────────────────────
# # Researcher subgraph state
# # ─────────────────────────────────────────────────────────────────────

# class ResearcherState(BaseModel):
#     """
#     Scoped state for the researcher subgraph only.
#     Passed in from the parent planning graph via researcher_node.

#     research_findings uses operator.add so all three parallel branches
#     safely append without overwriting each other's results.
#     """

#     # ── Inputs (set by parent before invoking subgraph) ───────────────
#     project_id: str
#     run_id: str
#     planning_goal: str
#     requirements_json: Dict[str, Any] = Field(default_factory=dict)
#     # Snapshot of selected patterns (already scoped to this run)
#     patterns_json: List[Dict[str, Any]] = Field(default_factory=list)

#     # ── Parallel accumulator (operator.add) ───────────────────────────
#     # All three branches append here; LangGraph merges via the reducer
#     research_findings: Annotated[List[ResearchFinding], operator.add] = Field(
#         default_factory=list
#     )

#     # ── Per-branch synthesis strings (scalar, last-write-wins) ────────
#     doc_synthesis: str = ""
#     kb_synthesis: str = ""
#     web_synthesis: str = ""

#     # ── Final output (set by synthesise_node) ─────────────────────────
#     final_synthesis: str = ""
#     total_findings: int = 0

#     # ── Error tracking ────────────────────────────────────────────────
#     branch_errors: Annotated[List[str], operator.add] = Field(default_factory=list)


# # ─────────────────────────────────────────────────────────────────────
# # LLM factories
# # ─────────────────────────────────────────────────────────────────────

# def _get_llm(temperature: float = 0.1) -> ChatOpenAI:
#     """Standard LLM — used for structured output at every branch."""
#     return ChatOpenAI(
#         model=settings.OPENAI_MODEL,
#         temperature=temperature,
#         api_key=settings.OPENAI_API_KEY,
#     )


# def _get_web_search_llm() -> ChatOpenAI:
#     """
#     LLM with OpenAI's built-in web_search_preview tool bound.
#     We use the tool to get fresh search results, then pass the raw
#     text to a SEPARATE synthesis call — this keeps structured output
#     and web search cleanly separated (OpenAI does not allow
#     with_structured_output + tools simultaneously on all models).
#     """
#     return ChatOpenAI(
#         model=settings.OPENAI_MODEL,
#         temperature=0.1,
#         api_key=settings.OPENAI_API_KEY,
#     ).bind_tools([{"type": "web_search_preview"}])


# # ─────────────────────────────────────────────────────────────────────
# # Helper: safe structured output call
# # ─────────────────────────────────────────────────────────────────────

# async def _invoke_structured(
#     llm: ChatOpenAI,
#     schema: type,
#     system: str,
#     user: str,
#     run_id: str,
#     branch: str,
# ) -> Any:
#     """
#     Calls llm.with_structured_output(schema).ainvoke(...).
#     Returns the parsed object or raises — callers handle exceptions.
#     """
#     structured_llm = llm.with_structured_output(schema)
#     return await structured_llm.ainvoke([
#         SystemMessage(content=system),
#         HumanMessage(content=user),
#     ])


# # ─────────────────────────────────────────────────────────────────────
# # Branch node 1 — Document RAG
# # ─────────────────────────────────────────────────────────────────────

# async def doc_rag_node(state: ResearcherState) -> Dict[str, Any]:
#     """
#     Retrieves chunks from the project's uploaded documents via ChromaDB.
#     Enforces project_id filter — no cross-project leakage.

#     Returns findings tagged [doc:<section_id>].
#     """
#     logger.info(
#         "[run=%s][branch=doc_rag] starting — project=%s",
#         state.run_id, state.project_id,
#     )
#     try:
#         adapter = PlanningChromaAdapter()
#         chunks = await adapter.query_documents(
#             query=state.planning_goal,
#             project_id=state.project_id,
#             n_results=8,
#         )

#         if not chunks:
#             logger.warning(
#                 "[run=%s][branch=doc_rag] no chunks returned for project=%s",
#                 state.run_id, state.project_id,
#             )
#             return {
#                 "research_findings": [],
#                 "doc_synthesis": "(no document chunks found for this project)",
#             }

#         # Format chunks with section IDs for citation tracking
#         chunks_text = "\n\n---\n\n".join(
#             f"[doc:{c['metadata'].get('section_id', 'unknown')}] "
#             f"(page {c['metadata'].get('page', '?')}, "
#             f"kind={c['metadata'].get('kind', 'unknown')})\n"
#             f"{c['document']}"
#             for c in chunks
#         )

#         result: ResearchOutput = await _invoke_structured(
#             llm=_get_llm(),
#             schema=ResearchOutput,
#             system=DOC_RESEARCHER_SYSTEM,
#             user=DOC_RESEARCHER_USER.format(
#                 planning_goal=state.planning_goal,
#                 chunks=chunks_text,
#             ),
#             run_id=state.run_id,
#             branch="doc",
#         )

#         logger.info(
#             "[run=%s][branch=doc_rag] complete — %d findings",
#             state.run_id, len(result.findings),
#         )
#         return {
#             "research_findings": result.findings,  # operator.add accumulates
#             "doc_synthesis": result.synthesis,
#         }

#     except Exception as e:
#         error_msg = f"doc_rag branch failed: {e}"
#         logger.error("[run=%s] %s", state.run_id, error_msg)
#         # Branch failure is non-fatal — return empty findings + error flag
#         return {
#             "research_findings": [],
#             "doc_synthesis": f"(doc branch error — skipped: {e})",
#             "branch_errors": [error_msg],
#         }


# # ─────────────────────────────────────────────────────────────────────
# # Branch node 2 — Pattern KB RAG
# # ─────────────────────────────────────────────────────────────────────

# async def kb_rag_node(state: ResearcherState) -> Dict[str, Any]:
#     """
#     Retrieves pattern entries from the ChromaDB patterns collection.
#     Not scoped by project_id (the pattern KB is global by design).

#     Returns findings tagged [kb:<pattern_name>].
#     """
#     logger.info("[run=%s][branch=kb_rag] starting", state.run_id)
#     try:
#         adapter = PlanningChromaAdapter()
#         kb_chunks = await adapter.query_patterns(
#             query=state.planning_goal,
#             n_results=6,
#         )

#         if not kb_chunks:
#             logger.warning("[run=%s][branch=kb_rag] no KB chunks returned", state.run_id)
#             return {
#                 "research_findings": [],
#                 "kb_synthesis": "(no KB pattern chunks found)",
#             }

#         # Format KB chunks with pattern names for citation tracking
#         kb_text = "\n\n---\n\n".join(
#             f"[kb:{c['metadata'].get('name', 'unknown')}]\n{c['document']}"
#             for c in kb_chunks
#         )

#         # Build pattern names list from snapshotted_patterns for context
#         pattern_names = ", ".join(
#             p.get("name", "?") for p in state.patterns_json
#         ) or "none selected yet"

#         result: ResearchOutput = await _invoke_structured(
#             llm=_get_llm(),
#             schema=ResearchOutput,
#             system=KB_RESEARCHER_SYSTEM,
#             user=KB_RESEARCHER_USER.format(
#                 planning_goal=state.planning_goal,
#                 pattern_names=pattern_names,
#                 kb_chunks=kb_text,
#             ),
#             run_id=state.run_id,
#             branch="kb",
#         )

#         logger.info(
#             "[run=%s][branch=kb_rag] complete — %d findings",
#             state.run_id, len(result.findings),
#         )
#         return {
#             "research_findings": result.findings,
#             "kb_synthesis": result.synthesis,
#         }

#     except Exception as e:
#         error_msg = f"kb_rag branch failed: {e}"
#         logger.error("[run=%s] %s", state.run_id, error_msg)
#         return {
#             "research_findings": [],
#             "kb_synthesis": f"(kb branch error — skipped: {e})",
#             "branch_errors": [error_msg],
#         }


# # ─────────────────────────────────────────────────────────────────────
# # Branch node 3 — Web Search
# # ─────────────────────────────────────────────────────────────────────

# async def web_search_node(state: ResearcherState) -> Dict[str, Any]:
#     """
#     Uses OpenAI's built-in web_search_preview tool to get fresh results.

#     Two-step process:
#       Step 1: Call the LLM with web_search_preview tool bound →
#               receives grounded web content in the response.
#       Step 2: Pass raw web content (wrapped in UNTRUSTED_CONTENT) to a
#               SEPARATE structured-output LLM call for safe extraction.

#     This separation is required because OpenAI does not support
#     with_structured_output and tool_calls simultaneously on all models.

#     Returns findings tagged [web:<url>].
#     """
#     logger.info("[run=%s][branch=web_search] starting", state.run_id)
#     try:
#         # ── Step 1: Get grounded web content ─────────────────────────
#         search_query = (
#             f"Best practices and design patterns for: {state.planning_goal[:300]}"
#         )
#         web_llm = _get_web_search_llm()
#         raw_response = await web_llm.ainvoke([
#             HumanMessage(content=search_query)
#         ])

#         # Extract text from response (handles both str and list content)
#         web_text = _extract_text_content(raw_response)

#         if not web_text.strip():
#             logger.warning(
#                 "[run=%s][branch=web_search] empty web response", state.run_id
#             )
#             return {
#                 "research_findings": [],
#                 "web_synthesis": "(web search returned no content)",
#             }

#         # ── Step 2: Structured extraction from web content ───────────
#         # Cap at 4000 chars to prevent token bloat; content is UNTRUSTED
#         result: ResearchOutput = await _invoke_structured(
#             llm=_get_llm(),
#             schema=ResearchOutput,
#             system=WEB_RESEARCHER_SYSTEM,
#             user=WEB_RESEARCHER_USER.format(
#                 planning_goal=state.planning_goal,
#                 web_results=web_text[:4000],
#             ),
#             run_id=state.run_id,
#             branch="web",
#         )

#         logger.info(
#             "[run=%s][branch=web_search] complete — %d findings",
#             state.run_id, len(result.findings),
#         )
#         return {
#             "research_findings": result.findings,
#             "web_synthesis": result.synthesis,
#         }

#     except Exception as e:
#         error_msg = f"web_search branch failed: {e}"
#         logger.error("[run=%s] %s", state.run_id, error_msg)
#         return {
#             "research_findings": [],
#             "web_synthesis": f"(web branch error — skipped: {e})",
#             "branch_errors": [error_msg],
#         }


# # ─────────────────────────────────────────────────────────────────────
# # Fan-in node — Synthesise
# # ─────────────────────────────────────────────────────────────────────

# async def synthesise_node(state: ResearcherState) -> Dict[str, Any]:
#     """
#     Merges all three branch outputs into a single research narrative.

#     By the time this node runs, research_findings already contains
#     findings from ALL three branches (operator.add merged them).
#     This node only needs to produce a readable narrative.

#     Adds [llm] citations for any knowledge contributed from training.
#     """
#     logger.info(
#         "[run=%s][branch=synthesise] merging %d total findings",
#         state.run_id, len(state.research_findings),
#     )

#     # If all branches failed, return a graceful degraded result
#     if not any([state.doc_synthesis, state.kb_synthesis, state.web_synthesis]):
#         logger.warning("[run=%s] all research branches returned empty", state.run_id)
#         return {
#             "final_synthesis": (
#                 "Research could not be completed — all branches returned empty. "
#                 "Proceeding with LLM-only knowledge [llm]."
#             ),
#             "total_findings": 0,
#         }

#     llm = _get_llm(temperature=0.2)
#     response = await llm.ainvoke([
#         SystemMessage(content=SYNTHESISER_SYSTEM),
#         HumanMessage(content=SYNTHESISER_USER.format(
#             planning_goal=state.planning_goal,
#             doc_synthesis=state.doc_synthesis or "(no document findings)",
#             kb_synthesis=state.kb_synthesis or "(no KB findings)",
#             web_synthesis=state.web_synthesis or "(no web findings)",
#         )),
#     ])

#     synthesis = _extract_text_content(response)

#     logger.info("[run=%s][branch=synthesise] complete", state.run_id)
#     return {
#         "final_synthesis": synthesis,
#         "total_findings": len(state.research_findings),
#     }


# # ─────────────────────────────────────────────────────────────────────
# # Helpers
# # ─────────────────────────────────────────────────────────────────────

# def _extract_text_content(response: Any) -> str:
#     """
#     Safely extracts a string from an LLM response.
#     Handles both plain str content and list-of-blocks content
#     (the latter occurs when the model uses tool_calls).
#     """
#     content = getattr(response, "content", response)
#     if isinstance(content, str):
#         return content
#     if isinstance(content, list):
#         for block in content:
#             if isinstance(block, dict) and block.get("type") == "text":
#                 return block.get("text", "")
#             if isinstance(block, str):
#                 return block
#     return str(content)


# # ─────────────────────────────────────────────────────────────────────
# # Build & compile
# # ─────────────────────────────────────────────────────────────────────

# def build_researcher_subgraph():
#     """
#     Builds and returns the COMPILED researcher subgraph.

#     No checkpointer is needed here — the parent planning graph's
#     checkpointer covers all state. The subgraph runs to completion
#     as a single logical node from the parent's perspective.

#     Graph wiring:
#       START ──► doc_rag    ──► synthesise ──► END
#       START ──► kb_rag     ──► synthesise
#       START ──► web_search ──► synthesise

#     LangGraph executes doc_rag, kb_rag, web_search in the same superstep
#     (parallel), then waits for all three before running synthesise.
#     """
#     graph = StateGraph(ResearcherState)

#     # ── Add nodes ─────────────────────────────────────────────────────
#     graph.add_node("doc_rag", doc_rag_node)
#     graph.add_node("kb_rag", kb_rag_node)
#     graph.add_node("web_search", web_search_node)
#     graph.add_node("synthesise", synthesise_node)

#     # ── Fan-out: START → three parallel branches ──────────────────────
#     graph.add_edge(START, "doc_rag")
#     graph.add_edge(START, "kb_rag")
#     graph.add_edge(START, "web_search")

#     # ── Fan-in: all three → synthesise ───────────────────────────────
#     # LangGraph waits for all superstep members before advancing
#     graph.add_edge("doc_rag", "synthesise")
#     graph.add_edge("kb_rag", "synthesise")
#     graph.add_edge("web_search", "synthesise")

#     # ── Terminal ──────────────────────────────────────────────────────
#     graph.add_edge("synthesise", END)

#     return graph.compile()


# # Module-level singleton — imported by researcher_node in nodes.py
# researcher_subgraph = build_researcher_subgraph()





# Code Generated by Sidekick is for learning and experimentation purposes only.
"""
Researcher Subgraph — Workflow 2, Combined Project & Code Planning.

Implements the PARALLELIZATION pattern:

    START
      │
      ├──► doc_rag_node    ──┐
      ├──► kb_rag_node     ──┼──► synthesise_node ──► END
      └──► web_search_node ──┘

All three branches emit into research_findings via operator.add, so
LangGraph merges them without any branch overwriting another.
"""
from __future__ import annotations

import logging
import operator
from typing import Annotated, Any, Dict, List, Optional

from langchain_core.messages import HumanMessage, SystemMessage
from langchain_google_genai import ChatGoogleGenerativeAI
from langgraph.graph import END, START, StateGraph
from pydantic import BaseModel, Field

# ── FIXED: correct import path ─────────────────────────────────────
from app.config import settings
# ───────────────────────────────────────────────────────────────────

from app.schemas.planning import ResearchFinding, ResearchOutput, ResearchSourceKind
from app.workflows.planning.chroma_adapter import PlanningChromaAdapter
from app.workflows.planning.prompts import (   # prompts.py (renamed from promts.py)
    DOC_RESEARCHER_SYSTEM,
    DOC_RESEARCHER_USER,
    KB_RESEARCHER_SYSTEM,
    KB_RESEARCHER_USER,
    SYNTHESISER_SYSTEM,
    SYNTHESISER_USER,
    WEB_RESEARCHER_SYSTEM,
    WEB_RESEARCHER_USER,
)

logger = logging.getLogger(__name__)


# ─────────────────────────────────────────────────────────────────────
# Researcher subgraph state
# ─────────────────────────────────────────────────────────────────────

class ResearcherState(BaseModel):
    """
    Scoped state for the researcher subgraph only.

    research_findings uses operator.add so all three parallel branches
    safely append without overwriting each other's results.
    """

    # ── Inputs ────────────────────────────────────────────────────────
    project_id: str
    run_id: str
    planning_goal: str
    requirements_json: Dict[str, Any] = Field(default_factory=dict)
    patterns_json: List[Dict[str, Any]] = Field(default_factory=list)

    # ── Parallel accumulator ──────────────────────────────────────────
    research_findings: Annotated[List[ResearchFinding], operator.add] = Field(
        default_factory=list
    )

    # ── Per-branch synthesis (scalar, last-write-wins) ─────────────────
    doc_synthesis: str = ""
    kb_synthesis: str = ""
    web_synthesis: str = ""

    # ── Final output ──────────────────────────────────────────────────
    final_synthesis: str = ""
    total_findings: int = 0

    # ── Error tracking ────────────────────────────────────────────────
    branch_errors: Annotated[List[str], operator.add] = Field(default_factory=list)


# ─────────────────────────────────────────────────────────────────────
# LLM factories  — Gemini ChatGoogleGenerativeAI
# ─────────────────────────────────────────────────────────────────────

def _get_api_key() -> str:
    return settings.GEMINI_API_KEY or settings.GOOGLE_API_KEY or settings.OPENAI_API_KEY


def _get_llm(temperature: float = 0.1) -> ChatGoogleGenerativeAI:
    return ChatGoogleGenerativeAI(
        model=settings.DEFAULT_MODEL,
        temperature=temperature,
        google_api_key=_get_api_key(),
    )


def _get_web_search_llm() -> ChatGoogleGenerativeAI:
    """
    LLM for web search / research.
    """
    return ChatGoogleGenerativeAI(
        model=settings.DEFAULT_MODEL,
        temperature=0.1,
        google_api_key=_get_api_key(),
    )


# ─────────────────────────────────────────────────────────────────────
# Helper: structured output call
# ─────────────────────────────────────────────────────────────────────

async def _invoke_structured(
    llm: ChatGoogleGenerativeAI,
    schema: type,
    system: str,
    user: str,
    run_id: str,
    branch: str,
) -> Any:
    structured_llm = llm.with_structured_output(schema)
    return await structured_llm.ainvoke([
        SystemMessage(content=system),
        HumanMessage(content=user),
    ])


# ─────────────────────────────────────────────────────────────────────
# Branch node 1 — Document RAG
# ─────────────────────────────────────────────────────────────────────

async def doc_rag_node(state: ResearcherState) -> Dict[str, Any]:
    """
    Retrieves chunks from the project's uploaded documents via DocumentStore.
    Enforces project_id filter — no cross-project leakage.
    Returns findings tagged [doc:<section_id>].
    """
    logger.info("[run=%s][branch=doc_rag] starting — project=%s",
                state.run_id, state.project_id)
    try:
        adapter = PlanningChromaAdapter()
        chunks = await adapter.query_documents(
            query=state.planning_goal,
            project_id=state.project_id,
            n_results=8,
        )

        if not chunks:
            logger.warning("[run=%s][branch=doc_rag] no chunks for project=%s",
                           state.run_id, state.project_id)
            return {
                "research_findings": [],
                "doc_synthesis": "(no document chunks found for this project)",
            }

        # adapter already normalised "text" → "document"
        chunks_text = "\n\n---\n\n".join(
            f"[doc:{c['metadata'].get('section_id', 'unknown')}] "
            f"(page {c['metadata'].get('page', '?')}, "
            f"kind={c['metadata'].get('kind', 'unknown')})\n"
            f"{c['document']}"
            for c in chunks
        )

        result: ResearchOutput = await _invoke_structured(
            llm=_get_llm(),
            schema=ResearchOutput,
            system=DOC_RESEARCHER_SYSTEM,
            user=DOC_RESEARCHER_USER.format(
                planning_goal=state.planning_goal,
                chunks=chunks_text,
            ),
            run_id=state.run_id,
            branch="doc",
        )

        logger.info("[run=%s][branch=doc_rag] complete — %d findings",
                    state.run_id, len(result.findings))
        return {
            "research_findings": result.findings,
            "doc_synthesis": result.synthesis,
        }

    except Exception as e:
        error_msg = f"doc_rag branch failed: {e}"
        logger.error("[run=%s] %s", state.run_id, error_msg)
        return {
            "research_findings": [],
            "doc_synthesis": f"(doc branch error — skipped: {e})",
            "branch_errors": [error_msg],
        }


# ─────────────────────────────────────────────────────────────────────
# Branch node 2 — Pattern KB RAG
# ─────────────────────────────────────────────────────────────────────

async def kb_rag_node(state: ResearcherState) -> Dict[str, Any]:
    """
    Retrieves pattern entries from the ChromaDB patterns collection.
    Global (not project-scoped). Returns findings tagged [kb:<pattern_name>].
    """
    logger.info("[run=%s][branch=kb_rag] starting", state.run_id)
    try:
        adapter = PlanningChromaAdapter()
        kb_chunks = await adapter.query_patterns(
            query=state.planning_goal,
            n_results=6,
        )

        if not kb_chunks:
            logger.warning("[run=%s][branch=kb_rag] no KB chunks returned", state.run_id)
            return {
                "research_findings": [],
                "kb_synthesis": "(no KB pattern chunks found)",
            }

        kb_text = "\n\n---\n\n".join(
            f"[kb:{c['metadata'].get('name', 'unknown')}]\n{c['document']}"
            for c in kb_chunks
        )

        pattern_names = ", ".join(
            p.get("name", "?") for p in state.patterns_json
        ) or "none selected yet"

        result: ResearchOutput = await _invoke_structured(
            llm=_get_llm(),
            schema=ResearchOutput,
            system=KB_RESEARCHER_SYSTEM,
            user=KB_RESEARCHER_USER.format(
                planning_goal=state.planning_goal,
                pattern_names=pattern_names,
                kb_chunks=kb_text,
            ),
            run_id=state.run_id,
            branch="kb",
        )

        logger.info("[run=%s][branch=kb_rag] complete — %d findings",
                    state.run_id, len(result.findings))
        return {
            "research_findings": result.findings,
            "kb_synthesis": result.synthesis,
        }

    except Exception as e:
        error_msg = f"kb_rag branch failed: {e}"
        logger.error("[run=%s] %s", state.run_id, error_msg)
        return {
            "research_findings": [],
            "kb_synthesis": f"(kb branch error — skipped: {e})",
            "branch_errors": [error_msg],
        }


# ─────────────────────────────────────────────────────────────────────
# Branch node 3 — Web Search
# ─────────────────────────────────────────────────────────────────────

async def web_search_node(state: ResearcherState) -> Dict[str, Any]:
    """
    Uses OpenAI's web_search_preview tool for fresh results.
    Two-step: (1) grounded content fetch, (2) structured extraction.
    Returns findings tagged [web:<url>].
    """
    logger.info("[run=%s][branch=web_search] starting", state.run_id)
    try:
        search_query = (
            f"Best practices and design patterns for: {state.planning_goal[:300]}"
        )
        web_llm = _get_web_search_llm()
        raw_response = await web_llm.ainvoke([HumanMessage(content=search_query)])

        web_text = _extract_text_content(raw_response)

        if not web_text.strip():
            logger.warning("[run=%s][branch=web_search] empty response", state.run_id)
            return {
                "research_findings": [],
                "web_synthesis": "(web search returned no content)",
            }

        result: ResearchOutput = await _invoke_structured(
            llm=_get_llm(),
            schema=ResearchOutput,
            system=WEB_RESEARCHER_SYSTEM,
            user=WEB_RESEARCHER_USER.format(
                planning_goal=state.planning_goal,
                web_results=web_text[:4000],
            ),
            run_id=state.run_id,
            branch="web",
        )

        logger.info("[run=%s][branch=web_search] complete — %d findings",
                    state.run_id, len(result.findings))
        return {
            "research_findings": result.findings,
            "web_synthesis": result.synthesis,
        }

    except Exception as e:
        error_msg = f"web_search branch failed: {e}"
        logger.error("[run=%s] %s", state.run_id, error_msg)
        return {
            "research_findings": [],
            "web_synthesis": f"(web branch error — skipped: {e})",
            "branch_errors": [error_msg],
        }


# ─────────────────────────────────────────────────────────────────────
# Fan-in node — Synthesise
# ─────────────────────────────────────────────────────────────────────

async def synthesise_node(state: ResearcherState) -> Dict[str, Any]:
    """
    Merges all three branch outputs into a single research narrative.
    research_findings already has all branches merged via operator.add.
    """
    logger.info("[run=%s][synthesise] merging %d total findings",
                state.run_id, len(state.research_findings))

    if not any([state.doc_synthesis, state.kb_synthesis, state.web_synthesis]):
        logger.warning("[run=%s] all research branches returned empty", state.run_id)
        return {
            "final_synthesis": (
                "Research could not be completed — all branches returned empty. "
                "Proceeding with LLM-only knowledge [llm]."
            ),
            "total_findings": 0,
        }

    llm = _get_llm(temperature=0.2)
    response = await llm.ainvoke([
        SystemMessage(content=SYNTHESISER_SYSTEM),
        HumanMessage(content=SYNTHESISER_USER.format(
            planning_goal=state.planning_goal,
            doc_synthesis=state.doc_synthesis or "(no document findings)",
            kb_synthesis=state.kb_synthesis or "(no KB findings)",
            web_synthesis=state.web_synthesis or "(no web findings)",
        )),
    ])

    synthesis = _extract_text_content(response)
    logger.info("[run=%s][synthesise] complete", state.run_id)
    return {
        "final_synthesis": synthesis,
        "total_findings": len(state.research_findings),
    }


# ─────────────────────────────────────────────────────────────────────
# Helper
# ─────────────────────────────────────────────────────────────────────

def _extract_text_content(response: Any) -> str:
    """Safely extracts string from LLM response (handles tool_call blocks)."""
    content = getattr(response, "content", response)
    if isinstance(content, str):
        return content
    if isinstance(content, list):
        for block in content:
            if isinstance(block, dict) and block.get("type") == "text":
                return block.get("text", "")
            if isinstance(block, str):
                return block
    return str(content)


# ─────────────────────────────────────────────────────────────────────
# Build & compile
# ─────────────────────────────────────────────────────────────────────

def build_researcher_subgraph():
    """
    Compiles the researcher subgraph.
    No checkpointer needed — parent planning graph's checkpointer covers all state.

    Wiring:
      START ──► doc_rag    ─┐
      START ──► kb_rag     ─┼──► synthesise ──► END
      START ──► web_search ─┘
    """
    graph = StateGraph(ResearcherState)

    graph.add_node("doc_rag", doc_rag_node)
    graph.add_node("kb_rag", kb_rag_node)
    graph.add_node("web_search", web_search_node)
    graph.add_node("synthesise", synthesise_node)

    # Fan-out
    graph.add_edge(START, "doc_rag")
    graph.add_edge(START, "kb_rag")
    graph.add_edge(START, "web_search")

    # Fan-in (LangGraph waits for all three before advancing)
    graph.add_edge("doc_rag", "synthesise")
    graph.add_edge("kb_rag", "synthesise")
    graph.add_edge("web_search", "synthesise")

    graph.add_edge("synthesise", END)

    return graph.compile()


# Module-level singleton — imported by researcher_node in nodes.py
researcher_subgraph = build_researcher_subgraph()
