# Code Generated by Sidekick is for learning and experimentation purposes only.
"""
PlanningService â€” orchestrates Workflow 2 lifecycle.

Responsibilities:
  - Create / fetch Run records
  - Build initial PlanningState
  - Launch the planning graph as a background task
  - Resume a paused graph after HITL approval/rejection
  - Query task list and research findings from state

Design notes:
  - Graph runs are fire-and-forget background tasks (FastAPI BackgroundTasks).
  - LangGraph checkpointer thread_id == run_id (stable across resumes).
  - All DB writes use the correct Run column names (output_data, error, run_metadata).
"""
from __future__ import annotations

import json
import logging
import uuid
from datetime import datetime, timezone
from typing import Any, Dict, List, Optional

from langgraph.types import Command
from sqlalchemy import select

from app.config import settings
from app.schemas.planning import (
    PlanningRunStatus,
    TaskItem,
    TriggerPlanningRequest,
    TriggerPlanningResponse,
)
from app.storage.database import AsyncSessionLocal
from app.storage.models import Run
from app.workflows.models import Task
from app.workflows.planning.graph import get_planning_graph
from app.workflows.planning.state import PlanningState

logger = logging.getLogger(__name__)

# LangGraph config key required for checkpointer thread isolation
_THREAD_CONFIG = lambda run_id: {"configurable": {"thread_id": run_id}}  # noqa: E731


class PlanningService:
    """
    Stateless service â€” all state lives in SQLite (DB + checkpointer).
    Instantiate once per request or inject as a FastAPI dependency.
    """

    # â”€â”€ Trigger â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€

    async def trigger(
        self,
        project_id: str,
        request: TriggerPlanningRequest,
    ) -> TriggerPlanningResponse:
        """
        Creates a new planning Run and returns immediately.
        Actual graph execution is started by the caller as a BackgroundTask.
        """
        # Validate that the requirements run exists
        async with AsyncSessionLocal() as db:
            req = await db.execute(
                select(Run).where(Run.id == request.requirements_run_id)
            )
            req_run = req.scalar_one_or_none()

        if req_run is None:
            raise ValueError(
                f"Requirements run '{request.requirements_run_id}' not found. "
                "Run Workflow 1 first and use its run_id."
            )
        if req_run.status not in ("completed", "approved"):
            raise ValueError(
                f"Requirements run '{request.requirements_run_id}' has status "
                f"'{req_run.status}' â€” only 'completed' runs can be planned."
            )

        run_id = str(uuid.uuid4())

        async with AsyncSessionLocal() as db:
            db.add(Run(
                id=run_id,
                project_id=project_id,
                workflow_type="planning",
                status="pending",
                input_data={
                    "requirements_run_id": request.requirements_run_id,
                    "idempotency_key": request.idempotency_key,
                },
                run_metadata={"current_node": "init"},
            ))
            await db.commit()

        logger.info("[service][trigger] created planning run=%s project=%s", run_id, project_id)

        return TriggerPlanningResponse(
            run_id=run_id,
            project_id=project_id,
            status=PlanningRunStatus.PENDING,
            message="Planning run created. Graph execution started in background.",
        )

    # â”€â”€ Execute (background task body) â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€

    async def execute(self, project_id: str, run_id: str, requirements_run_id: str) -> None:
        """
        Runs the full planning graph to completion (or HITL pause).
        Called as a FastAPI BackgroundTask â€” never awaited by the router.
        """
        logger.info("[service][execute] starting run=%s", run_id)

        initial_state = PlanningState(
            project_id=project_id,
            run_id=run_id,
            requirements_run_id=requirements_run_id,
        )

        try:
            async with get_planning_graph() as graph:
                await graph.ainvoke(
                    initial_state,
                    config=_THREAD_CONFIG(run_id),
                )
            logger.info("[service][execute] run=%s finished", run_id)

        except Exception as e:
            logger.error("[service][execute] run=%s FAILED: %s", run_id, e)
            # Persist failure
            try:
                async with AsyncSessionLocal() as db:
                    result = await db.execute(select(Run).where(Run.id == run_id))
                    run = result.scalar_one_or_none()
                    if run:
                        run.status = "failed"
                        run.error = str(e)[:500]
                        run.finished_at = datetime.now(timezone.utc)
                        await db.commit()
            except Exception as db_err:
                logger.error("[service][execute] DB failure persist error: %s", db_err)

    # â”€â”€ HITL Resume â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€

    async def resume_after_approval(
        self,
        project_id: str,
        run_id: str,
        decision: str,
        feedback: str = "",
    ) -> Dict[str, Any]:
        """
        Resumes a paused planning graph after a HITL approve/reject decision.
        Uses LangGraph Command(resume=...) to wake the interrupt() in approval_gate_node.

        Returns the updated run status dict.
        """
        logger.info("[service][resume] run=%s decision=%s", run_id, decision)

        # Validate run exists and is paused
        async with AsyncSessionLocal() as db:
            result = await db.execute(select(Run).where(Run.id == run_id))
            run = result.scalar_one_or_none()

        if run is None:
            raise ValueError(f"Run {run_id} not found")
        if run.status != "paused_hitl":
            raise ValueError(
                f"Run {run_id} is not awaiting approval (status={run.status})"
            )

        resume_payload = {"decision": decision, "feedback": feedback}

        try:
            async with get_planning_graph() as graph:
                await graph.ainvoke(
                    Command(resume=resume_payload),
                    config=_THREAD_CONFIG(run_id),
                )
            logger.info("[service][resume] run=%s resumed successfully", run_id)
        except Exception as e:
            logger.error("[service][resume] run=%s failed after resume: %s", run_id, e)
            raise

        # Return fresh status
        return await self.get_run_status(run_id)

    # â”€â”€ Query helpers â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€

    async def get_run_status(self, run_id: str) -> Dict[str, Any]:
        """Returns a status dict for the planning run."""
        async with AsyncSessionLocal() as db:
            result = await db.execute(select(Run).where(Run.id == run_id))
            run = result.scalar_one_or_none()

        if run is None:
            raise ValueError(f"Run {run_id} not found")

        meta = run.run_metadata or {}
        return {
            "run_id": run.id,
            "project_id": run.project_id,
            "status": run.status if isinstance(run.status, str) else run.status.value,
            "current_node": meta.get("current_node", "unknown"),
            "critic_iterations": meta.get("critic_iterations", 0),
            "critic_passed": meta.get("critic_passed", False),
            "tokens_used": meta.get("tokens_used", 0),
            "cost_usd": meta.get("cost_usd", 0.0),
            "pending_hitl_request_id": run.pending_hitl_request_id,
            "last_error": run.error,
            "created_at": run.created_at.isoformat() if run.created_at else None,
            "finished_at": run.finished_at.isoformat() if run.finished_at else None,
        }

    async def get_tasks(self, run_id: str) -> List[Dict[str, Any]]:
        """
        Returns the full task list from run.output_data.
        Falls back to empty list if the run has not completed yet.
        """
        async with AsyncSessionLocal() as db:
            result = await db.execute(select(Run).where(Run.id == run_id))
            run = result.scalar_one_or_none()

        if run is None:
            raise ValueError(f"Run {run_id} not found")

        output = run.output_data or {}
        if isinstance(output, str):
            try:
                output = json.loads(output)
            except json.JSONDecodeError:
                output = {}

        return output.get("tasks", [])

    async def update_task(
        self,
        run_id: str,
        task_id: str,
        updates: Dict[str, Any],
    ) -> Dict[str, Any]:
        """
        Updates a task's fields in run.output_data (patch semantics).
        Only mutable fields: title, description, acceptance_criteria, order.
        """
        async with AsyncSessionLocal() as db:
            result = await db.execute(select(Run).where(Run.id == run_id))
            run = result.scalar_one_or_none()

        if run is None:
            raise ValueError(f"Run {run_id} not found")

        output = run.output_data or {}
        if isinstance(output, str):
            output = json.loads(output)

        tasks: List[Dict] = output.get("tasks", [])
        target = next((t for t in tasks if t.get("task_id") == task_id), None)
        if target is None:
            raise ValueError(f"Task {task_id} not found in run {run_id}")

        allowed = {"title", "description", "acceptance_criteria", "order"}
        for key, val in updates.items():
            if key in allowed:
                target[key] = val

        output["tasks"] = tasks

        async with AsyncSessionLocal() as db:
            result = await db.execute(select(Run).where(Run.id == run_id))
            run = result.scalar_one_or_none()
            if run:
                run.output_data = output
                await db.commit()

        return target

    async def get_research_findings(self, run_id: str) -> Dict[str, Any]:
        """
        Returns research synthesis + finding count from run_metadata.
        Full findings are stored in the LangGraph checkpoint, not the DB â€”
        this returns the summary available from the Run row.
        """
        async with AsyncSessionLocal() as db:
            result = await db.execute(select(Run).where(Run.id == run_id))
            run = result.scalar_one_or_none()

        if run is None:
            raise ValueError(f"Run {run_id} not found")

        output = run.output_data or {}
        if isinstance(output, str):
            try:
                output = json.loads(output)
            except json.JSONDecodeError:
                output = {}
        research = output.get("research") or {}
        meta = run.run_metadata or {}
        synthesis = research.get("synthesis") or meta.get("research_synthesis", "(not yet available)")
        findings = research.get("findings") or []
        return {
            "run_id": run_id,
            "research_available": bool(research or "research_synthesis" in meta),
            "synthesis": synthesis,
            "doc_synthesis": research.get("doc_synthesis") or meta.get("doc_synthesis", ""),
            "kb_synthesis": research.get("kb_synthesis") or meta.get("kb_synthesis", ""),
            "web_synthesis": research.get("web_synthesis") or meta.get("web_synthesis", ""),
            "total_findings": len(findings) if findings else meta.get("total_findings", 0),
        }
