# # Code Generated by Sidekick is for learning and experimentation purposes only.
# """
# PlanningState — the single LangGraph state schema for Workflow 2.

# Key design decisions:
#   - research_findings uses Annotated[List, operator.add] so the three
#     parallel researcher branches can each append without overwriting.
#   - errors uses the same accumulator pattern.
#   - All scalar fields use plain types (last-write-wins by default in
#     LangGraph when you pass a dict update from a node).
# """
# from __future__ import annotations

# import operator
# from typing import Annotated, Any, Dict, List, Optional

# from pydantic import BaseModel, Field

# from app.schemas.planning import (
#     ArchitectureOutput,
#     CriticOutput,
#     PatternSelectionOutput,
#     ProjectComplexity,
#     ResearchFinding,
#     TaskPlanOutput,
# )


# class PlanningState(BaseModel):
#     """
#     State threaded through every node in Workflow 2.

#     Reducers:
#       research_findings : operator.add  — accumulates across parallel branches
#       errors            : operator.add  — accumulates error strings
#       All other fields  : last-write-wins (LangGraph default for dict updates)
#     """

#     # ── Identity ──────────────────────────────────────────────────────
#     project_id: str
#     run_id: str
#     requirements_run_id: str

#     # ── Requirements input (loaded at graph start) ────────────────────
#     requirements_json: Dict[str, Any] = Field(default_factory=dict)
#     requirements_md: str = ""

#     # ── Routing ───────────────────────────────────────────────────────
#     complexity: Optional[ProjectComplexity] = None

#     # ── Pattern Selection ─────────────────────────────────────────────
#     pattern_selection: Optional[PatternSelectionOutput] = None
#     # Immutable snapshot of selected pattern entries for this run.
#     # Stored in DB as JSON so global KB edits never mutate historical runs.
#     snapshotted_patterns: List[Dict[str, Any]] = Field(default_factory=list)

#     # ── Research (parallel accumulator) ───────────────────────────────
#     # Annotated with operator.add so doc_rag, kb_rag, web_search branches
#     # each safely append their findings in the same superstep.
#     research_findings: Annotated[List[ResearchFinding], operator.add] = Field(
#         default_factory=list
#     )
#     # Per-branch synthesis strings (scalar, last-write-wins per branch)
#     doc_synthesis: str = ""
#     kb_synthesis: str = ""
#     web_synthesis: str = ""
#     # Final merged narrative produced by the synthesise node
#     research_synthesis: str = ""

#     # ── Architecture ──────────────────────────────────────────────────
#     architecture: Optional[ArchitectureOutput] = None
#     architecture_md: str = ""

#     # ── Task Plan ─────────────────────────────────────────────────────
#     task_plan: Optional[TaskPlanOutput] = None

#     # ── Critic / Evaluator-Optimizer loop ────────────────────────────
#     critic_result: Optional[CriticOutput] = None
#     critic_iteration: int = 0
#     max_critic_iterations: int = 3   # configurable ceiling
#     critic_passed: bool = False

#     # ── HITL Approval ─────────────────────────────────────────────────
#     # Set by approval_gate_node; read by route_approval_result edge fn
#     approval_decision: Optional[str] = None      # "approve" | "reject"
#     approval_feedback: Optional[str] = None      # populated on reject
#     # Stable request_id so reconnecting WebSocket clients get same prompt
#     pending_hitl_request_id: Optional[str] = None

#     # ── Observability ─────────────────────────────────────────────────
#     current_node: str = "init"
#     tokens_used: int = 0
#     cost_usd: float = 0.0
#     # Accumulates across nodes — never overwritten
#     errors: Annotated[List[str], operator.add] = Field(default_factory=list)





# Code Generated by Sidekick is for learning and experimentation purposes only.
"""
PlanningState — top-level state threaded through every node in Workflow 2.

Reducers:
  research_findings : operator.add  — accumulates across parallel branches
  errors            : operator.add  — accumulates error strings
  All other fields  : last-write-wins (LangGraph default for dict updates)
"""
from __future__ import annotations

import operator
from typing import Annotated, Any, Dict, List, Optional

from pydantic import BaseModel, Field

from app.schemas.planning import (
    ArchitectureOutput,
    CriticOutput,
    PatternSelectionOutput,
    ProjectComplexity,
    ResearchFinding,
    TaskPlanOutput,
)


class PlanningState(BaseModel):

    # ── Identity ──────────────────────────────────────────────────────────
    project_id: str
    run_id: str
    requirements_run_id: str

    # ── Requirements input (loaded at graph start) ─────────────────────────
    requirements_json: Dict[str, Any] = Field(default_factory=dict)
    requirements_md: str = ""

    # ── Planning goal (derived from requirements, used by researcher) ───────
    planning_goal: str = ""

    # ── Routing ────────────────────────────────────────────────────────────
    complexity: Optional[ProjectComplexity] = None

    # ── Pattern Selection ──────────────────────────────────────────────────
    pattern_selection: Optional[PatternSelectionOutput] = None
    snapshotted_patterns: List[Dict[str, Any]] = Field(default_factory=list)

    # ── Research (parallel accumulator) ───────────────────────────────────
    research_findings: Annotated[List[ResearchFinding], operator.add] = Field(
        default_factory=list
    )
    doc_synthesis: str = ""
    kb_synthesis: str = ""
    web_synthesis: str = ""
    research_synthesis: str = ""

    # ── Architecture ───────────────────────────────────────────────────────
    architecture: Optional[ArchitectureOutput] = None
    architecture_md: str = ""

    # ── Task Plan ──────────────────────────────────────────────────────────
    task_plan: Optional[TaskPlanOutput] = None

    # ── Critic / Evaluator-Optimizer loop ──────────────────────────────────
    critic_result: Optional[CriticOutput] = None
    critic_iteration: int = 0
    max_critic_iterations: int = 3
    critic_passed: bool = False

    # ── HITL Approval ──────────────────────────────────────────────────────
    approval_decision: Optional[str] = None      # "approve" | "reject"
    approval_feedback: Optional[str] = None
    pending_hitl_request_id: Optional[str] = None

    # ── Observability ──────────────────────────────────────────────────────
    current_node: str = "init"
    tokens_used: int = 0
    cost_usd: float = 0.0
    errors: Annotated[List[str], operator.add] = Field(default_factory=list)
