# Code Generated by Sidekick is for learning and experimentation purposes only.
"""
app/workflows/codegen/graph.py
-------------------------------
Builds and compiles the top-level orchestrator StateGraph for the
Milestone 5 Code Generation workflow.

Topology
--------

  START
    â””â”€â–º load_context
              â””â”€â–º [route_orchestrator]
                        â”œâ”€(EXECUTE_TASK)â”€â–º pick_next_task
                        â”‚                       â””â”€â–º execute_task_node
                        â”‚                                 â””â”€â–º record_task_result
                        â”‚                                           â””â”€â–º [route_orchestrator]  â† loop
                        â”œâ”€(BUNDLE)â”€â”€â”€â”€â”€â”€â”€â–º bundle_workspace
                        â”‚                       â””â”€â–º request_approval
                        â”‚                                 â””â”€â–º END
                        â””â”€(FAIL)â”€â”€â”€â”€â”€â”€â”€â”€â”€â–º handle_failure_node
                                                  â””â”€â–º END

Key design notes
----------------
execute_task_node
    Wrapper node that dynamically invokes the per-task subgraph compiled
    by build_task_subgraph().  The orchestrator graph has no direct
    knowledge of the subgraph topology â€” it only sees _last_task_result.

route_orchestrator
    Shared conditional routing function (defined in nodes.py) attached to
    two source nodes: load_context (first pass) and record_task_result
    (subsequent iterations).  This creates the task execution loop.

handle_failure_node
    Terminal error handler.  Marks the Run as FAILED in the DB and writes
    the error into output_data so the router can surface it to callers.

Checkpointer
    An AsyncSqliteSaver instance is injected at compile time.
    Created once in runner.py and passed here â€” not created per-run.
"""

from __future__ import annotations

import base64
import logging
from datetime import datetime, timezone
from typing import Optional

from langgraph.checkpoint.sqlite.aio import AsyncSqliteSaver
from langgraph.graph import END, START, StateGraph

from app.hooks.node_hooks import node_hook
from app.workflows.graph_png import render_workflow_graph_png
from app.storage.database import AsyncSessionLocal
from app.storage.models import Run
from app.workflows.codegen.nodes import (
    bundle_workspace,
    load_context,
    pick_next_task,
    record_task_result,
    request_approval,
    route_orchestrator,
)
from app.workflows.codegen.state import (
    OrchestratorRoute,
    OrchestratorState,
    TaskRecord,
    TaskState,
)
from app.workflows.codegen.subgraph import build_task_subgraph, log_topology

log = logging.getLogger(__name__)


_FALLBACK_PNG = base64.b64decode(
    "iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8/x8AAwMCAO+/p9sAAAAASUVORK5CYII="
)


# ---------------------------------------------------------------------------
# execute_task_node  (subgraph bridge)
# ---------------------------------------------------------------------------

async def execute_task_node(state: OrchestratorState) -> OrchestratorState:
    """
    Bridge between the orchestrator graph and the per-task subgraph.

    Responsibilities
    ----------------
    1. Read the current TaskRecord from state["tasks"][current_task_index].
    2. Call build_task_subgraph(task) â€” returns a compiled graph from cache
       after the first call for each pattern combination.
    3. Construct a clean TaskState from orchestrator context.
    4. Invoke the subgraph via ainvoke() â€” runs to END.
    5. Extract _last_task_result from the subgraph's final state.
    6. Write _last_task_result back into OrchestratorState for
       record_task_result to consume.

    Error handling
    --------------
    If the subgraph itself raises an unhandled exception (e.g. DB
    connection lost mid-task), execute_task_node catches it, constructs
    a synthetic _last_task_result with final_status="failed", and
    returns it.  This prevents the orchestrator from crashing â€” the
    task is marked failed and the loop continues to the next task.

    Subgraph invocation note
    ------------------------
    We pass config={"recursion_limit": 50} to ainvoke().  The default
    LangGraph recursion limit is 25, which is insufficient for a task
    that hits max_retries=3 with a Reflection inner loop â€” each retry
    can traverse 5â€“7 nodes, and 3 retries Ã— 7 nodes = 21 steps before
    the reviewer fan-out even counts.  50 is conservative but safe.
    """
    idx   = state.get("current_task_index", 0)
    tasks = state.get("tasks", [])

    if idx >= len(tasks):
        return {
            **state,
            "_last_task_result": {
                "task_id":         "unknown",
                "final_status":    "failed",
                "retry_count":     0,
                "generated_files": [],
                "feedback":        None,
                "error":           f"execute_task_node: index {idx} out of bounds.",
            },
        }

    task = TaskRecord.from_dict(tasks[idx])

    log.info(
        "execute_task_node | run_id=%s | index=%d | task_id=%s | title=%r | patterns=%s",
        state["run_id"], idx, task.id, task.title, task.pattern_refs,
    )

    log_topology(task)

    # -- Build (or retrieve from cache) the subgraph -------------------------
    subgraph = build_task_subgraph(
        task        = task,
        max_retries = state.get("max_retries", 3),
    )

    # -- Construct initial TaskState -----------------------------------------
    initial_task_state: TaskState = {
        "run_id":                state["run_id"],
        "project_id":            state["project_id"],
        "task":                  task.to_dict(),
        "requirements_context":  state.get("requirements_context", ""),
        "architecture_context":  state.get("architecture_context", ""),
        "max_retries":           state.get("max_retries", 3),
        "developer_output":      None,
        "pending_files":         [],
        "critic_feedback":       None,
        "reviewer_verdicts":     [],
        "review_passed":         False,
        "aggregated_feedback":   None,
        "retry_count":           0,
        "final_status":          None,
        "generated_files":       [],
        "error":                 None,
    }

    # -- Invoke subgraph ------------------------------------------------------
    try:
        final_task_state: TaskState = await subgraph.ainvoke(
            initial_task_state,
            config={"recursion_limit": 50},
        )
        last_result = final_task_state.get("_last_task_result") or {
            "task_id":         task.id,
            "final_status":    final_task_state.get("final_status", "failed"),
            "retry_count":     final_task_state.get("retry_count", 0),
            "generated_files": final_task_state.get("generated_files", []),
            "feedback":        final_task_state.get("aggregated_feedback"),
            "error":           final_task_state.get("error"),
        }

    except Exception as exc:
        log.exception(
            "execute_task_node | subgraph raised unhandled exception | "
            "task_id=%s | error=%s",
            task.id, exc,
        )
        last_result = {
            "task_id":         task.id,
            "final_status":    "failed",
            "retry_count":     state.get("max_retries", 3),
            "generated_files": [],
            "feedback":        None,
            "error":           f"Subgraph raised unhandled exception: {exc}",
        }

    log.info(
        "execute_task_node | task_id=%s | final_status=%s | files=%d",
        task.id,
        last_result.get("final_status"),
        len(last_result.get("generated_files", [])),
    )

    return {**state, "_last_task_result": last_result}


# ---------------------------------------------------------------------------
# handle_failure_node  (terminal error handler)
# ---------------------------------------------------------------------------

async def handle_failure_node(state: OrchestratorState) -> OrchestratorState:
    """
    Terminal node for unrecoverable orchestrator failures.

    Called when route_orchestrator returns OrchestratorRoute.FAIL.
    Marks the Run as FAILED in the DB and writes the error into
    output_data so the router can surface it to the caller.

    Does NOT raise â€” failure handling must be silent so the graph
    can reach END cleanly and the checkpointer can record final state.
    """
    run_id = state.get("run_id", "unknown")
    error  = state.get("error", "Unknown orchestrator failure.")

    log.error(
        "handle_failure_node | run_id=%s | error=%s", run_id, error
    )

    try:
        from app.workflows.codegen.nodes import _db_session  # avoid circular at module level
        async with _db_session() as db:
            db_run: Optional[Run] = await db.get(Run, run_id)
            if db_run:
                db_run.status      = "failed"
                db_run.error       = error
                db_run.finished_at = datetime.now(timezone.utc)
                output             = db_run.output_data or {}
                output["error"]    = error
                db_run.output_data = output

    except Exception as exc:
        # Never let the failure handler itself crash the graph.
        log.error(
            "handle_failure_node | DB update failed: %s", exc
        )

    return state


# ---------------------------------------------------------------------------
# Orchestrator graph factory
# ---------------------------------------------------------------------------

def build_orchestrator_graph(
    checkpointer: Optional[AsyncSqliteSaver],
) -> "CompiledGraph":  # type: ignore[name-defined]
    """
    Construct and compile the top-level orchestrator StateGraph.

    Parameters
    ----------
    checkpointer
        An AsyncSqliteSaver instance created by the runner.
        Injected here rather than created here so the caller controls
        the DB path and the instance lifetime.

    Returns
    -------
    CompiledGraph
        A compiled LangGraph graph ready for ainvoke() / astream().

    Topology
    --------
    See module docstring for the full ASCII diagram.

    Conditional edge sources
    ------------------------
    Both load_context and record_task_result use route_orchestrator as
    their conditional edge function.  This creates the task execution
    loop â€” after each task completes, route_orchestrator decides whether
    to run the next task, bundle, or fail.

    route_orchestrator return values (from OrchestratorRoute):
        EXECUTE_TASK  â†’ pick_next_task
        BUNDLE        â†’ bundle_workspace
        FAIL          â†’ handle_failure_node
    """
    graph = StateGraph(OrchestratorState)

    # -- Register nodes -------------------------------------------------------
    graph.add_node("load_context",        node_hook("load_context")(load_context))
    graph.add_node("pick_next_task",      node_hook("pick_next_task")(pick_next_task))
    graph.add_node("execute_task_node",   node_hook("execute_task_node")(execute_task_node))
    graph.add_node("record_task_result",  node_hook("record_task_result")(record_task_result))
    graph.add_node("bundle_workspace",    node_hook("bundle_workspace")(bundle_workspace))
    graph.add_node("request_approval",    node_hook("request_approval")(request_approval))
    graph.add_node("handle_failure_node", node_hook("handle_failure_node")(handle_failure_node))

    # -- Entry edge -----------------------------------------------------------
    graph.add_edge(START, "load_context")

    # -- Conditional edge from load_context -----------------------------------
    # First routing decision: did load_context succeed and are there tasks?
    graph.add_conditional_edges(
        "load_context",
        route_orchestrator,
        {
            OrchestratorRoute.EXECUTE_TASK: "pick_next_task",
            OrchestratorRoute.BUNDLE:       "bundle_workspace",
            OrchestratorRoute.FAIL:         "handle_failure_node",
        },
    )

    # -- Linear task execution chain -----------------------------------------
    graph.add_edge("pick_next_task",    "execute_task_node")
    graph.add_edge("execute_task_node", "record_task_result")

    # -- Conditional edge from record_task_result (the loop) -----------------
    # After each task completes, route back to pick_next_task (more tasks),
    # bundle_workspace (all done), or handle_failure_node (error).
    graph.add_conditional_edges(
        "record_task_result",
        route_orchestrator,
        {
            OrchestratorRoute.EXECUTE_TASK: "pick_next_task",
            OrchestratorRoute.BUNDLE:       "bundle_workspace",
            OrchestratorRoute.FAIL:         "handle_failure_node",
        },
    )

    # -- Post-bundle chain ---------------------------------------------------
    graph.add_edge("bundle_workspace",  "request_approval")
    graph.add_edge("request_approval",  END)

    # -- Failure terminal ----------------------------------------------------
    graph.add_edge("handle_failure_node", END)

    # -- Compile with checkpointer -------------------------------------------
    return graph.compile(checkpointer=checkpointer)


def get_graph_png_bytes() -> bytes:
    graph = build_orchestrator_graph(checkpointer=None)
    try:
        return graph.get_graph().draw_mermaid_png()
    except Exception as exc:
        log.warning("codegen_graph_png_fallback", extra={"error": str(exc)})
        return render_workflow_graph_png(
            "Workflow 3: Code Generation",
            [
                "Load architecture context and approved task plan",
                "Pick next task and execute its dynamic per-task subgraph",
                "Generate files, run syntax/tool checks, and execute reviewer subagents",
                "Apply reviewer feedback through retry and revision loops",
                "Record task result and continue until all tasks are handled",
                "Package workspace into bundle.zip with MANIFEST.json",
                "Pause for final approval and persist approval state",
            ],
        )
