# Code Generated by Sidekick is for learning and experimentation purposes only.
"""
app/workflows/codegen/nodes.py
-------------------------------
LangGraph node implementations for the Milestone 5 Code Generation workflow.

Node inventory
--------------
Orchestrator graph nodes:
  load_context          â€” load task list + document context into state
  pick_next_task        â€” advance cursor, mark task in_progress in DB
  record_task_result    â€” write subgraph result back to DB + state
  bundle_workspace      â€” zip workspace, write MANIFEST.json
  request_approval      â€” push approval_request over HITL channel

Task subgraph nodes:
  developer_node        â€” call OpenAI, parse <file> blocks, stage files
  critic_node           â€” Reflection-pattern inner critic (optional)
  workflow_reviewer_node
  prompt_reviewer_node
  security_reviewer_node
  reduce_verdicts_node  â€” collapse parallel verdicts â†’ pass/fail
  finalize_task_node    â€” write staged files to disk, update DB

Routing functions (conditional edge callbacks):
  route_orchestrator    â€” EXECUTE_TASK | BUNDLE | FAIL
  route_after_critic    â€” TO_REVIEWERS | back to developer
  route_after_reduce    â€” FINALIZE | RETRY | FAIL

DB session pattern
------------------
Each node that touches the DB opens its own AsyncSession via
_db_session() context manager.  Sessions are never held across
await boundaries that span multiple nodes.

OpenAI client
-------------
A single AsyncOpenAI instance (_oai) is created at module level and
shared across all node calls.  It maintains an internal httpx
connection pool â€” do not instantiate per-call.
"""

from __future__ import annotations

import ast
import json
import logging
import os
import re
import uuid
from contextlib import asynccontextmanager
from datetime import datetime, timezone
from typing import AsyncGenerator, Optional

from langgraph.types import interrupt
from langchain_google_genai import ChatGoogleGenerativeAI
from langchain_core.messages import HumanMessage, SystemMessage
from sqlalchemy import select
from sqlalchemy.ext.asyncio import AsyncSession

from app.config import get_settings
from app.hooks.node_hooks import record_usage
from app.sse.manager import emit_event
from app.storage.database import AsyncSessionLocal
from app.storage.file_store import file_store
from app.storage.models import Run
from app.workflows.models import Task, TaskStatus, Approval
from app.workflows.codegen.state import (
    OrchestratorState,
    OrchestratorRoute,
    TaskRoute,
    TaskRecord,
    TaskState,
    GeneratedFile,
    ReviewerVerdict,
)
from app.workflows.codegen.prompts import (
    build_developer_prompt,
    build_retry_prompt,
    build_critic_prompt,
    build_workflow_reviewer_prompt,
    build_prompt_reviewer_prompt,
    build_security_reviewer_prompt,
    parse_developer_output,
    parse_reviewer_verdict,
    parse_critic_output,
)

log      = logging.getLogger(__name__)
settings = get_settings()

# ---------------------------------------------------------------------------
# Gemini API client
# ---------------------------------------------------------------------------

def _get_api_key() -> str:
    return settings.GEMINI_API_KEY or settings.GOOGLE_API_KEY or settings.OPENAI_API_KEY

# Model used for all developer / reviewer / critic calls.
_DEVELOPER_MODEL = getattr(settings, "CODEGEN_MODEL", settings.DEFAULT_MODEL)
_REVIEWER_MODEL  = getattr(settings, "REVIEWER_MODEL", settings.DEFAULT_MODEL)

# Tokens â€” generous for developer (multi-file output), tighter for reviewers
_DEVELOPER_MAX_TOKENS = 8192
_REVIEWER_MAX_TOKENS  = 1024
_CRITIC_MAX_TOKENS    = 1024


# ---------------------------------------------------------------------------
# DB session helper
# ---------------------------------------------------------------------------

@asynccontextmanager
async def _db_session() -> AsyncGenerator[AsyncSession, None]:
    """
    Yield an AsyncSession for use inside a node.

    Usage:
        async with _db_session() as db:
            result = await db.execute(select(Task).where(...))
            ...
            await db.commit()

    Always commits on clean exit, always rolls back on exception.
    Never hold this open across multiple node invocations.
    """
    async with AsyncSessionLocal() as session:
        try:
            yield session
            await session.commit()
        except Exception:
            await session.rollback()
            raise


# ---------------------------------------------------------------------------
# Small Gemini call helper
# ---------------------------------------------------------------------------

async def _chat(
    messages:   list[dict],
    model:      str,
    max_tokens: int,
    temperature: float = 0.2,
    node_name: str | None = None,
    run_id: str | None = None,
    project_id: str | None = None,
) -> str:
    """
    Call Gemini LLM via ChatGoogleGenerativeAI and return the content string.
    """
    active_model = settings.DEFAULT_MODEL if model in ("gpt-4o", "gpt-4o-mini") else model
    llm = ChatGoogleGenerativeAI(
        model=active_model,
        temperature=temperature,
        max_output_tokens=max_tokens,
        google_api_key=_get_api_key(),
    )
    formatted_messages = []
    for msg in messages:
        role = msg.get("role")
        content = msg.get("content", "")
        if role == "system":
            formatted_messages.append(SystemMessage(content=content))
        else:
            formatted_messages.append(HumanMessage(content=content))

    response = await llm.ainvoke(formatted_messages)
    usage = getattr(response, "usage_metadata", None)
    await record_usage(
        node_name=node_name or "llm_call",
        usage=usage,
        run_id=run_id,
        project_id=project_id,
        model=active_model,
        metadata={"temperature": temperature, "max_tokens": max_tokens},
    )
    return str(getattr(response, "content", response) or "")


# ---------------------------------------------------------------------------
# ORCHESTRATOR NODES
# ---------------------------------------------------------------------------

async def load_context(state: OrchestratorState) -> OrchestratorState:
    """
    Graph entry node.  Loads everything the orchestrator needs into state:

    1. Fetch the Run record for architecture_run_id â€” confirm it exists
       and is in COMPLETED status.
    2. Load all Task rows for this codegen run_id, sorted by order_index.
    3. Load requirements document text from the architecture run's artifacts.
    4. Load architecture spec text from the architecture run's artifacts.

    Fails fast with a clear error if:
    - The architecture run doesn't exist or isn't completed.
    - No tasks are found for this run.
    - Neither artifacts nor output_data contains the architecture spec.

    On failure, sets state["error"] â€” the router will send the run to FAIL.
    """
    run_id              = state["run_id"]
    project_id          = state["project_id"]
    architecture_run_id = state["architecture_run_id"]

    log.info(
        "load_context | run_id=%s | architecture_run_id=%s",
        run_id, architecture_run_id,
    )

    async with _db_session() as db:
        # -- Verify architecture run -----------------------------------------
        arch_run_result = await db.execute(
            select(Run).where(Run.id == architecture_run_id)
        )
        arch_run: Optional[Run] = arch_run_result.scalar_one_or_none()

        if not arch_run:
            return {**state, "error": f"Architecture run {architecture_run_id!r} not found."}

        arch_status = arch_run.status.value if hasattr(arch_run.status, "value") else str(arch_run.status)
        if arch_status != "completed":
            return {
                **state,
                "error": (
                    f"Architecture run {architecture_run_id!r} is not completed "
                    f"(status={arch_status!r}).  "
                    "Codegen requires an approved, completed architecture run."
                ),
            }

        # -- Load task list ---------------------------------------------------
        tasks_result = await db.execute(
            select(Task)
            .where(Task.run_id == run_id)
            .order_by(Task.order_index)
        )
        tasks: list[Task] = list(tasks_result.scalars().all())

        if not tasks:
            return {
                **state,
                "error": (
                    f"No tasks found for run_id={run_id!r}.  "
                    "The architecture workflow must have written tasks before "
                    "codegen can be triggered."
                ),
            }

        task_dicts = [TaskRecord.from_orm(t).to_dict() for t in tasks]

    # -- Load requirements context -------------------------------------------
    # Try artifacts file first; fall back to output_data["requirements"]
    requirements_context = await _load_text_artifact(
        project_id       = project_id,
        run_id           = architecture_run_id,
        filename         = "requirements.md",
        fallback_run     = arch_run,
        fallback_key     = "requirements",
    )

    # -- Load architecture context --------------------------------------------
    architecture_context = await _load_text_artifact(
        project_id       = project_id,
        run_id           = architecture_run_id,
        filename         = "architecture.json",
        fallback_run     = arch_run,
        fallback_key     = "architecture",
    )

    if not architecture_context:
        return {
            **state,
            "error": (
                f"Could not load architecture spec for run {architecture_run_id!r}.  "
                "Expected artifacts/architecture.json or output_data['architecture']."
            ),
        }

    log.info(
        "load_context | loaded %d tasks | "
        "requirements=%d chars | architecture=%d chars",
        len(task_dicts),
        len(requirements_context),
        len(architecture_context),
    )

    return {
        **state,
        "tasks":                task_dicts,
        "current_task_index":   0,
        "completed_task_ids":   [],
        "failed_task_ids":      [],
        "requirements_context": requirements_context,
        "architecture_context": architecture_context,
        "bundle_path":          None,
        "manifest":             None,
        "hitl_request_id":      None,
        "error":                None,
    }


async def _load_text_artifact(
    *,
    project_id:   str,
    run_id:       str,
    filename:     str,
    fallback_run: Run,
    fallback_key: str,
) -> str:
    """
    Try to read a text artifact from the filesystem; fall back to
    run.output_data[fallback_key] if the file doesn't exist.

    Returns an empty string if neither source has the content.
    """
    artifact_path = os.path.join(
        file_store.artifacts_dir(project_id, run_id), filename
    )

    if file_store.file_exists(artifact_path):
        try:
            return await file_store.read_file(artifact_path)
        except Exception as exc:
            log.warning("Could not read artifact %s: %s", artifact_path, exc)

    # Fallback: output_data on the Run record
    if fallback_run.output_data and fallback_key in fallback_run.output_data:
        value = fallback_run.output_data[fallback_key]
        # May be a dict (JSON) or a string
        if isinstance(value, dict):
            return json.dumps(value, indent=2)
        return str(value)

    return ""


# ---------------------------------------------------------------------------

async def pick_next_task(state: OrchestratorState) -> OrchestratorState:
    """
    Mark the current task as in_progress in the DB and return updated state.

    This is a lightweight node â€” it advances the cursor and writes a
    single status field.  The heavy lifting (LLM calls, file I/O) happens
    inside the subgraph.
    """
    tasks = state["tasks"]
    idx   = state["current_task_index"]

    if idx >= len(tasks):
        # Shouldn't reach here â€” route_orchestrator guards this.
        # Defensive: set error so the router sends to FAIL.
        return {**state, "error": "current_task_index out of bounds in pick_next_task."}

    task = TaskRecord.from_dict(tasks[idx])

    log.info(
        "pick_next_task | run_id=%s | index=%d | task_id=%s | title=%r",
        state["run_id"], idx, task.id, task.title,
    )

    async with _db_session() as db:
        db_task = await db.get(Task, task.id)
        if db_task:
            db_task.status     = TaskStatus.IN_PROGRESS.value
            db_task.started_at = datetime.now(timezone.utc)

    # Reflect in-memory state so subgraph sees in_progress
    task.status = TaskStatus.IN_PROGRESS.value
    updated_tasks = list(tasks)
    updated_tasks[idx] = task.to_dict()

    return {**state, "tasks": updated_tasks}


# ---------------------------------------------------------------------------

async def record_task_result(state: OrchestratorState) -> OrchestratorState:
    """
    Called by the orchestrator after each subgraph completes.

    Reads the subgraph's result from state["_last_task_result"] â€” a dict
    written by the subgraph's terminal node before returning.  Updates:

    - The Task row in DB (status, retry_count, generated_files, error)
    - The TaskRecord dict in state["tasks"][current_task_index]
    - state["completed_task_ids"] or state["failed_task_ids"]
    - Advances state["current_task_index"] by 1

    "_last_task_result" structure:
        {
          "task_id":        str,
          "final_status":   "completed" | "failed",
          "retry_count":    int,
          "generated_files": list[str],
          "feedback":       str | None,
          "error":          str | None,
        }
    """
    result = state.get("_last_task_result", {})
    idx    = state["current_task_index"]
    tasks  = list(state["tasks"])

    task_id      = result.get("task_id", "")
    final_status = result.get("final_status", TaskStatus.FAILED.value)
    retry_count  = result.get("retry_count", 0)
    gen_files    = result.get("generated_files", [])
    feedback     = result.get("feedback")
    error        = result.get("error")

    log.info(
        "record_task_result | task_id=%s | status=%s | files=%d",
        task_id, final_status, len(gen_files),
    )

    # -- Update DB ------------------------------------------------------------
    async with _db_session() as db:
        db_task = await db.get(Task, task_id)
        if db_task:
            db_task.status          = final_status
            db_task.retry_count     = retry_count
            db_task.generated_files = gen_files
            db_task.feedback        = feedback
            db_task.error           = error
            db_task.finished_at     = datetime.now(timezone.utc)

    # -- Update in-memory task record ----------------------------------------
    if 0 <= idx < len(tasks):
        task = TaskRecord.from_dict(tasks[idx])
        task.status          = final_status
        task.retry_count     = retry_count
        task.generated_files = gen_files
        task.feedback        = feedback
        task.error           = error
        tasks[idx] = task.to_dict()

    # -- Update progress lists -----------------------------------------------
    completed_ids = list(state.get("completed_task_ids", []))
    failed_ids = list(state.get("failed_task_ids", []))
    if final_status == TaskStatus.COMPLETED.value:
        if task_id not in completed_ids:
            completed_ids.append(task_id)
        failed_ids = [existing for existing in failed_ids if existing != task_id]
    else:
        if task_id not in failed_ids:
            failed_ids.append(task_id)
        completed_ids = [existing for existing in completed_ids if existing != task_id]
    return {
        **state,
        "tasks":               tasks,
        "current_task_index":  idx + 1,
        "completed_task_ids":  completed_ids,  # reducer appends
        "failed_task_ids":     failed_ids,     # reducer appends
        "_last_task_result":   None,
    }


# ---------------------------------------------------------------------------

async def bundle_workspace(state: OrchestratorState) -> OrchestratorState:
    """
    Zip the workspace and write MANIFEST.json.

    MANIFEST.json structure:
        {
          "run_id":      str,
          "project_id":  str,
          "generated_at": ISO timestamp,
          "tasks": {
            "<task_id>": {
              "title":  str,
              "status": str,
              "files":  ["relative/path/a.py", ...]
            },
            ...
          },
          "all_files": ["sorted", "list", "of", "all", "paths"]
        }
    """
    run_id     = state["run_id"]
    project_id = state["project_id"]

    log.info("bundle_workspace | run_id=%s | project_id=%s", run_id, project_id)

    # -- Build manifest -------------------------------------------------------
    tasks      = state.get("tasks", [])
    task_index = {}
    for t_dict in tasks:
        task = TaskRecord.from_dict(t_dict)
        task_index[task.id] = {
            "title":  task.title,
            "status": task.status,
            "files":  task.generated_files,
        }

    all_files = sorted(set(file_store.list_workspace_files(project_id, run_id) + ["MANIFEST.json"]))

    manifest = {
        "run_id":        run_id,
        "project_id":    project_id,
        "generated_at":  datetime.now(timezone.utc).isoformat(),
        "tasks":         task_index,
        "all_files":     all_files,
        "completed_tasks": state.get("completed_task_ids", []),
        "failed_tasks":    state.get("failed_task_ids", []),
        "final_approval": {
            "status": "pending",
            "approved": None,
            "decision": None,
            "feedback": None,
            "request_id": None,
            "decided_at": None,
        },
    }

    manifest_json = json.dumps(manifest, indent=2)

    # -- Write MANIFEST.json to workspace (included in bundle) and artifacts --
    await file_store.save_workspace_file(
        project_id    = project_id,
        run_id        = run_id,
        relative_path = "MANIFEST.json",
        content       = manifest_json,
    )
    await file_store.save_artifact(
        project_id = project_id,
        run_id     = run_id,
        filename   = "MANIFEST.json",
        content    = manifest_json,
    )

    # -- Create bundle.zip ----------------------------------------------------
    try:
        bundle_path = file_store.create_bundle(project_id, run_id)
        log.info("bundle_workspace | bundle created at %s", bundle_path)
    except Exception as exc:
        log.error("bundle_workspace | failed to create bundle: %s", exc)
        return {**state, "error": f"Bundle creation failed: {exc}"}

    # -- Persist bundle path on Run record ------------------------------------
    async with _db_session() as db:
        db_run = await db.get(Run, run_id)
        if db_run:
            meta = db_run.run_metadata or {}
            meta["bundle_path"] = bundle_path
            meta["manifest"]    = manifest
            db_run.run_metadata = meta

    return {
        **state,
        "bundle_path": bundle_path,
        "manifest":    manifest,
    }


# ---------------------------------------------------------------------------

async def request_approval(state: OrchestratorState) -> OrchestratorState:
    """
    Create an approval request, publish it, and pause with LangGraph interrupt().

    On first execution, interrupt() stores the checkpoint and returns control to
    the caller. On resume, Command(resume=...) returns the human decision here
    and this node records the final approval state before the graph reaches END.
    """
    run_id = state["run_id"]
    project_id = state["project_id"]
    request_id = state.get("hitl_request_id")
    if not request_id:
        async with _db_session() as db:
            existing_run = await db.get(Run, run_id)
            if existing_run and existing_run.pending_hitl_request_id:
                request_id = existing_run.pending_hitl_request_id
    request_id = request_id or str(uuid.uuid4())

    log.info("request_approval | run_id=%s | request_id=%s", run_id, request_id)

    manifest = dict(state.get("manifest") or {})
    final_approval = dict(manifest.get("final_approval") or {})
    final_approval.update({
        "status": "pending",
        "approved": None,
        "decision": None,
        "feedback": None,
        "request_id": request_id,
        "requested_at": datetime.now(timezone.utc).isoformat(),
        "decided_at": None,
    })
    manifest["final_approval"] = final_approval
    manifest["hitl_request_id"] = request_id

    bundle_path = state.get("bundle_path")
    try:
        manifest_json = json.dumps(manifest, indent=2)
        await file_store.save_workspace_file(
            project_id=project_id,
            run_id=run_id,
            relative_path="MANIFEST.json",
            content=manifest_json,
        )
        await file_store.save_artifact(
            project_id=project_id,
            run_id=run_id,
            filename="MANIFEST.json",
            content=manifest_json,
        )
        bundle_path = file_store.create_bundle(project_id, run_id)
    except Exception as exc:
        log.warning("request_approval | manifest approval stamp failed: %s", exc)

    state = {**state, "manifest": manifest, "bundle_path": bundle_path}

    payload = {
        "type": "approval_request",
        "request_id": request_id,
        "run_id": run_id,
        "project_id": project_id,
        "bundle_path": bundle_path,
        "summary": {
            "completed_tasks": len(state.get("completed_task_ids", [])),
            "failed_tasks": len(state.get("failed_task_ids", [])),
            "total_tasks": len(state.get("tasks", [])),
            "all_files": state.get("manifest", {}).get("all_files", []),
        },
        "message": "Codegen complete. Please review the bundle and approve or reject.",
    }

    output_data = {
        "completed_task_ids": state.get("completed_task_ids", []),
        "failed_task_ids": state.get("failed_task_ids", []),
        "bundle_path": state.get("bundle_path"),
        "manifest": state.get("manifest"),
        "hitl_request_id": request_id,
        "error": state.get("error"),
    }

    async with _db_session() as db:
        existing = await db.get(Approval, request_id)
        if not existing:
            db.add(
                Approval(
                    id=request_id,
                    project_id=project_id,
                    run_id=run_id,
                    workflow_type="codegen",
                    request_id=request_id,
                    status="pending",
                    artifact_urls=[bundle_path] if bundle_path else [],
                    payload=payload,
                )
            )

        db_run = await db.get(Run, run_id)
        if db_run:
            db_run.status = "paused_hitl"
            db_run.pending_hitl_request_id = request_id
            db_run.pending_hitl_type = "approval"
            db_run.output_data = output_data

    await emit_event(
        "approval_requested",
        payload,
        run_id=run_id,
        project_id=project_id,
        node_name="request_approval",
        message="Waiting for human approval",
    )

    try:
        from app.hitl.manager import push_to_run
        await push_to_run(run_id, "approval_request", payload)
    except Exception as exc:
        log.warning("request_approval | HITL push failed: %s", exc)

    decision_payload = interrupt(payload) or {}
    approved = bool(
        decision_payload.get("approved")
        if "approved" in decision_payload
        else decision_payload.get("decision") == "approve"
    )
    feedback = decision_payload.get("feedback")

    async with _db_session() as db:
        approval = await db.get(Approval, request_id)
        if approval:
            approval.status = "approved" if approved else "rejected"
            approval.decision = "approve" if approved else "reject"
            approval.approved = approved
            approval.feedback = feedback
            approval.decided_at = datetime.now(timezone.utc)
            approval.resolved_at = approval.decided_at
            approval.payload = {**(approval.payload or payload), "response": decision_payload}

    await emit_event(
        "approval_resumed",
        {"request_id": request_id, "approved": approved, "feedback": feedback},
        run_id=run_id,
        project_id=project_id,
        node_name="request_approval",
        message="Human approval received",
    )

    return {
        **state,
        "hitl_request_id": None,
        "approval_decision": "approve" if approved else "reject",
        "approval_feedback": feedback,
        "error": None if approved else (feedback or "Rejected by reviewer."),
    }

# ---------------------------------------------------------------------------
# TASK SUBGRAPH NODES
# ---------------------------------------------------------------------------

async def developer_node(state: TaskState) -> TaskState:
    """
    Core developer agent.  Calls OpenAI with a pattern-aware prompt and
    parses the response into a list of staged GeneratedFile dicts.

    On first attempt (retry_count == 0 and no critic_feedback):
        Uses build_developer_prompt()

    On retry (retry_count > 0):
        Uses build_retry_prompt() â€” includes previous output + reviewer feedback

    On Reflection iteration (critic_feedback is set):
        Uses build_developer_prompt() with critic_feedback injected â€”
        the developer knows it's revising in response to the critic,
        not the human reviewers.

    Sets state["developer_output"] and state["pending_files"].
    Sets state["error"] on parse failure (no <file> blocks found).
    """
    task        = TaskRecord.from_dict(state["task"])
    retry_count = state.get("retry_count", 0)
    agg_feedback = state.get("aggregated_feedback")
    critic_feedback = state.get("critic_feedback")

    existing_files = file_store.list_workspace_files(
        state["project_id"], state["run_id"]
    )

    log.info(
        "developer_node | task_id=%s | retry=%d | "
        "has_feedback=%s | has_critic=%s",
        task.id, retry_count,
        bool(agg_feedback), bool(critic_feedback),
    )

    # -- Choose prompt strategy ----------------------------------------------
    if retry_count > 0 and agg_feedback:
        messages = build_retry_prompt(
            task_title            = task.title,
            task_description      = task.description,
            pattern_refs          = task.pattern_refs,
            requirements_context  = state.get("requirements_context", ""),
            architecture_context  = state.get("architecture_context", ""),
            developer_output      = state.get("developer_output", ""),
            aggregated_feedback   = agg_feedback,
            retry_number          = retry_count,
            max_retries           = state.get("max_retries", 3),
            existing_files        = existing_files,
        )
    else:
        messages = build_developer_prompt(
            task_title            = task.title,
            task_description      = task.description,
            pattern_refs          = task.pattern_refs,
            requirements_context  = state.get("requirements_context", ""),
            architecture_context  = state.get("architecture_context", ""),
            existing_files        = existing_files,
            critic_feedback       = critic_feedback,
        )

    # -- Call OpenAI ----------------------------------------------------------
    try:
        raw_output = await _chat(
            messages   = messages,
            model      = _DEVELOPER_MODEL,
            max_tokens = _DEVELOPER_MAX_TOKENS,
            temperature = 0.2,
            node_name = "developer_node",
            run_id = state.get("run_id"),
            project_id = state.get("project_id"),
        )
    except Exception as exc:
        log.error("developer_node | OpenAI call failed: %s", exc)
        return {
            **state,
            "developer_output": "",
            "pending_files":    [],
            "error":            f"LLM call failed: {exc}",
        }

    # -- Parse output ---------------------------------------------------------
    try:
        parsed_files = parse_developer_output(raw_output)
    except ValueError as exc:
        log.warning("developer_node | parse failed: %s", exc)
        return {
            **state,
            "developer_output": raw_output,
            "pending_files":    [],
            "error":            str(exc),
        }

    pending = [
        GeneratedFile(
            relative_path = pf.relative_path,
            content       = pf.content,
            task_id       = task.id,
        ).to_dict()
        for pf in parsed_files
    ]

    log.info(
        "developer_node | task_id=%s | parsed %d file(s): %s",
        task.id,
        len(pending),
        [p["relative_path"] for p in pending],
    )

    return {
        **state,
        "developer_output": raw_output,
        "pending_files":    pending,
        "critic_feedback":  None,   # clear from previous iteration
        "error":            None,
    }



# ---------------------------------------------------------------------------

def _has_tool_function_docstring(pending: list[dict]) -> bool:
    """Return True when any generated Python function has a docstring."""
    fallback = re.compile(
        r"def\s+\w+\s*\([^)]*\)\s*:[ \t]*(?:\r?\n)[ \t]*(?:[rRuUfF]*)(?:'''|\"\"\")"
    )
    for item in pending:
        content = str(item.get("content", ""))
        try:
            tree = ast.parse(content)
        except SyntaxError:
            if fallback.search(content):
                return True
            continue
        for node in ast.walk(tree):
            if isinstance(node, (ast.FunctionDef, ast.AsyncFunctionDef)) and ast.get_docstring(node):
                return True
    return False


# ---------------------------------------------------------------------------

async def tool_syntax_check_node(state: TaskState) -> TaskState:
    """
    Static Tool-Use guardrail before LLM reviewers.

    A Tool-Use task must stage at least one file that defines callable tools,
    registers them in a tools list, and constructs a LangGraph ToolNode. This
    catches common malformed generations before spending reviewer calls.
    """
    task = TaskRecord.from_dict(state["task"])
    pending = state.get("pending_files", [])
    retry_count = state.get("retry_count", 0)

    combined = "\n\n".join(str(item.get("content", "")) for item in pending)
    issues: list[str] = []

    if not pending:
        issues.append("No generated files were staged for Tool-Use validation.")
    if "ToolNode" not in combined:
        issues.append("Generated code must import or instantiate langgraph.prebuilt.ToolNode.")
    if not re.search(r"\btools\s*=\s*\[", combined):
        issues.append("Generated code must define a tools = [...] registry.")
    if not _has_tool_function_docstring(pending):
        issues.append("At least one tool function must include a docstring.")

    if not issues:
        log.info("tool_syntax_check_node | task_id=%s | passed", task.id)
        return {
            **state,
            "aggregated_feedback": None,
            "error": None,
        }

    feedback = "Tool-Use validation failed:\n" + "\n".join(f"- {issue}" for issue in issues)
    log.info(
        "tool_syntax_check_node | task_id=%s | failed | retry=%d | issues=%s",
        task.id,
        retry_count,
        issues,
    )
    return {
        **state,
        "review_passed": False,
        "aggregated_feedback": feedback,
        "retry_count": retry_count + 1,
        "error": None,
    }

async def critic_node(state: TaskState) -> TaskState:
    """
    Reflection-pattern inner critic.

    Evaluates the developer's output for completeness, pattern compliance,
    and obvious logic errors before it reaches the human reviewers.

    Returns:
    - If passed=True:  clears critic_feedback â†’ route_after_critic sends
      to reviewers.
    - If passed=False: sets critic_feedback â†’ route_after_critic sends
      back to developer_node for revision.

    Critic parse failure is soft â€” if the LLM returns malformed JSON,
    we pass through to reviewers rather than blocking the pipeline.
    """
    task = TaskRecord.from_dict(state["task"])

    log.info("critic_node | task_id=%s", task.id)

    messages = build_critic_prompt(
        task_title       = task.title,
        task_description = task.description,
        pattern_refs     = task.pattern_refs,
        developer_output = state.get("developer_output", ""),
    )

    try:
        raw_output = await _chat(
            messages    = messages,
            model       = _REVIEWER_MODEL,
            max_tokens  = _CRITIC_MAX_TOKENS,
            temperature = 0.0,
            node_name = "critic_node",
            run_id = state.get("run_id"),
            project_id = state.get("project_id"),
        )
    except Exception as exc:
        log.error("critic_node | OpenAI call failed: %s â€” passing through", exc)
        return {**state, "critic_feedback": None}

    passed, feedback = parse_critic_output(raw_output)

    log.info(
        "critic_node | task_id=%s | passed=%s | feedback_len=%d",
        task.id, passed, len(feedback),
    )

    if passed:
        return {
            **state,
            "critic_feedback": None,
            "aggregated_feedback": None,
            "error": None,
        }

    return {
        **state,
        "critic_feedback": feedback,
        "aggregated_feedback": feedback,
        "retry_count": state.get("retry_count", 0) + 1,
        "review_passed": False,
        "error": None,
    }


# ---------------------------------------------------------------------------
# Reviewer nodes â€” run in parallel via LangGraph fan-out
# Each appends exactly one ReviewerVerdict dict to reviewer_verdicts.
# The operator.add reducer in TaskState ensures no race condition.
# ---------------------------------------------------------------------------

async def workflow_reviewer_node(state: TaskState) -> TaskState:
    """
    Reviewer 1: workflow correctness and pattern alignment.
    Appends one ReviewerVerdict dict to state["reviewer_verdicts"].
    """
    task       = TaskRecord.from_dict(state["task"])
    reviewer   = "workflow_reviewer"

    log.info("workflow_reviewer_node | task_id=%s", task.id)

    messages = build_workflow_reviewer_prompt(
        task_title            = task.title,
        task_description      = task.description,
        pattern_refs          = task.pattern_refs,
        developer_output      = state.get("developer_output", ""),
        architecture_context  = state.get("architecture_context", ""),
    )

    verdict = await _call_reviewer(
        reviewer=reviewer,
        messages=messages,
        run_id=state.get("run_id"),
        project_id=state.get("project_id"),
        attempt=state.get("retry_count", 0),
    )

    log.info(
        "workflow_reviewer_node | task_id=%s | passed=%s",
        task.id, verdict.passed,
    )

    return {"reviewer_verdicts": [verdict.to_dict()]}


async def prompt_reviewer_node(state: TaskState) -> TaskState:
    """
    Reviewer 2: prompt quality and injection resistance.
    Appends one ReviewerVerdict dict to state["reviewer_verdicts"].
    """
    task     = TaskRecord.from_dict(state["task"])
    reviewer = "prompt_reviewer"

    log.info("prompt_reviewer_node | task_id=%s", task.id)

    messages = build_prompt_reviewer_prompt(
        task_title       = task.title,
        task_description = task.description,
        developer_output = state.get("developer_output", ""),
    )

    verdict = await _call_reviewer(
        reviewer=reviewer,
        messages=messages,
        run_id=state.get("run_id"),
        project_id=state.get("project_id"),
        attempt=state.get("retry_count", 0),
    )

    log.info(
        "prompt_reviewer_node | task_id=%s | passed=%s",
        task.id, verdict.passed,
    )

    return {"reviewer_verdicts": [verdict.to_dict()]}


async def security_reviewer_node(state: TaskState) -> TaskState:
    """
    Reviewer 3: OWASP basics â€” secrets, input validation, error leakage.
    Appends one ReviewerVerdict dict to state["reviewer_verdicts"].
    """
    task     = TaskRecord.from_dict(state["task"])
    reviewer = "security_reviewer"

    log.info("security_reviewer_node | task_id=%s", task.id)

    messages = build_security_reviewer_prompt(
        task_title       = task.title,
        task_description = task.description,
        developer_output = state.get("developer_output", ""),
    )

    verdict = await _call_reviewer(
        reviewer=reviewer,
        messages=messages,
        run_id=state.get("run_id"),
        project_id=state.get("project_id"),
        attempt=state.get("retry_count", 0),
    )

    log.info(
        "security_reviewer_node | task_id=%s | passed=%s",
        task.id, verdict.passed,
    )

    return {"reviewer_verdicts": [verdict.to_dict()]}


async def _call_reviewer(
    *,
    reviewer: str,
    messages: list[dict],
    run_id: str | None = None,
    project_id: str | None = None,
    attempt: int = 0,
) -> ReviewerVerdict:
    """
    Shared helper: call OpenAI for any reviewer node and parse the verdict.

    Returns a blocking-failure ReviewerVerdict if the LLM call itself
    fails â€” we never silently pass on a reviewer error.
    """
    try:
        raw = await _chat(
            messages    = messages,
            model       = _REVIEWER_MODEL,
            max_tokens  = _REVIEWER_MAX_TOKENS,
            temperature = 0.0,
            node_name = f"{reviewer}_node",
            run_id = run_id,
            project_id = project_id,
        )
    except Exception as exc:
        log.error("_call_reviewer | %s | LLM call failed: %s", reviewer, exc)
        return ReviewerVerdict(
            reviewer = reviewer,
            passed   = False,
            feedback = f"{reviewer} LLM call failed: {exc}",
            severity = "blocking",
            attempt  = attempt,
        )

    parsed = parse_reviewer_verdict(raw, reviewer)

    return ReviewerVerdict(
        reviewer = reviewer,
        passed   = parsed.passed,
        feedback = parsed.feedback,
        severity = parsed.severity,
        attempt  = attempt,
    )


# ---------------------------------------------------------------------------

async def reduce_verdicts_node(state: TaskState) -> TaskState:
    """
    Collapse the three parallel reviewer verdicts into a single pass/fail.

    Logic:
    - A blocking failure from ANY reviewer â†’ review_passed=False.
    - Advisory failures are logged but do not affect pass/fail.
    - If review_passed=False, aggregated_feedback concatenates all
      blocking feedback strings, labelled by reviewer name.
    - reviewer_verdicts is cleared after reduction so the list doesn't
      grow across retry iterations (the reducer would keep appending).

    Also increments retry_count so developer_node knows which iteration
    it's on if the route sends back for a retry.
    """
    verdicts_raw: list[dict] = state.get("reviewer_verdicts", [])
    retry_count:  int        = state.get("retry_count", 0)

    all_verdicts = [ReviewerVerdict.from_dict(v) for v in verdicts_raw]
    verdicts = [v for v in all_verdicts if v.attempt == retry_count]
    if not verdicts and all_verdicts:
        verdicts = all_verdicts

    blocking_failures = [
        v for v in verdicts
        if not v.passed and v.severity == "blocking"
    ]
    advisory_failures = [
        v for v in verdicts
        if not v.passed and v.severity == "advisory"
    ]

    if advisory_failures:
        for v in advisory_failures:
            log.info(
                "reduce_verdicts | advisory: [%s] %s",
                v.reviewer, v.feedback,
            )

    if blocking_failures:
        feedback_parts = []
        for v in blocking_failures:
            feedback_parts.append(
                f"### {v.reviewer.replace('_', ' ').title()}\n{v.feedback.strip()}"
            )
        aggregated = "\n\n".join(feedback_parts)

        log.info(
            "reduce_verdicts | FAILED | retry=%d | blocking_reviewers=%s",
            retry_count,
            [v.reviewer for v in blocking_failures],
        )

        return {
            **state,
            "review_passed":       False,
            "aggregated_feedback": aggregated,
            "retry_count":         retry_count + 1,
        }

    log.info("reduce_verdicts | PASSED | retry=%d", retry_count)

    return {
        **state,
        "review_passed":       True,
        "aggregated_feedback": None,
    }


# ---------------------------------------------------------------------------

async def finalize_task_node(state: TaskState) -> TaskState:
    """
    Terminal node of the task subgraph.

    On review_passed=True:
      - Write all pending_files to disk via FileStore.save_workspace_file()
      - Set final_status="completed"

    On review_passed=False (retry cap exhausted):
      - Do NOT write any files to disk
      - Set final_status="failed"

    In both cases, writes "_last_task_result" into state so the
    orchestrator's record_task_result node can update the DB without
    needing to re-inspect subgraph state directly.

    File write failures are caught individually â€” if one file fails,
    the others are still written and the task is marked completed with
    a warning, not failed.  A complete write failure marks the task failed.
    """
    task          = TaskRecord.from_dict(state["task"])
    review_passed = state.get("review_passed", False)
    pending       = state.get("pending_files", [])
    retry_count   = state.get("retry_count", 0)
    run_id        = state["run_id"]
    project_id    = state["project_id"]

    log.info(
        "finalize_task_node | task_id=%s | review_passed=%s | files=%d",
        task.id, review_passed, len(pending),
    )

    generated_files: list[str] = []
    write_error: Optional[str] = None

    if review_passed and pending:
        for file_dict in pending:
            gf = GeneratedFile.from_dict(file_dict)
            try:
                await file_store.save_workspace_file(
                    project_id    = project_id,
                    run_id        = run_id,
                    relative_path = gf.relative_path,
                    content       = gf.content,
                )
                generated_files.append(gf.relative_path)
                log.info(
                    "finalize_task_node | wrote %s", gf.relative_path
                )
            except Exception as exc:
                log.error(
                    "finalize_task_node | failed to write %s: %s",
                    gf.relative_path, exc,
                )
                write_error = str(exc)

        if not generated_files:
            # Every file write failed
            final_status = TaskStatus.FAILED.value
            error        = write_error or "All file writes failed."
        else:
            final_status = TaskStatus.COMPLETED.value
            error        = write_error  # partial write warning, non-None but not fatal
    else:
        # review_passed=False with retry cap hit, or no files to write
        final_status = TaskStatus.FAILED.value
        error = state.get("aggregated_feedback") or state.get("error")

    last_result = {
        "task_id":         task.id,
        "final_status":    final_status,
        "retry_count":     retry_count,
        "generated_files": generated_files,
        "feedback":        state.get("aggregated_feedback"),
        "error":           error,
    }

    log.info(
        "finalize_task_node | task_id=%s | final_status=%s | files_written=%d",
        task.id, final_status, len(generated_files),
    )

    return {
        **state,
        "final_status":       final_status,
        "generated_files":    generated_files,
        "_last_task_result":  last_result,
    }


# ---------------------------------------------------------------------------
# ROUTING FUNCTIONS
# ---------------------------------------------------------------------------

def route_orchestrator(state: OrchestratorState) -> str:
    """
    Conditional edge from pick_next_task / record_task_result.

    FAIL          â†’ unrecoverable error set during load_context or bundling
    EXECUTE_TASK  â†’ more tasks remain in the list
    BUNDLE        â†’ all tasks processed, proceed to bundle + approval
    """
    if state.get("error"):
        return OrchestratorRoute.FAIL

    idx   = state.get("current_task_index", 0)
    tasks = state.get("tasks", [])

    if idx < len(tasks):
        return OrchestratorRoute.EXECUTE_TASK

    return OrchestratorRoute.BUNDLE


def route_after_critic(state: TaskState) -> str:
    """
    Conditional edge from critic_node.

    critic_feedback is None  â†’ critic passed â†’ proceed to reviewers (fan-out)
    critic_feedback is set   â†’ critic failed â†’ back to developer for revision
    """
    if state.get("critic_feedback"):
        return TaskRoute.TO_REVIEWERS   # actually goes back to developer
        # Note: the subgraph wires this edge to developer_node, not reviewers.
        # The constant name is TO_REVIEWERS as a default; subgraph.py overrides
        # the routing target for Reflection tasks.  See subgraph.py for wiring.
    return TaskRoute.TO_REVIEWERS


def route_after_reduce(state: TaskState) -> str:
    """
    Conditional edge from reduce_verdicts_node.

    FINALIZE â†’ review passed â†’ write files, complete task
    RETRY    â†’ review failed, retries remain â†’ back to developer
    FAIL     â†’ review failed, retry cap hit â†’ finalize as failed
    """
    review_passed = state.get("review_passed", False)
    retry_count   = state.get("retry_count", 0)
    max_retries   = state.get("max_retries", 3)

    if review_passed:
        return TaskRoute.FINALIZE

    if retry_count <= max_retries:
        return TaskRoute.RETRY

    return TaskRoute.FAIL







