# Code Generated by Sidekick is for learning and experimentation purposes only.
"""
app/workflows/codegen/prompts.py
---------------------------------
All prompt templates and output parsers for the Milestone 5 codegen workflow.

Contents
--------
  build_developer_prompt()   — base developer prompt, pattern-aware
  build_retry_prompt()       — developer retry with aggregated reviewer feedback
  build_critic_prompt()      — Reflection pattern inner critic
  build_workflow_reviewer_prompt()
  build_prompt_reviewer_prompt()
  build_security_reviewer_prompt()
  parse_developer_output()   — extracts GeneratedFile list from LLM response
  parse_reviewer_verdict()   — extracts ReviewerVerdict from JSON response

Output format contract
----------------------
Developer agent:
  One or more <file> blocks, each on its own line:

      <file path="relative/path/to/file.py">
      ...file content...
      </file>

  The parser is strict: it only extracts content inside <file> tags.
  Any text outside the tags (explanation, preamble) is ignored — this
  is intentional so the model can reason freely before writing files.

Reviewer agents:
  A single JSON object — no preamble, no markdown fences:

      {"passed": true, "feedback": "", "severity": "blocking"}
      {"passed": false, "feedback": "Missing input validation on ...", "severity": "blocking"}

  severity "advisory" means the feedback is logged but does not
  count toward pass/fail in reduce_verdicts.

Pattern injection
-----------------
  build_developer_prompt() reads task.pattern_refs and injects a
  pattern-specific section into the prompt.  Each recognised pattern
  tag maps to a PATTERN_GUIDANCE entry that explains the structural
  expectation for the generated code.

  Unrecognised tags are silently skipped — forward-compatibility.
"""

from __future__ import annotations

import json
import re
from dataclasses import dataclass, field
from typing import Optional


# ---------------------------------------------------------------------------
# Pattern guidance blocks
# Injected into the developer prompt when task.pattern_refs contains
# the matching tag.  Keep each block concise — it's appended to the
# prompt verbatim.
# ---------------------------------------------------------------------------

PATTERN_GUIDANCE: dict[str, str] = {
    "Orchestrator-Worker": """
## Pattern: Orchestrator-Worker
Your code must implement a clear orchestrator node that:
- Maintains the task list and dispatches work to worker nodes.
- Does not perform domain work itself — it only routes and aggregates.
- Handles worker failure gracefully (catch exceptions, mark failed, continue).
Worker nodes must:
- Accept a well-defined input slice from the orchestrator.
- Return a well-defined result dict — no side effects on shared state.
""",

    "Plan-and-Execute": """
## Pattern: Plan-and-Execute
Your code must separate planning from execution:
- A planner function/node produces a structured plan (list of steps) before
  any execution begins.  The plan must be inspectable and serialisable.
- An executor function/node consumes the plan sequentially.
- The plan must be stored in state so the SQLite checkpointer can resume
  a partially-executed plan after a crash.
- Never mix planning logic into execution nodes.
""",

    "Reflection": """
## Pattern: Reflection
Your code must implement a self-critique loop:
- After initial generation, a critic node evaluates the output against
  explicit criteria (correctness, completeness, alignment with spec).
- The critic returns structured feedback: {passed: bool, issues: list[str]}.
- The generator iterates on feedback up to a configurable max_iterations.
- The loop must be bounded — always enforce max_iterations to prevent
  infinite cycles.
- Both the generator and critic prompts must be in the codebase as
  named constants, not inline strings.
""",

    "Tool-Use": """
## Pattern: Tool-Use
Your code must define tools as typed Python functions with:
- A clear docstring describing the tool's purpose and parameters
  (LangChain / OpenAI function calling uses these descriptions).
- Explicit input validation before any external call.
- A structured return type — never return raw strings from tools.
- Error handling that raises ToolException (not bare Exception) so the
  ToolNode can route failures correctly.
Tools must be registered in a tools list passed to the ToolNode.
""",

    "Evaluator-Optimizer": """
## Pattern: Evaluator-Optimizer
Your code must implement a generate → evaluate → refine loop:
- The evaluator must return a numeric score OR a structured verdict
  {score: float, passed: bool, feedback: str}.
- The optimizer uses the evaluator's feedback to produce an improved output.
- Loop termination condition: score >= threshold OR iteration >= max_iterations.
- Both threshold and max_iterations must come from config, not hardcoded.
""",

    "Human-in-the-Loop": """
## Pattern: Human-in-the-Loop
Your code must implement a proper HITL interrupt:
- Use LangGraph's interrupt_after to pause the graph at the review node.
- Push a structured approval_request payload over the HITL channel:
  {type: "approval_request", run_id: str, request_id: str, payload: dict}.
- Resume is triggered by an external approval_response — the graph must
  not poll or block a thread.
- Both WebSocket push and REST fallback (POST .../approve) must be wired.
- Store the pending request_id on the Run record so it survives a restart.
""",

    "RAG": """
## Pattern: RAG (Retrieval-Augmented Generation)
Your code must implement retrieval before generation:
- The retriever must be decoupled from the generator — it is a separate
  function/node that returns a list of Document objects.
- Retrieved chunks must be deduped and ranked by relevance score.
- The generator prompt must clearly delimit retrieved context from the
  user query (e.g. a CONTEXT: section before the QUESTION:).
- Never embed raw retrieved text directly into f-strings — always use
  a structured prompt template.
- Retrieval failures must be caught and surfaced as empty context, not
  as exceptions that crash the graph.
""",
}

# Planner output uses a few assignment/domain names that differ from the
# canonical prompt guidance names. Keep aliases explicit so generated tasks get
# the same instructions reviewers expect them to satisfy.
PATTERN_GUIDANCE["Planner-Executor"] = PATTERN_GUIDANCE["Plan-and-Execute"]
PATTERN_GUIDANCE["Critic-Refine"] = PATTERN_GUIDANCE["Reflection"]
PATTERN_GUIDANCE["Critic-Refine (Reflexion)"] = PATTERN_GUIDANCE["Reflection"]
PATTERN_GUIDANCE["Reflexion"] = PATTERN_GUIDANCE["Reflection"]
PATTERN_GUIDANCE["Router"] = """
## Pattern: Router
Your code must expose clear routing boundaries:
- FastAPI routes should be thin adapters that validate input, enforce auth /
  ownership, and delegate workflow behavior to service or graph functions.
- Route handlers must return stable response models and consistent HTTP errors.
- Workflow routing must use explicit conditional branches with exhaustive
  statuses instead of hidden fall-through behavior.
- Keep path/query/body parameters typed and avoid leaking internal exceptions.
"""

# Patterns that trigger a Reflection inner loop in the subgraph.
# build_developer_prompt() uses this to tell the developer a critic is coming.
REFLECTION_PATTERNS = {
    "Reflection",
    "Critic-Refine",
    "Critic-Refine (Reflexion)",
    "Reflexion",
}

# Patterns that require tool infrastructure in the subgraph.
TOOL_USE_PATTERNS = {"Tool-Use"}


def _workflow_pattern_checklist(pattern_refs: list[str]) -> str:
    """Return reviewer checks scoped to the patterns assigned to this task."""
    refs = set(pattern_refs or [])
    checks: list[str] = []

    if refs.intersection({"Orchestrator-Worker"}):
        checks.append("Orchestrator-Worker: verify a dispatch-only orchestrator and separate worker functions.")
    if refs.intersection({"Plan-and-Execute", "Planner-Executor"}):
        checks.append("Plan-and-Execute / Planner-Executor: verify planning is separated from execution for this task slice.")
    if refs.intersection(REFLECTION_PATTERNS):
        checks.append("Reflection / Critic-Refine: verify a bounded generate -> critique -> revise loop where this task owns revision behavior.")
    if refs.intersection(TOOL_USE_PATTERNS):
        checks.append("Tool-Use: verify tools are registered through a ToolNode or equivalent tool registry.")
    if refs.intersection({"Evaluator-Optimizer"}):
        checks.append("Evaluator-Optimizer: verify a structured evaluation gate and bounded optimization loop.")
    if refs.intersection({"Human-in-the-Loop"}):
        checks.append("Human-in-the-Loop: verify interrupt/resume semantics for the current approval or clarification slice.")
    if refs.intersection({"Router"}):
        checks.append("Router: verify route handlers validate inputs, delegate business logic, and return consistent errors.")
    if refs.intersection({"RAG"}):
        checks.append("RAG: verify retrieval is separate from generation and retrieved context is clearly delimited.")

    if not checks:
        return "No pattern-specific topology is required; review only basic coherence for the current task."
    return "\n".join(f"{idx}. {check}" for idx, check in enumerate(checks, start=1))


# ---------------------------------------------------------------------------
# Developer prompt
# ---------------------------------------------------------------------------

def build_developer_prompt(
    *,
    task_title:           str,
    task_description:     str,
    pattern_refs:         list[str],
    requirements_context: str,
    architecture_context: str,
    existing_files:       Optional[list[str]] = None,
    critic_feedback:      Optional[str]       = None,
) -> list[dict]:
    """
    Build the system + user message list for the developer agent.

    Parameters
    ----------
    task_title / task_description
        From the current TaskRecord.

    pattern_refs
        Tags from task.pattern_refs.  Each recognised tag injects a
        PATTERN_GUIDANCE block into the prompt.

    requirements_context / architecture_context
        Full text of the requirements doc and architecture spec, loaded
        once at graph entry and passed through OrchestratorState.

    existing_files
        Relative paths of files already written in the workspace.
        Injected so the developer knows what exists and can import it
        rather than duplicating.

    critic_feedback
        When present, this is a Reflection-pattern iteration — the
        developer has seen a critic's assessment and must revise.

    Returns
    -------
    list[dict]  — OpenAI messages format: [{"role": ..., "content": ...}]
    """

    # -- Pattern guidance blocks ---------------------------------------------
    pattern_sections = []
    for tag in pattern_refs:
        guidance = PATTERN_GUIDANCE.get(tag)
        if guidance:
            pattern_sections.append(guidance.strip())

    pattern_block = "\n\n".join(pattern_sections) if pattern_sections else (
        "No specific patterns are required for this task — "
        "follow clean, idiomatic Python."
    )

    # -- Reflection awareness ------------------------------------------------
    has_reflection = bool(REFLECTION_PATTERNS.intersection(pattern_refs))
    reflection_note = (
        "\n\nNote: A critic agent will review your output before it reaches "
        "the human reviewers.  The critic checks alignment with the "
        "Reflection pattern requirements above.  Write code that is clean "
        "enough to pass that check on the first attempt — but do not let "
        "anticipated critic feedback prevent you from producing complete code."
    ) if has_reflection else ""

    # -- Existing workspace context ------------------------------------------
    if existing_files:
        files_list = "\n".join(f"  - {p}" for p in sorted(existing_files))
        workspace_block = (
            f"The following files have already been written to the workspace "
            f"by earlier tasks.  You may import from them:\n{files_list}"
        )
    else:
        workspace_block = (
            "The workspace is empty — this is the first task.  "
            "You may define shared utilities that later tasks will import."
        )

    # -- Critic feedback block (Reflection iterations only) ------------------
    critic_block = ""
    if critic_feedback:
        critic_block = f"""
---
## Critic Feedback — Revise Your Output

A critic has reviewed your previous attempt and raised the following issues.
You MUST address every point before producing your revised output:

{critic_feedback.strip()}
---
"""

    # -- System message ------------------------------------------------------
    system_message = {
        "role": "system",
        "content": (
            "You are an expert Python software engineer building a production-quality "
            "LangGraph / FastAPI application.  You write clean, well-documented, "
            "type-annotated Python 3.11+ code.\n\n"

            "## Output Format — STRICT\n"
            "You MUST output every file inside a <file> XML tag:\n\n"
            "    <file path=\"relative/path/to/module.py\">\n"
            "    # file content here\n"
            "    </file>\n\n"
            "Rules:\n"
            "- One <file> block per file.  Do not split a file across multiple blocks.\n"
            "- The path attribute is relative to the workspace root.  "
            "Use forward slashes.  No leading slash.\n"
            "- You may write multiple files.  Output them sequentially.\n"
            "- Text outside <file> tags is ignored by the parser.  "
            "You may use that space for brief reasoning, but keep it short.\n"
            "- Never truncate file content — output every line, even for long files.\n"
            "- Do not output placeholder comments like '# ... rest of code ...'  "
            "Every function must be fully implemented.\n\n"

            "## Code Quality Requirements\n"
            "- Full type annotations on all functions and class attributes.\n"
            "- Docstrings on every module, class, and public function.\n"
            "- No bare `except:` — always catch specific exception types.\n"
            "- No hardcoded secrets, connection strings, or credentials.  "
            "Use environment variables or settings objects.\n"
            "- No `print()` statements in production code — use the `logging` module.\n"
            "- Every async function that touches I/O must use `async/await` "
            "consistently — no `asyncio.run()` inside async functions.\n"
        ),
    }

    # -- User message --------------------------------------------------------
    user_message = {
        "role": "user",
        "content": f"""
# Task: {task_title}

## Description
{task_description.strip()}

## Pattern Requirements
{pattern_block}
{reflection_note}

## Requirements Document
<requirements>
{requirements_context.strip()}
</requirements>

## Architecture Specification
<architecture>
{architecture_context.strip()}
</architecture>

## Current Workspace State
{workspace_block}
{critic_block}
## Your Output
Write all files required to implement this task.
Use <file path="..."> blocks as instructed.
Begin now.
""".strip(),
    }

    return [system_message, user_message]


# ---------------------------------------------------------------------------
# Retry prompt (developer receives aggregated reviewer feedback)
# ---------------------------------------------------------------------------

def build_retry_prompt(
    *,
    task_title:           str,
    task_description:     str,
    pattern_refs:         list[str],
    requirements_context: str,
    architecture_context: str,
    developer_output:     str,
    aggregated_feedback:  str,
    retry_number:         int,
    max_retries:          int,
    existing_files:       Optional[list[str]] = None,
) -> list[dict]:
    """
    Build the message list for a retry iteration.

    This is separate from build_developer_prompt() because the framing
    is meaningfully different: the developer is revising existing output
    rather than starting from scratch, and needs to see both its previous
    attempt and the specific reviewer objections.

    The previous output is included in full so the model doesn't need to
    regenerate unchanged files — it can output only the files that need
    fixing.  The parser in nodes.py always takes the latest version of
    each path, so re-outputting unchanged files is also fine.
    """

    pattern_sections = []
    for tag in pattern_refs:
        guidance = PATTERN_GUIDANCE.get(tag)
        if guidance:
            pattern_sections.append(guidance.strip())
    pattern_block = "\n\n".join(pattern_sections) if pattern_sections else (
        "No specific patterns required — follow clean idiomatic Python."
    )

    if existing_files:
        files_list = "\n".join(f"  - {p}" for p in sorted(existing_files))
        workspace_block = f"Files already in workspace:\n{files_list}"
    else:
        workspace_block = "No other files in workspace yet."

    system_message = {
        "role": "system",
        "content": (
            "You are an expert Python software engineer revising code based on "
            "reviewer feedback.  Your task is to address every reviewer objection "
            "and re-output corrected files.\n\n"

            "## Output Format — STRICT (same as before)\n"
            "Output every revised file inside a <file path=\"...\"> block.\n"
            "You may re-output unchanged files — the parser takes the latest "
            "version of each path.\n"
            "Never truncate file content.  Never output placeholder comments.\n"
        ),
    }

    user_message = {
        "role": "user",
        "content": f"""
# Revision Attempt {retry_number} of {max_retries}
# Task: {task_title}

## What You Must Fix
The reviewers rejected your previous output.  
You MUST address every point below before re-submitting:

<reviewer_feedback>
{aggregated_feedback.strip()}
</reviewer_feedback>

## Your Previous Output (for reference)
<previous_output>
{developer_output.strip()}
</previous_output>

## Task Description (reminder)
{task_description.strip()}

## Pattern Requirements (reminder)
{pattern_block}

## Requirements Document
<requirements>
{requirements_context.strip()}
</requirements>

## Architecture Specification
<architecture>
{architecture_context.strip()}
</architecture>

## Current Workspace State
{workspace_block}

## Your Revised Output
Re-output all files that need changes (and any others you want to include).
Use <file path="..."> blocks.  Begin now.
""".strip(),
    }

    return [system_message, user_message]


# ---------------------------------------------------------------------------
# Critic prompt (Reflection pattern inner loop)
# ---------------------------------------------------------------------------

def build_critic_prompt(
    *,
    task_title:       str,
    task_description: str,
    pattern_refs:     list[str],
    developer_output: str,
) -> list[dict]:
    """
    Build the message list for the Reflection-pattern critic node.

    The critic runs BEFORE the human reviewers.  Its job is to catch
    structural issues — missing implementations, wrong pattern usage,
    obvious logic errors — so the human reviewers only see code that
    is at least structurally sound.

    The critic returns a JSON object, not prose:
        {
          "passed": bool,
          "issues": ["issue 1", "issue 2", ...],
          "feedback": "consolidated feedback string for the developer"
        }

    "passed": true means the critic is satisfied and the code should
    proceed to the human reviewers.  The issues list should be empty.
    "passed": false means the developer must revise.
    """

    pattern_names = ", ".join(pattern_refs) if pattern_refs else "none"

    system_message = {
        "role": "system",
        "content": (
            "You are a senior code reviewer performing an internal quality gate "
            "before human reviewers see the code.  You are thorough but fair — "
            "you do not invent problems that aren't there.\n\n"

            "## Your Output Format — STRICT\n"
            "Respond with ONLY a JSON object.  No preamble, no markdown fences:\n\n"
            '    {"passed": true, "issues": [], "feedback": ""}\n'
            "    or\n"
            '    {"passed": false, "issues": ["Missing input validation on X", ...], '
            '"feedback": "Consolidated feedback string for the developer."}\n\n'

            "Do not include any text outside the JSON object."
        ),
    }

    user_message = {
        "role": "user",
        "content": f"""
# Critic Review
# Task: {task_title}
# Required patterns: {pattern_names}

## Task Description
{task_description.strip()}

## Developer Output to Review
<developer_output>
{developer_output.strip()}
</developer_output>

## What to Check
1. **Completeness**: Are all files needed for this task present?
   Are all functions fully implemented (no stubs, no TODOs, no truncations)?

2. **Pattern compliance**: Does the code correctly implement each of the
   following patterns: {pattern_names}?
   Check structure, not style — missing orchestrator dispatch, unbounded
   loops, wrong node topology, etc. are blocking issues.

3. **Imports**: Do all import statements reference modules that either
   exist in the workspace or are standard library / known third-party packages?

4. **Obvious logic errors**: Division by zero, index out of bounds on
   guaranteed-empty lists, awaiting non-coroutines, etc.

5. **Type annotations**: Are all public function signatures annotated?

Do NOT flag style nits (variable names, comment density, minor formatting).
Focus on issues that would cause runtime failures or pattern misalignment.

Respond with your JSON verdict now.
""".strip(),
    }

    return [system_message, user_message]


# ---------------------------------------------------------------------------
# Reviewer prompts
# ---------------------------------------------------------------------------

_REVIEWER_SYSTEM_BASE = (
    "You are a specialised code reviewer.  You evaluate generated code "
    "against a specific dimension described below.\n\n"
    "## Review Scope\n"
    "The code is generated one implementation task at a time. Review only the "
    "current task responsibility. Do not fail a task because other "
    "architecture components, routes, or files that belong to later or earlier "
    "tasks are absent. Treat cross-task or whole-system completeness concerns "
    "as advisory unless the current task explicitly owns that component. A "
    "task should pass when its generated files are coherent, parseable, and "
    "substantively implement the task slice.\n\n"
    "## Your Output Format — STRICT\n"
    "Respond with ONLY a JSON object.  No preamble, no markdown fences:\n\n"
    '    {"passed": true, "feedback": "", "severity": "blocking"}\n'
    "    or\n"
    '    {"passed": false, '
    '"feedback": "Specific, actionable description of each issue found.", '
    '"severity": "blocking"}\n\n'
    'Set severity to "advisory" only for minor nits that should be noted '
    "but do not warrant a retry cycle.  "
    "Default to \"blocking\" for anything that would cause real problems.\n\n"
    "Do not include any text outside the JSON object."
)


def build_workflow_reviewer_prompt(
    *,
    task_title:       str,
    task_description: str,
    pattern_refs:     list[str],
    developer_output: str,
    architecture_context: str,
) -> list[dict]:
    """
    Reviewer 1 — Workflow correctness.

    Checks that the generated agent orchestration matches the selected
    patterns and the architecture specification.  Does not review
    prompt quality or security — those are other reviewers' jobs.
    """

    pattern_names = ", ".join(pattern_refs) if pattern_refs else "none specified"
    required_pattern_checks = _workflow_pattern_checklist(pattern_refs)

    system_message = {
        "role": "system",
        "content": (
            f"{_REVIEWER_SYSTEM_BASE}\n\n"
            "## Your Specialisation: Workflow & Orchestration Correctness\n"
            "You check that the generated code correctly implements the required "
            "agentic patterns and matches the architecture spec.  You do NOT "
            "review prompt quality or security vulnerabilities."
        ),
    }

    user_message = {
        "role": "user",
        "content": f"""
# Workflow Review
# Task: {task_title}
# Required patterns: {pattern_names}

## Task Description
{task_description.strip()}

## Architecture Specification (source of truth)
<architecture>
{architecture_context.strip()}
</architecture>

## Generated Code to Review
<developer_output>
{developer_output.strip()}
</developer_output>

## Required Pattern Checks
{required_pattern_checks}

## What to Check
1. **Pattern topology**: Verify only the required pattern checks listed above.
   Do not require Reflection, Tool-Use, HITL, RAG, or any other pattern unless
   it appears in the Required patterns list for this task.

2. **Task-slice architecture alignment**: Does the implementation match the
   component, interface, or data flow owned by this task? Do not fail because
   components assigned to other tasks are absent.

3. **State management**: If this task defines graph state, is it typed and
   JSON-serialisable? If it does not define graph state, this check is advisory.

4. **Graph completeness**: If this task defines graph edges, are conditional
   branches exhaustive for this slice? If it does not define a graph, this is
   advisory rather than blocking.

5. **Checkpointer compatibility**: No SQLAlchemy objects or non-serialisable
   classes should be placed into LangGraph state when this task creates state.

Respond with your JSON verdict now.
""".strip(),
    }

    return [system_message, user_message]


def build_prompt_reviewer_prompt(
    *,
    task_title:       str,
    task_description: str,
    developer_output: str,
) -> list[dict]:
    """
    Reviewer 2 — Prompt quality.

    Checks generated prompts for clarity, role definition, and
    injection-resistance.  Only fires if the developer output contains
    prompt strings — if the task produced no prompts, the reviewer
    should return passed=True with an advisory note.
    """

    system_message = {
        "role": "system",
        "content": (
            f"{_REVIEWER_SYSTEM_BASE}\n\n"
            "## Your Specialisation: Prompt Quality & Injection Resistance\n"
            "You review LLM prompt strings defined in the generated code.  "
            "You do NOT review workflow structure or security vulnerabilities."
        ),
    }

    user_message = {
        "role": "user",
        "content": f"""
# Prompt Review
# Task: {task_title}

## Task Description
{task_description.strip()}

## Generated Code to Review
<developer_output>
{developer_output.strip()}
</developer_output>

## What to Check
If the generated code contains NO prompt strings (f-strings, string constants
assigned to prompt variables, messages lists), respond with:
{{"passed": true, "feedback": "No prompt strings found — not applicable.", "severity": "advisory"}}

Otherwise, for every prompt string found, check:

1. **Role definition**: Does the system message clearly define the agent's
   role, constraints, and output format?  A vague system message like
   "You are a helpful assistant" is a blocking issue for agent code.

2. **Output format instruction**: Does the prompt explicitly tell the model
   the required output format (JSON schema, XML tags, markdown structure)?
   Prompts that rely on the model "guessing" the format are blocking.

3. **Injection resistance**:
   - Is untrusted user input ever concatenated directly into a prompt
     without a clear delimiter (e.g. <user_input> tags)?
   - Is there a risk that user-supplied text could override system
     instructions?  (e.g. "Ignore previous instructions" attacks.)
   - Are retrieved document chunks clearly delimited from instructions?

4. **Clarity**: Would a different capable engineer understand the prompt's
   intent immediately?  Flag prompts that are ambiguous about what
   "good output" looks like.

5. **Hardcoded content**: Are prompt templates hardcoded as inline strings
   rather than named constants or template files?  Inline strings buried
   inside node functions are harder to maintain and test.

Respond with your JSON verdict now.
""".strip(),
    }

    return [system_message, user_message]


def build_security_reviewer_prompt(
    *,
    task_title:       str,
    task_description: str,
    developer_output: str,
) -> list[dict]:
    """
    Reviewer 3 — Security.

    Checks for OWASP basics: input validation, secrets handling,
    error leakage.  Scoped to what's realistic in LLM-generated
    application code — not a full pentest.
    """

    system_message = {
        "role": "system",
        "content": (
            f"{_REVIEWER_SYSTEM_BASE}\n\n"
            "## Your Specialisation: Security (OWASP Basics)\n"
            "You review generated code for common security issues relevant to "
            "FastAPI / LangGraph application code.  You do NOT review workflow "
            "structure or prompt quality."
        ),
    }

    user_message = {
        "role": "user",
        "content": f"""
# Security Review
# Task: {task_title}

## Task Description
{task_description.strip()}

## Generated Code to Review
<developer_output>
{developer_output.strip()}
</developer_output>

## What to Check

1. **Hardcoded secrets** (BLOCKING):
   - API keys, passwords, tokens, or connection strings hardcoded as
     string literals.
   - Any string matching common secret patterns:
     sk-..., Bearer ..., password=..., secret=... as literals.
   - Fix: must come from environment variables or a settings object.

2. **Input validation** (BLOCKING if missing on external inputs):
   - Treat strongly typed FastAPI parameters (`int`, UUID strings validated by
     Pydantic, enums, constrained fields) as valid input validation unless the
     value is later interpolated into a raw SQL string, shell command, or file
     path.
   - Treat SQLAlchemy ORM/parameterized database calls as SQL-injection safe;
     do not demand extra SQL sanitization for typed integer IDs.
   - FastAPI path/query/body parameters must use Pydantic models or
     explicit type annotations — no raw `request.body()` without parsing.
   - Any value used in a file path must be sanitised against path
     traversal (e.g. `../../../etc/passwd`).
   - Any value used in a shell command must be validated — no
     `subprocess.run(user_input, shell=True)`.

3. **Error leakage** (BLOCKING):
   - Exception handlers must not return raw stack traces or internal
     error messages to the API caller.
   - `except Exception as e: return {{"error": str(e)}}` patterns expose
     internals — must be caught and replaced with a generic message
     while logging the real error server-side.

4. **Sensitive data in logs** (ADVISORY unless obvious):
   - Logging full request bodies that may contain PII or credentials.
   - Logging LLM prompts that may contain retrieved document content.

5. **Insecure deserialization** (BLOCKING if present):
   - Use of `pickle.loads()` on untrusted data.
   - Use of `eval()` or `exec()` on any non-constant string.

6. **Dependency on unvalidated IDs** (BLOCKING):
   - `project_id` or `run_id` values from URL paths used directly in
     filesystem paths without sanitisation.  Must reject values
     containing `..`, `/`, or non-UUID characters.

If none of the above issues are present, respond with passed=true and
a brief "No issues found" feedback.

Respond with your JSON verdict now.
""".strip(),
    }

    return [system_message, user_message]


# ---------------------------------------------------------------------------
# Output parsers
# ---------------------------------------------------------------------------

# Matches <file path="some/path.py"> ... </file>
# re.DOTALL so content can span multiple lines.
_FILE_BLOCK_RE = re.compile(
    r'<file\s+path=["\']([^"\']+)["\']\s*>(.*?)</file>',
    re.DOTALL,
)


@dataclass
class ParsedFile:
    """
    A single file extracted from the developer agent's response.
    Mirrors GeneratedFile from state.py but lives here to avoid a
    circular import (parsers are used in nodes.py which also imports state).
    """
    relative_path: str
    content:       str


def parse_developer_output(raw_output: str) -> list[ParsedFile]:
    """
    Extract all <file path="..."> blocks from the developer agent response.

    Returns a list of ParsedFile instances in document order.
    Strips leading/trailing whitespace from each file's content.

    Raises ValueError if no file blocks are found — the developer node
    should treat this as a generation failure and retry.
    """
    matches = _FILE_BLOCK_RE.findall(raw_output)

    if not matches:
        raise ValueError(
            "Developer output contained no <file> blocks.  "
            "The model likely produced prose without following the output format.  "
            f"Raw output preview: {raw_output[:500]!r}"
        )

    # Deduplicate by path — last occurrence wins (model may revise a file
    # by outputting it again later in the same response).
    seen: dict[str, str] = {}
    for relative_path, content in matches:
        seen[relative_path.strip()] = content.strip()

    return [
        ParsedFile(relative_path=path, content=content)
        for path, content in seen.items()
    ]


@dataclass
class ParsedVerdict:
    """
    A reviewer's verdict extracted from their JSON response.
    Lives here for the same circular-import reason as ParsedFile.
    """
    passed:   bool
    feedback: str  = ""
    severity: str  = "blocking"


def parse_reviewer_verdict(
    raw_output: str,
    reviewer:   str,
) -> ParsedVerdict:
    """
    Parse a reviewer agent's JSON response into a ParsedVerdict.

    Handles two common model misbehaviours:
    1. JSON wrapped in a markdown fence (```json ... ```)
    2. Extra prose before or after the JSON object

    If parsing fails entirely, returns a blocking failure with the raw
    output as feedback — better to force a retry than silently pass.

    Parameters
    ----------
    raw_output : str
        The raw string returned by the reviewer LLM call.
    reviewer : str
        Reviewer identifier for error messages
        ("workflow_reviewer" | "prompt_reviewer" | "security_reviewer").
    """

    # Strip markdown fences if present
    cleaned = re.sub(r"```(?:json)?\s*", "", raw_output).strip()
    cleaned = cleaned.replace("```", "").strip()

    # Attempt to find the first {...} block in the output
    json_match = re.search(r'\{.*\}', cleaned, re.DOTALL)
    if not json_match:
        return ParsedVerdict(
            passed   = False,
            feedback = (
                f"{reviewer} returned a malformed response that could not be "
                f"parsed as JSON.  Raw output: {raw_output[:300]!r}"
            ),
            severity = "blocking",
        )

    try:
        data = json.loads(json_match.group())
    except json.JSONDecodeError as exc:
        return ParsedVerdict(
            passed   = False,
            feedback = (
                f"{reviewer} returned invalid JSON: {exc}.  "
                f"Raw output: {raw_output[:300]!r}"
            ),
            severity = "blocking",
        )

    return ParsedVerdict(
        passed   = bool(data.get("passed", False)),
        feedback = str(data.get("feedback", "")),
        severity = str(data.get("severity", "blocking")),
    )


def parse_critic_output(raw_output: str) -> tuple[bool, str]:
    """
    Parse the critic node's JSON response.

    Returns
    -------
    (passed, feedback)
        passed=True means the code is good enough to proceed to reviewers.
        feedback is the consolidated string to inject into the developer
        retry prompt if passed=False.
    """
    cleaned     = re.sub(r"```(?:json)?\s*", "", raw_output).strip().replace("```", "").strip()
    json_match  = re.search(r'\{.*\}', cleaned, re.DOTALL)

    if not json_match:
        # Treat parse failure as a pass — the critic is an inner gate,
        # not a hard blocker.  Log the issue but don't stall the pipeline.
        return True, ""

    try:
        data = json.loads(json_match.group())
    except json.JSONDecodeError:
        return True, ""

    passed   = bool(data.get("passed", True))
    issues   = data.get("issues", [])
    feedback = data.get("feedback", "")

    if not passed and not feedback and issues:
        feedback = "\n".join(f"- {issue}" for issue in issues)

    return passed, feedback
