# Code Generated by Sidekick is for learning and experimentation purposes only.
"""
app/workflows/codegen/router.py
--------------------------------
FastAPI sub-router for the Milestone 5 Code Generation workflow.

Mounted at:  /projects/{project_id}/codegen
by app/workflows/router.py via include_router().

Endpoints
---------
POST   /runs                             trigger_codegen
GET    /runs                             list_codegen_runs
GET    /runs/{run_id}                    get_codegen_run
POST   /runs/{run_id}/approve            approve_codegen
GET    /runs/{run_id}/bundle/download    download_bundle

Background task pattern
-----------------------
trigger_codegen() returns 202 immediately and fires the orchestrator graph
via FastAPI BackgroundTasks.  Callers poll GET /runs/{run_id} for status.

The background task wrapper catches all exceptions, marks the run failed
in the DB, and logs — it never lets an unhandled exception propagate out
of the background task (which would silently swallow it in FastAPI).

Authentication
--------------
All endpoints use get_current_user from app.auth.dependencies.
Project-level access is verified via verify_project_access() which
confirms the authenticated user has read/write access to project_id.
"""

from __future__ import annotations

import logging
import os
from typing import Optional

from fastapi import APIRouter, BackgroundTasks, Depends, HTTPException, Path, Query
from fastapi.responses import FileResponse
from sqlalchemy import select
from sqlalchemy.ext.asyncio import AsyncSession

from app.auth.dependencies import get_current_user
from app.auth.models import User
from app.storage.database import get_db as get_async_db
from app.storage.models import Run
from app.workflows.codegen.runner import (
    create_codegen_run,
    execute_codegen_run,
    resume_codegen_run,
    trigger_codegen_run as _legacy_trigger_codegen_run,
)
from app.workflows.codegen.schemas import (
    ApproveCodegenRequest,
    ApproveCodegenResponse,
    CodegenRunDetail,
    CodegenRunListItem,
    TaskSummary,
    TriggerCodegenRequest,
    TriggerCodegenResponse,
)
from app.workflows.models import Task, TaskStatus

log = logging.getLogger(__name__)

router = APIRouter(
    prefix="/codegen",
    tags=["codegen"],
)


def _status_value(status) -> str:
    """Return a stable string for enum or raw string statuses."""
    return status.value if hasattr(status, "value") else str(status)


def _should_commit_session(db: AsyncSession) -> bool:
    """Commit route-created runs unless the caller supplied an in-memory test DB."""
    try:
        bind = db.get_bind()
        url = str(getattr(bind, "url", ""))
    except Exception:
        return True
    return ":memory:" not in url


async def trigger_codegen_run(
    *,
    project_id: str,
    architecture_run_id: str,
    document_ids: Optional[list[str]] = None,
    max_retries: int = 3,
    idempotency_key: Optional[str] = None,
    run_id: Optional[str] = None,
) -> dict:
    """Compatibility entrypoint for router-level background trigger patches."""
    if run_id:
        return await execute_codegen_run(run_id=run_id, project_id=project_id)
    return await _legacy_trigger_codegen_run(
        project_id=project_id,
        architecture_run_id=architecture_run_id,
        document_ids=document_ids,
        max_retries=max_retries,
        idempotency_key=idempotency_key,
    )
# ---------------------------------------------------------------------------
# Dependency: project access guard
# ---------------------------------------------------------------------------

async def verify_project_access(
    project_id: str = Path(..., description="Parent project UUID"),
    current_user: User = Depends(get_current_user),
    db: AsyncSession = Depends(get_async_db),
) -> str:
    """
    Confirm the authenticated user has access to project_id.

    Raises 404 if the project doesn't exist (we don't leak existence
    to unauthorised callers — 404 rather than 403).
    Raises 403 if the user exists but lacks access.

    Returns project_id on success so downstream endpoints can use it
    via Depends() without re-declaring the Path param.
    """
    from app.projects.models import Project  # local import — avoids circular
    from app.dependencies import check_project_membership

    project = await db.get(Project, project_id)
    if not project:
        raise HTTPException(status_code=404, detail="Project not found.")

    await check_project_membership(
        project=project,
        user=current_user,
        db=db,
    )
    return project_id


# ---------------------------------------------------------------------------
# Background task runner
# ---------------------------------------------------------------------------

async def _run_codegen_background(
    *,
    run_id:              str,
    project_id:          str,
    architecture_run_id: str,
    document_ids:        Optional[list[str]] = None,
    max_retries:         int = 3,
    idempotency_key:     Optional[str] = None,
) -> None:
    """
    Wrapper for execute_codegen_run() that runs in a BackgroundTask.

    The Run row is created before this fires, so callers can poll the real
    run_id immediately after POST /runs returns.
    """
    try:
        result = await trigger_codegen_run(
            run_id=run_id,
            project_id=project_id,
            architecture_run_id=architecture_run_id,
            document_ids=document_ids,
            max_retries=max_retries,
            idempotency_key=idempotency_key,
        )
        log.info(
            "_run_codegen_background | completed | project_id=%s | run_id=%s | result=%s",
            project_id, run_id, result,
        )
    except Exception as exc:
        log.exception(
            "_run_codegen_background | unhandled exception | project_id=%s | run_id=%s | error=%s",
            project_id, run_id, exc,
        )


# ---------------------------------------------------------------------------
# Helper: build CodegenRunDetail from ORM objects
# ---------------------------------------------------------------------------

async def _build_run_detail(
    run:    Run,
    db:     AsyncSession,
) -> CodegenRunDetail:
    """
    Construct a CodegenRunDetail response from a Run ORM row plus its
    associated Task rows.

    Reads output_data for bundle_path, manifest, and hitl_request_id
    rather than re-querying the graph state — these are persisted by
    _finalise_run() in runner.py.
    """
    run_id = run.id

    # -- Load tasks -----------------------------------------------------------
    tasks_result = await db.execute(
        select(Task)
        .where(Task.run_id == run_id)
        .order_by(Task.order_index)
    )
    tasks: list[Task] = list(tasks_result.scalars().all())

    task_summaries = [
        TaskSummary(
            id              = t.id,
            title           = t.title,
            order_index     = t.order_index,
            status          = t.status,
            pattern_refs    = t.pattern_refs or [],
            retry_count     = t.retry_count,
            generated_files = t.generated_files or [],
            feedback        = t.feedback,
            error           = t.error,
            started_at      = t.started_at,
            finished_at     = t.finished_at,
        )
        for t in tasks
    ]

    completed = sum(1 for t in tasks if _status_value(t.status) == TaskStatus.COMPLETED.value)
    failed    = sum(1 for t in tasks if _status_value(t.status) == TaskStatus.FAILED.value)

    # -- Extract from output_data -------------------------------------------
    output          = run.output_data or {}
    input_data      = run.input_data  or {}
    run_metadata    = run.run_metadata or {}

    bundle_path     = output.get("bundle_path")
    manifest        = output.get("manifest", {})
    hitl_request_id = output.get("hitl_request_id") or run.pending_hitl_request_id
    all_files       = manifest.get("all_files", []) if manifest else []

    arch_run_id = (
        input_data.get("architecture_run_id")
        or run_metadata.get("architecture_run_id", "")
    )

    return CodegenRunDetail(
        run_id               = run_id,
        project_id           = run.project_id,
        architecture_run_id  = arch_run_id,
        status               = _status_value(run.status),
        max_retries          = input_data.get("max_retries", 3),
        started_at           = run.started_at,
        finished_at          = run.finished_at,
        error                = run.error,
        tasks                = task_summaries,
        completed_task_count = completed,
        failed_task_count    = failed,
        total_task_count     = len(tasks),
        bundle_path          = bundle_path,
        all_files            = all_files,
        manifest             = manifest or {},
        final_approval       = output.get("final_approval") or (manifest or {}).get("final_approval"),
        hitl_request_id      = hitl_request_id,
        pending_approval     = bool(hitl_request_id and _status_value(run.status) == "paused_hitl"),
    )


# ---------------------------------------------------------------------------
# POST /runs  — trigger
# ---------------------------------------------------------------------------

@router.post(
    "/runs",
    status_code=202,
    response_model=TriggerCodegenResponse,
    summary="Trigger a new codegen run",
    responses={
        202: {"description": "Run accepted and queued."},
        400: {"description": "Invalid request — missing tasks or bad architecture run."},
        404: {"description": "Project or architecture run not found."},
        409: {"description": "A run is already in progress for this architecture run."},
    },
)
async def trigger_codegen(
    body:           TriggerCodegenRequest,
    background:     BackgroundTasks,
    project_id:     str                = Depends(verify_project_access),
    current_user:   User               = Depends(get_current_user),
    db:             AsyncSession       = Depends(get_async_db),
) -> TriggerCodegenResponse:
    """
    Trigger a new codegen run against a completed architecture run.

    Returns 202 immediately.  The graph runs in the background.
    Poll GET /runs/{run_id} for live status.

    A 409 is returned if a non-failed, non-cancelled run already exists
    for this architecture_run_id within the project — use the returned
    run_id to track the existing run.
    """
    log.info(
        "POST /codegen/runs | project_id=%s | arch_run=%s | user=%s",
        project_id, body.architecture_run_id, current_user.id,
    )

    # -- Conflict check: active run for same architecture run ----------------
    existing = (await db.execute(
        select(Run).where(
            Run.project_id    == project_id,
            Run.workflow_type == "codegen",
        ).order_by(Run.started_at.desc())
    )).scalars().all()

    for existing_run in existing:
        meta = existing_run.run_metadata or {}
        inp  = existing_run.input_data   or {}
        arch = meta.get("architecture_run_id") or inp.get("architecture_run_id")
        if (
            arch == body.architecture_run_id
            and body.idempotency_key
            and (meta.get("idempotency_key") == body.idempotency_key)
        ):
            continue
        if (
            arch == body.architecture_run_id
            and _status_value(existing_run.status) not in ("failed", "cancelled", "completed")
        ):
            raise HTTPException(
                status_code=409,
                detail=(
                    f"A codegen run (id={existing_run.id!r}) is already active "
                    f"for architecture run {body.architecture_run_id!r}.  "
                    f"Current status: {_status_value(existing_run.status)!r}."
                ),
            )

    # -- Validate architecture run exists and is completed -------------------
    arch_run: Optional[Run] = (await db.execute(
        select(Run).where(Run.id == body.architecture_run_id)
    )).scalar_one_or_none()

    if not arch_run or arch_run.project_id != project_id:
        raise HTTPException(
            status_code=404,
            detail=f"Architecture run {body.architecture_run_id!r} not found.",
        )
    if _status_value(arch_run.status) != "completed":
        raise HTTPException(
            status_code=400,
            detail=(
                f"Architecture run {body.architecture_run_id!r} is not completed "
                f"(status={_status_value(arch_run.status)!r}).  "
                "Approve the architecture workflow before triggering codegen."
            ),
        )

    output = arch_run.output_data or {}
    if not output.get("tasks"):
        raise HTTPException(
            status_code=400,
            detail=(
                f"Architecture run {body.architecture_run_id!r} has no tasks "
                "in output_data['tasks'].  The architecture workflow must produce "
                "a task list before codegen can be triggered."
            ),
        )

    # -- Create run before scheduling so the caller receives a real run_id ----
    try:
        created = await create_codegen_run(
            project_id          = project_id,
            architecture_run_id = body.architecture_run_id,
            document_ids        = body.document_ids,
            max_retries         = body.max_retries,
            idempotency_key     = body.idempotency_key,
            db                  = db,
            commit              = _should_commit_session(db),
        )
    except ValueError as exc:
        raise HTTPException(status_code=400, detail=str(exc))

    if created.get("created", True):
        background.add_task(
            _run_codegen_background,
            run_id              = created["run_id"],
            project_id          = project_id,
            architecture_run_id = body.architecture_run_id,
            document_ids        = body.document_ids,
            max_retries         = body.max_retries,
            idempotency_key     = body.idempotency_key,
        )

    status = "queued" if created.get("created", True) else created.get("status", "queued")
    message = (
        f"Codegen run {created['run_id']!r} queued for architecture run "
        f"{body.architecture_run_id!r}."
        if created.get("created", True)
        else created.get("message", "Existing codegen run returned.")
    )
    return TriggerCodegenResponse(
        run_id     = created["run_id"],
        project_id = project_id,
        status     = status,
        message    = message,
    )


# ---------------------------------------------------------------------------
# GET /runs  — list
# ---------------------------------------------------------------------------

@router.get(
    "/runs",
    response_model=list[CodegenRunListItem],
    summary="List codegen runs for a project",
)
async def list_codegen_runs(
    project_id:   str          = Depends(verify_project_access),
    limit:        int          = Query(default=20, ge=1, le=100),
    offset:       int          = Query(default=0,  ge=0),
    status:       Optional[str] = Query(default=None, description="Filter by status"),
    db:           AsyncSession = Depends(get_async_db),
    current_user: User         = Depends(get_current_user),
) -> list[CodegenRunListItem]:
    """
    Return a paginated list of codegen runs for the project.

    Sorted by started_at descending (most recent first).
    Optionally filtered by status: running | completed | failed |
    paused_hitl | cancelled.
    """
    query = (
        select(Run)
        .where(
            Run.project_id    == project_id,
            Run.workflow_type == "codegen",
        )
        .order_by(Run.started_at.desc())
        .limit(limit)
        .offset(offset)
    )

    if status:
        query = query.where(Run.status == status)

    runs: list[Run] = list((await db.execute(query)).scalars().all())

    items = []
    for run in runs:
        input_data   = run.input_data   or {}
        run_metadata = run.run_metadata or {}
        output       = run.output_data  or {}

        arch_run_id = (
            input_data.get("architecture_run_id")
            or run_metadata.get("architecture_run_id", "")
        )

        completed = len(output.get("completed_task_ids", []))
        failed    = len(output.get("failed_task_ids",    []))
        total     = completed + failed  # best effort without loading tasks

        items.append(CodegenRunListItem(
            run_id               = run.id,
            project_id           = run.project_id,
            architecture_run_id  = arch_run_id,
            status               = _status_value(run.status),
            started_at           = run.started_at,
            finished_at          = run.finished_at,
            completed_task_count = completed,
            failed_task_count    = failed,
            total_task_count     = total,
        ))

    return items


# ---------------------------------------------------------------------------
# GET /runs/{run_id}  — detail
# ---------------------------------------------------------------------------

@router.get(
    "/runs/{run_id}",
    response_model=CodegenRunDetail,
    summary="Get codegen run detail",
    responses={
        404: {"description": "Run not found or belongs to a different project."},
    },
)
async def get_codegen_run(
    run_id:       str          = Path(..., description="Codegen run UUID"),
    project_id:   str          = Depends(verify_project_access),
    db:           AsyncSession = Depends(get_async_db),
    current_user: User         = Depends(get_current_user),
) -> CodegenRunDetail:
    """
    Return full detail for a single codegen run, including per-task status,
    generated file list, bundle path, and HITL state.

    404 is returned if the run doesn't exist OR belongs to a different
    project — we don't leak cross-project run existence.
    """
    run: Optional[Run] = (await db.execute(
        select(Run).where(
            Run.id            == run_id,
            Run.project_id    == project_id,
            Run.workflow_type == "codegen",
        )
    )).scalar_one_or_none()

    if not run:
        raise HTTPException(
            status_code=404,
            detail=f"Codegen run {run_id!r} not found.",
        )

    return await _build_run_detail(run, db)


# ---------------------------------------------------------------------------
# POST /runs/{run_id}/approve  — human approval gate
# ---------------------------------------------------------------------------

@router.post(
    "/runs/{run_id}/approve",
    response_model=ApproveCodegenResponse,
    summary="Approve or reject a completed codegen bundle",
    responses={
        200: {"description": "Approval decision recorded."},
        400: {"description": "Missing feedback on rejection, or run not paused."},
        404: {"description": "Run not found."},
    },
)
async def approve_codegen(
    body:         ApproveCodegenRequest,
    run_id:       str          = Path(..., description="Codegen run UUID"),
    project_id:   str          = Depends(verify_project_access),
    db:           AsyncSession = Depends(get_async_db),
    current_user: User         = Depends(get_current_user),
) -> ApproveCodegenResponse:
    """
    Record a human approval or rejection for a codegen bundle.

    The run must be in status `paused_hitl` — any other status returns 400.
    Rejection requires a `feedback` string explaining the reason.

    On approval:   run status → completed
    On rejection:  run status → failed, rejection reason stored on run record

    This endpoint does NOT re-invoke the graph — codegen runs end after
    the bundle is created.  Approval is a terminal state update only.
    To re-run after rejection, trigger a new codegen run.
    """
    log.info(
        "POST /codegen/runs/%s/approve | project_id=%s | approved=%s | user=%s",
        run_id, project_id, body.approved, current_user.id,
    )

    # -- Validate run exists and belongs to this project ---------------------
    run: Optional[Run] = (await db.execute(
        select(Run).where(
            Run.id            == run_id,
            Run.project_id    == project_id,
            Run.workflow_type == "codegen",
        )
    )).scalar_one_or_none()

    if not run:
        raise HTTPException(
            status_code=404,
            detail=f"Codegen run {run_id!r} not found.",
        )

    if _status_value(run.status) != "paused_hitl":
        raise HTTPException(
            status_code=400,
            detail=(
                f"Run {run_id!r} is not awaiting approval "
                f"(status={_status_value(run.status)!r}).  "
                "Only runs with status 'paused_hitl' can be approved or rejected."
            ),
        )

    # -- Validate feedback requirement on rejection --------------------------
    if not body.approved and not body.feedback:
        raise HTTPException(
            status_code=400,
            detail=(
                "A feedback string is required when rejecting a codegen run.  "
                "Provide a clear explanation so the team can trigger a corrected run."
            ),
        )

    # -- Delegate to runner --------------------------------------------------
    try:
        result = await resume_codegen_run(
            run_id     = run_id,
            project_id = project_id,
            approved   = body.approved,
            feedback   = body.feedback,
        )
    except ValueError as exc:
        raise HTTPException(status_code=400, detail=str(exc))
    except Exception as exc:
        log.exception(
            "approve_codegen | unexpected error | run_id=%s | error=%s",
            run_id, exc,
        )
        raise HTTPException(
            status_code=500,
            detail="An unexpected error occurred while processing the approval.",
        )

    # -- Push WebSocket notification to connected clients --------------------
    try:
        from app.hitl.manager import push_to_run
        await push_to_run(
            run_id,
            "approval_response",
            {
                "run_id": run_id,
                "approved": body.approved,
                "status": result["status"],
                "message": result["message"],
            },
        )
    except Exception as exc:
        log.warning("approve_codegen | WS notification failed (non-fatal): %s", exc)
    return ApproveCodegenResponse(
        run_id  = run_id,
        status  = result["status"],
        message = result["message"],
    )


# ---------------------------------------------------------------------------
# GET /runs/{run_id}/artifacts/{filename} - artifact download
# ---------------------------------------------------------------------------

@router.get(
    "/runs/{run_id}/artifacts/{filename}",
    summary="Download a generated codegen artifact",
    responses={
        200: {"description": "Artifact stream."},
        400: {"description": "Invalid filename."},
        404: {"description": "Run or artifact not found."},
    },
)
async def download_codegen_artifact(
    filename:     str,
    run_id:       str          = Path(..., description="Codegen run UUID"),
    project_id:   str          = Depends(verify_project_access),
    db:           AsyncSession = Depends(get_async_db),
    current_user: User         = Depends(get_current_user),
):
    run: Optional[Run] = (await db.execute(
        select(Run).where(
            Run.id            == run_id,
            Run.project_id    == project_id,
            Run.workflow_type == "codegen",
        )
    )).scalar_one_or_none()

    if not run:
        raise HTTPException(status_code=404, detail=f"Codegen run {run_id!r} not found.")

    from app.storage.file_store import file_store

    artifact_dir = os.path.realpath(file_store.artifacts_dir(project_id, run_id))
    file_path = os.path.realpath(os.path.join(artifact_dir, filename))
    if not (file_path == artifact_dir or file_path.startswith(artifact_dir + os.sep)):
        raise HTTPException(status_code=400, detail="Invalid artifact filename.")
    if not os.path.isfile(file_path):
        raise HTTPException(status_code=404, detail=f"Artifact {filename!r} not found.")

    media_type = "application/octet-stream"
    if filename.endswith(".json"):
        media_type = "application/json"
    elif filename.endswith(".zip"):
        media_type = "application/zip"
    elif filename.endswith(".md"):
        media_type = "text/markdown"

    log.info(
        "download_codegen_artifact | run_id=%s | filename=%s | user=%s",
        run_id, filename, current_user.id,
    )
    return FileResponse(path=file_path, media_type=media_type, filename=filename)


# ---------------------------------------------------------------------------
# GET /runs/{run_id}/bundle/download  — bundle download
# ---------------------------------------------------------------------------

@router.get(
    "/runs/{run_id}/bundle/download",
    summary="Download the generated code bundle",
    responses={
        200: {"description": "ZIP file stream."},
        400: {"description": "Bundle not yet available."},
        404: {"description": "Run not found."},
    },
)
async def download_bundle(
    run_id:       str          = Path(..., description="Codegen run UUID"),
    project_id:   str          = Depends(verify_project_access),
    db:           AsyncSession = Depends(get_async_db),
    current_user: User         = Depends(get_current_user),
):
    """
    Stream the bundle.zip for a completed codegen run.

    Returns 400 if the run hasn't completed bundling yet.
    The bundle path is read from run.output_data["bundle_path"] which
    is set by bundle_workspace in nodes.py.

    Note: For large bundles in production, replace FileResponse with
    a pre-signed S3 URL redirect.  FileResponse streams synchronously
    from disk — appropriate for bundles up to ~100 MB.
    """
    run: Optional[Run] = (await db.execute(
        select(Run).where(
            Run.id            == run_id,
            Run.project_id    == project_id,
            Run.workflow_type == "codegen",
        )
    )).scalar_one_or_none()

    if not run:
        raise HTTPException(
            status_code=404,
            detail=f"Codegen run {run_id!r} not found.",
        )

    output      = run.output_data or {}
    bundle_path = output.get("bundle_path")

    if not bundle_path:
        raise HTTPException(
            status_code=400,
            detail=(
                f"Bundle not yet available for run {run_id!r} "
                f"(status={_status_value(run.status)!r}).  "
                "Wait for the run to reach 'paused_hitl' or 'completed' status."
            ),
        )

    if not os.path.isfile(bundle_path):
        raise HTTPException(
            status_code=404,
            detail=(
                f"Bundle file not found on disk at {bundle_path!r}.  "
                "The file may have been cleaned up — contact support."
            ),
        )

    filename = f"codegen_{run_id[:8]}.zip"

    log.info(
        "download_bundle | run_id=%s | path=%s | user=%s",
        run_id, bundle_path, current_user.id,
    )

    return FileResponse(
        path         = bundle_path,
        media_type   = "application/zip",
        filename     = filename,
    )
