# Code Generated by Sidekick is for learning and experimentation purposes only.
"""
app/workflows/codegen/runner.py
--------------------------------
Entry point for triggering and resuming codegen workflow runs.

Public API
----------
    get_orchestrator()              â†’ singleton compiled graph + checkpointer
    trigger_codegen_run(...)        â†’ seed tasks, create Run, invoke graph
    resume_codegen_run(...)         â†’ resume a paused_hitl run after approval

Run lock
--------
A per-run asyncio.Lock prevents concurrent invocations of the same run_id.
This matters because the LangGraph SQLite checkpointer is not safe for
concurrent writers on the same thread_id.  The lock is process-local â€”
in a multi-worker deployment, Redis-backed distributed locking should
replace it.  A TODO marks that callout.

Checkpointer
------------
AsyncSqliteSaver is created once at first call to get_orchestrator()
and reused for all subsequent calls.  The SQLite DB path comes from
settings.CHECKPOINT_DB_PATH (defaults to "checkpoints/codegen.db").
The directory is created if it doesn't exist.

Task seeding
------------
trigger_codegen_run() reads the architecture run's output_data["tasks"]
(a list of task dicts written by Milestone 4) and creates Task ORM rows
before the graph is invoked.  load_context then reads these rows.

Expected architecture output_data["tasks"] schema
--------------------------------------------------
    [
      {
        "title":       str,
        "description": str,
        "order_index": int,          # optional â€” inferred from list position if absent
        "pattern_refs": list[str],   # optional â€” defaults to []
      },
      ...
    ]

If output_data["tasks"] is absent, trigger_codegen_run raises ValueError
with a clear message â€” codegen cannot proceed without a task list.
"""

from __future__ import annotations

import asyncio
import json
import logging
import os
import uuid
from contextlib import asynccontextmanager
from datetime import datetime, timezone
from typing import Any, AsyncGenerator, Optional

from langgraph.checkpoint.sqlite.aio import AsyncSqliteSaver
from langgraph.types import Command
from sqlalchemy import select

from app.config import get_settings
from app.sse.manager import emit_event
from app.storage.database import AsyncSessionLocal
from app.storage.file_store import file_store
from app.storage.models import Run
from app.workflows.codegen.graph import build_orchestrator_graph
from app.workflows.codegen.state import OrchestratorState
from app.workflows.models import Task, TaskStatus, RunStatus

log      = logging.getLogger(__name__)
settings = get_settings()

# ---------------------------------------------------------------------------
# Run lock registry
# One asyncio.Lock per run_id â€” prevents concurrent graph invocations
# on the same thread (same run_id).
#
# TODO: Replace with Redis-backed distributed lock for multi-worker
# deployments.  The current implementation is process-local only.
# ---------------------------------------------------------------------------
_run_locks: dict[str, asyncio.Lock] = {}
_run_locks_meta_lock = asyncio.Lock()   # guards mutations to _run_locks


async def _get_run_lock(run_id: str) -> asyncio.Lock:
    """Get or create the asyncio.Lock for run_id."""
    async with _run_locks_meta_lock:
        if run_id not in _run_locks:
            _run_locks[run_id] = asyncio.Lock()
        return _run_locks[run_id]


def _release_run_lock(run_id: str) -> None:
    """Remove the lock entry after a run completes (keeps dict from growing unbounded)."""
    _run_locks.pop(run_id, None)


# ---------------------------------------------------------------------------
# Orchestrator singleton
# ---------------------------------------------------------------------------

_orchestrator_instance: Optional[Any] = None   # CompiledGraph
_checkpointer_instance: Optional[AsyncSqliteSaver] = None
_checkpointer_context: Optional[Any] = None


async def get_orchestrator() -> Any:
    """
    Return the singleton compiled orchestrator graph.

    Creates the AsyncSqliteSaver checkpointer and compiles the graph on
    first call.  Subsequent calls return the cached instance.

    Thread safety: asyncio is single-threaded within a worker â€” no lock
    needed here.  In a multi-threaded context, wrap with asyncio.Lock.
    """
    global _orchestrator_instance, _checkpointer_instance, _checkpointer_context

    if _orchestrator_instance is not None:
        return _orchestrator_instance

    db_path = getattr(settings, "CHECKPOINT_DB_PATH", "checkpoints/codegen.db")

    # Ensure the directory exists
    os.makedirs(os.path.dirname(db_path) or ".", exist_ok=True)

    log.info("get_orchestrator | initialising checkpointer at %s", db_path)

    _checkpointer_context = AsyncSqliteSaver.from_conn_string(db_path)
    _checkpointer_instance = await _checkpointer_context.__aenter__()
    _orchestrator_instance = build_orchestrator_graph(
        checkpointer=_checkpointer_instance,
    )

    log.info("get_orchestrator | orchestrator compiled and ready")
    return _orchestrator_instance

async def close_orchestrator() -> None:
    """Close the shared codegen checkpointer on application/test shutdown."""
    global _orchestrator_instance, _checkpointer_instance, _checkpointer_context
    context = _checkpointer_context
    if context is None and _checkpointer_instance is None:
        return
    _orchestrator_instance = None
    _checkpointer_instance = None
    _checkpointer_context = None
    _run_locks.clear()
    if context is not None:
        await context.__aexit__(None, None, None)


# ---------------------------------------------------------------------------
# DB session helper (local â€” mirrors nodes.py pattern)
# ---------------------------------------------------------------------------

@asynccontextmanager
async def _db_session() -> AsyncGenerator[Any, None]:
    async with AsyncSessionLocal() as session:
        try:
            yield session
            await session.commit()
        except Exception:
            await session.rollback()
            raise


def _status_str(value: Any) -> str:
    """Return a stable string for enum or raw string status values."""
    return value.value if hasattr(value, "value") else str(value)


# ---------------------------------------------------------------------------
# Task seeding
# ---------------------------------------------------------------------------

async def _seed_tasks(
    run_id:       str,
    project_id:   str,
    task_dicts:   list[dict],
    db,
) -> list[Task]:
    """
    Create Task ORM rows for a new codegen run.

    Idempotent: if tasks already exist for this run_id (e.g. a duplicate
    trigger call), we return the existing rows rather than creating duplicates.

    Parameters
    ----------
    task_dicts
        Raw task definitions from the architecture run's output_data["tasks"].
        Each dict must have at minimum a "title" key.

    Returns
    -------
    list[Task]
        The created (or existing) Task rows, ordered by order_index.
    """
    # Idempotency check: if tasks already seeded, return them
    existing = (await db.execute(
        select(Task)
        .where(Task.run_id == run_id)
        .order_by(Task.order_index)
    )).scalars().all()

    if existing:
        log.info(
            "_seed_tasks | run_id=%s | %d tasks already exist â€” skipping seed",
            run_id, len(existing),
        )
        return list(existing)

    tasks: list[Task] = []
    for i, t in enumerate(task_dicts):
        task = Task(
            id           = str(uuid.uuid4()),
            run_id       = run_id,
            title        = t.get("title", f"Task {i + 1}"),
            description  = t.get("description", ""),
            order_index  = t.get("order_index", i),
            pattern_refs = t.get("pattern_refs", []),
            status       = TaskStatus.PENDING.value,
            retry_count  = 0,
            generated_files = [],
        )
        db.add(task)
        tasks.append(task)
        log.debug(
            "_seed_tasks | created task id=%s title=%r order=%d patterns=%s",
            task.id, task.title, task.order_index, task.pattern_refs,
        )

    log.info(
        "_seed_tasks | run_id=%s | seeded %d tasks", run_id, len(tasks)
    )
    return tasks


# ---------------------------------------------------------------------------
# Public: trigger_codegen_run
# ---------------------------------------------------------------------------

async def trigger_codegen_run(
    *,
    project_id:          str,
    architecture_run_id: str,
    document_ids:        Optional[list[str]] = None,
    max_retries:         int                 = 3,
    idempotency_key:     Optional[str]       = None,
) -> dict:
    """
    Seed a new codegen run and invoke the orchestrator graph.

    Steps
    -----
    1.  Verify the architecture run exists and is completed.
    2.  Extract task definitions from architecture run output_data["tasks"].
    3.  Create a Run record (status=RUNNING) for the codegen run.
    4.  Seed Task rows from the architecture task list.
    5.  Acquire the per-run lock (prevent concurrent invocations).
    6.  Invoke the compiled orchestrator graph via ainvoke().
    7.  Update the Run record with final status, output_data, finished_at.
    8.  Release the run lock.

    Parameters
    ----------
    project_id
        Parent project UUID.
    architecture_run_id
        The completed architecture workflow run to execute.
    document_ids
        Optional extra document IDs injected into load_context for
        additional developer agent context.
    max_retries
        Per-task reviewer retry cap.
    idempotency_key
        If provided, checked against existing Run records.  If a run
        with this key already exists and is not FAILED/CANCELLED, we
        return its details rather than starting a duplicate.

    Returns
    -------
    dict
        {
          "run_id":      str,
          "project_id":  str,
          "status":      str,
          "message":     str,
        }
    """
    log.info(
        "trigger_codegen_run | project_id=%s | arch_run=%s | max_retries=%d",
        project_id, architecture_run_id, max_retries,
    )

    # -- Idempotency check ---------------------------------------------------
    if idempotency_key:
        async with _db_session() as db:
            existing_run = (await db.execute(
                select(Run).where(
                    Run.project_id == project_id,
                    Run.workflow_type == "codegen",
                    Run.run_metadata["idempotency_key"].as_string() == idempotency_key,
                )
            )).scalar_one_or_none()

            if existing_run and _status_str(existing_run.status) not in ("failed", "cancelled"):
                log.info(
                    "trigger_codegen_run | idempotency hit | run_id=%s",
                    existing_run.id,
                )
                return {
                    "run_id":     existing_run.id,
                    "project_id": project_id,
                    "status":     _status_str(existing_run.status),
                    "message":    "Existing run returned (idempotency key matched).",
                }

    # -- Verify architecture run ---------------------------------------------
    async with _db_session() as db:
        arch_run: Optional[Run] = (await db.execute(
            select(Run).where(Run.id == architecture_run_id)
        )).scalar_one_or_none()

        if not arch_run:
            raise ValueError(
                f"Architecture run {architecture_run_id!r} not found."
            )
        if _status_str(arch_run.status) != "completed":
            raise ValueError(
                f"Architecture run {architecture_run_id!r} is not completed "
                f"(status={_status_str(arch_run.status)!r}).  "
                "Approve the architecture workflow before triggering codegen."
            )

        # -- Extract task definitions from architecture output ---------------
        output     = arch_run.output_data or {}
        task_dicts = output.get("tasks")

        if not task_dicts:
            raise ValueError(
                f"Architecture run {architecture_run_id!r} has no tasks in "
                "output_data['tasks'].  The architecture workflow must produce "
                "a task list before codegen can be triggered."
            )

        # -- Create codegen Run record ---------------------------------------
        run_id = str(uuid.uuid4())
        run    = Run(
            id            = run_id,
            project_id    = project_id,
            workflow_type = "codegen",
            status        = RunStatus.RUNNING,
            input_data    = {
                "architecture_run_id": architecture_run_id,
                "document_ids":        document_ids or [],
                "max_retries":         max_retries,
            },
            run_metadata  = {
                "idempotency_key":     idempotency_key,
                "architecture_run_id": architecture_run_id,
            },
            started_at    = datetime.now(timezone.utc),
        )
        db.add(run)

        # -- Seed tasks -------------------------------------------------------
        await _seed_tasks(
            run_id     = run_id,
            project_id = project_id,
            task_dicts = task_dicts,
            db         = db,
        )

    log.info(
        "trigger_codegen_run | run created | run_id=%s | tasks=%d",
        run_id, len(task_dicts),
    )

    # -- Build initial OrchestratorState ------------------------------------
    initial_state: OrchestratorState = {
        "run_id":               run_id,
        "project_id":           project_id,
        "architecture_run_id":  architecture_run_id,
        "tasks":                [],          # loaded by load_context
        "current_task_index":   0,
        "max_retries":          max_retries,
        "requirements_context": "",          # loaded by load_context
        "architecture_context": "",          # loaded by load_context
        "completed_task_ids":   [],
        "failed_task_ids":      [],
        "bundle_path":          None,
        "manifest":             None,
        "hitl_request_id":      None,
        "error":                None,
    }

    # -- Invoke graph with run lock ------------------------------------------
    run_lock   = await _get_run_lock(run_id)
    orchestrator = await get_orchestrator()

    graph_config = {
        "configurable": {"thread_id": run_id},
        "recursion_limit": 200,
    }

    async with run_lock:
        try:
            final_state: OrchestratorState = await orchestrator.ainvoke(
                initial_state,
                config=graph_config,
            )
            graph_snapshot = await orchestrator.aget_state(graph_config)
            interrupted = bool(getattr(graph_snapshot, "next", ()))
        except Exception as exc:
            log.exception(
                "trigger_codegen_run | orchestrator raised: %s | run_id=%s",
                exc, run_id,
            )
            await _mark_run_failed(run_id, str(exc))
            _release_run_lock(run_id)
            await close_orchestrator()
            raise

    _release_run_lock(run_id)
    await close_orchestrator()

    # -- Persist final run state to DB ---------------------------------------
    await _finalise_run(run_id, final_state, interrupted=interrupted)
    status = await _get_run_status(run_id)

    if status == "paused_hitl":
        message = "Codegen paused for human approval."
    else:
        message = (
            f"Codegen complete. "
            f"{len(final_state.get('completed_task_ids', []))} task(s) succeeded, "
            f"{len(final_state.get('failed_task_ids', []))} failed."
        )
    log.info(
        "trigger_codegen_run | done | run_id=%s | status=%s", run_id, status
    )

    return {
        "run_id":     run_id,
        "project_id": project_id,
        "status":     status,
        "message":    message,
    }


# ---------------------------------------------------------------------------
# Public: create_codegen_run / execute_codegen_run
# ---------------------------------------------------------------------------

async def create_codegen_run(
    *,
    project_id:          str,
    architecture_run_id: str,
    document_ids:        Optional[list[str]] = None,
    max_retries:         int                 = 3,
    idempotency_key:     Optional[str]       = None,
    db:                  Optional[Any]       = None,
    commit:              bool                = True,
) -> dict:
    """
    Validate inputs, create a pending codegen Run, and seed its Task rows.

    This split lets HTTP triggers return a real run_id immediately while the
    orchestrator graph runs in a background task.  Routes may pass their active
    DB session so dependency overrides and background execution see the same
    created run; direct callers fall back to the application session factory.
    """
    log.info(
        "create_codegen_run | project_id=%s | arch_run=%s | max_retries=%d",
        project_id, architecture_run_id, max_retries,
    )

    async def _create_with_session(session) -> dict:
        if idempotency_key:
            existing_run = (await session.execute(
                select(Run).where(
                    Run.project_id == project_id,
                    Run.workflow_type == "codegen",
                    Run.run_metadata["idempotency_key"].as_string() == idempotency_key,
                )
            )).scalar_one_or_none()
            if existing_run and _status_str(existing_run.status) not in ("failed", "cancelled"):
                return {
                    "run_id":     existing_run.id,
                    "project_id": project_id,
                    "status":     _status_str(existing_run.status),
                    "created":    False,
                    "message":    "Existing run returned (idempotency key matched).",
                }

        arch_run: Optional[Run] = (await session.execute(
            select(Run).where(Run.id == architecture_run_id)
        )).scalar_one_or_none()

        if not arch_run or arch_run.project_id != project_id:
            raise ValueError(f"Architecture run {architecture_run_id!r} not found.")
        if _status_str(arch_run.status) != "completed":
            raise ValueError(
                f"Architecture run {architecture_run_id!r} is not completed "
                f"(status={_status_str(arch_run.status)!r}).  "
                "Approve the architecture workflow before triggering codegen."
            )

        output = arch_run.output_data or {}
        task_dicts = output.get("tasks")
        if not task_dicts:
            raise ValueError(
                f"Architecture run {architecture_run_id!r} has no tasks in "
                "output_data['tasks'].  The architecture workflow must produce "
                "a task list before codegen can be triggered."
            )

        run_id = str(uuid.uuid4())
        run = Run(
            id=run_id,
            project_id=project_id,
            workflow_type="codegen",
            status=RunStatus.PENDING,
            input_data={
                "architecture_run_id": architecture_run_id,
                "document_ids": document_ids or [],
                "max_retries": max_retries,
            },
            output_data={
                "completed_task_ids": [],
                "failed_task_ids": [],
                "bundle_path": None,
                "manifest": {},
                "hitl_request_id": None,
            },
            run_metadata={
                "idempotency_key": idempotency_key,
                "architecture_run_id": architecture_run_id,
                "current_node": "queued",
            },
            started_at=datetime.now(timezone.utc),
        )
        session.add(run)
        await _seed_tasks(
            run_id=run_id,
            project_id=project_id,
            task_dicts=task_dicts,
            db=session,
        )
        await session.flush()

        return {
            "run_id":     run_id,
            "project_id": project_id,
            "status":     RunStatus.PENDING.value,
            "created":    True,
            "message":    "Codegen run created.",
        }

    if db is not None:
        result = await _create_with_session(db)
        if commit:
            await db.commit()
        else:
            await db.flush()
        return result

    async with _db_session() as session:
        return await _create_with_session(session)

def _initial_state_for_run(
    *,
    run_id: str,
    project_id: str,
    architecture_run_id: str,
    max_retries: int,
) -> OrchestratorState:
    return {
        "run_id":               run_id,
        "project_id":           project_id,
        "architecture_run_id":  architecture_run_id,
        "tasks":                [],
        "current_task_index":   0,
        "max_retries":          max_retries,
        "requirements_context": "",
        "architecture_context": "",
        "completed_task_ids":   [],
        "failed_task_ids":      [],
        "bundle_path":          None,
        "manifest":             None,
        "hitl_request_id":      None,
        "error":                None,
    }


async def execute_codegen_run(
    *,
    run_id: str,
    project_id: Optional[str] = None,
) -> dict:
    """Run the orchestrator for an already-created codegen run."""
    async with _db_session() as db:
        db_run: Optional[Run] = await db.get(Run, run_id)
        if not db_run:
            raise ValueError(f"Codegen run {run_id!r} not found.")
        if project_id and db_run.project_id != project_id:
            raise ValueError(f"Codegen run {run_id!r} not found for this project.")
        if db_run.workflow_type != "codegen":
            raise ValueError(f"Run {run_id!r} is not a codegen run.")

        current_status = _status_str(db_run.status)
        if current_status in ("completed", "failed", "cancelled", "paused_hitl"):
            return {
                "run_id":     run_id,
                "project_id": db_run.project_id,
                "status":     current_status,
                "message":    f"Codegen run is already {current_status}.",
            }

        input_data = db_run.input_data or {}
        architecture_run_id = input_data.get("architecture_run_id")
        if not architecture_run_id:
            raise ValueError(f"Codegen run {run_id!r} is missing architecture_run_id.")

        max_retries = int(input_data.get("max_retries", 3))
        actual_project_id = db_run.project_id
        db_run.status = RunStatus.RUNNING
        db_run.started_at = db_run.started_at or datetime.now(timezone.utc)
        meta = db_run.run_metadata or {}
        meta["current_node"] = "load_context"
        db_run.run_metadata = meta

    initial_state = _initial_state_for_run(
        run_id=run_id,
        project_id=actual_project_id,
        architecture_run_id=architecture_run_id,
        max_retries=max_retries,
    )

    run_lock = await _get_run_lock(run_id)
    orchestrator = await get_orchestrator()
    graph_config = {
        "configurable": {"thread_id": run_id},
        "recursion_limit": 200,
    }

    async with run_lock:
        try:
            final_state: OrchestratorState = await orchestrator.ainvoke(
                initial_state,
                config=graph_config,
            )
            graph_snapshot = await orchestrator.aget_state(graph_config)
            interrupted = bool(getattr(graph_snapshot, "next", ()))
        except Exception as exc:
            log.exception("execute_codegen_run | orchestrator raised: %s | run_id=%s", exc, run_id)
            await _mark_run_failed(run_id, str(exc))
            _release_run_lock(run_id)
            await close_orchestrator()
            raise

    _release_run_lock(run_id)
    await close_orchestrator()
    await _finalise_run(run_id, final_state, interrupted=interrupted)
    status = await _get_run_status(run_id)

    if status == "paused_hitl":
        message = "Codegen paused for human approval."
    else:
        message = (
            f"Codegen complete. "
            f"{len(final_state.get('completed_task_ids', []))} task(s) succeeded, "
            f"{len(final_state.get('failed_task_ids', []))} failed."
        )

    return {
        "run_id":     run_id,
        "project_id": actual_project_id,
        "status":     status,
        "message":    message,
    }


# ---------------------------------------------------------------------------
# Public: resume_codegen_run
# ---------------------------------------------------------------------------

async def resume_codegen_run(
    *,
    run_id:     str,
    project_id: str,
    approved:   bool,
    feedback:   Optional[str] = None,
) -> dict:
    """Resume a paused codegen graph with LangGraph Command(resume=...)."""
    log.info("resume_codegen_run | run_id=%s | approved=%s", run_id, approved)

    if not approved and not feedback:
        raise ValueError("Feedback is required when rejecting a codegen run.")

    async with _db_session() as db:
        db_run: Optional[Run] = await db.get(Run, run_id)
        if not db_run or db_run.project_id != project_id:
            raise ValueError(f"Run {run_id!r} not found.")
        if _status_str(db_run.status) != "paused_hitl":
            raise ValueError(
                f"Run {run_id!r} is not paused (status={_status_str(db_run.status)!r}). "
                "Only paused_hitl runs can be resumed."
            )
        request_id = db_run.pending_hitl_request_id

    resume_payload = {
        "type": "approval_response",
        "request_id": request_id,
        "approved": approved,
        "decision": "approve" if approved else "reject",
        "feedback": feedback,
    }

    await emit_event(
        "resume_requested",
        resume_payload,
        run_id=run_id,
        project_id=project_id,
        node_name="request_approval",
        message="Human decision submitted",
    )

    run_lock = await _get_run_lock(run_id)
    orchestrator = await get_orchestrator()
    graph_config = {
        "configurable": {"thread_id": run_id},
        "recursion_limit": 50,
    }

    try:
        async with run_lock:
            final_state: OrchestratorState = await orchestrator.ainvoke(
                Command(resume=resume_payload),
                config=graph_config,
            )
    finally:
        _release_run_lock(run_id)
        await close_orchestrator()

    await _finalise_run(run_id, final_state, interrupted=False)

    status = "completed" if approved else "failed"
    message = "Codegen run approved and completed." if approved else f"Codegen run rejected. Reason: {feedback}"

    async with _db_session() as db:
        db_run = await db.get(Run, run_id)
        if db_run:
            output = dict(db_run.output_data or {})
            output = await _stamp_final_approval(
                output=output,
                project_id=project_id,
                run_id=run_id,
                request_id=request_id,
                approved=approved,
                feedback=feedback,
            )
            if approved:
                output["approved_at"] = datetime.now(timezone.utc).isoformat()
                db_run.status = RunStatus.COMPLETED
                db_run.error = None
            else:
                output["rejected_reason"] = feedback
                db_run.status = RunStatus.FAILED
                db_run.error = feedback or "Rejected by reviewer."
            db_run.pending_hitl_request_id = None
            db_run.pending_hitl_type = None
            db_run.output_data = output
            db_run.finished_at = datetime.now(timezone.utc)

    await emit_event(
        "run_completed" if approved else "run_failed",
        {"status": status, "approved": approved, "feedback": feedback},
        run_id=run_id,
        project_id=project_id,
        message=message,
    )

    log.info("resume_codegen_run | run_id=%s | final_status=%s", run_id, status)
    return {"run_id": run_id, "status": status, "message": message}

# ---------------------------------------------------------------------------
# Internal helpers
# ---------------------------------------------------------------------------


async def _stamp_final_approval(
    *,
    output: dict,
    project_id: str,
    run_id: str,
    request_id: Optional[str],
    approved: bool,
    feedback: Optional[str],
) -> dict:
    """Persist final approval state into MANIFEST.json and rebuild bundle.zip."""
    decided_at = datetime.now(timezone.utc).isoformat()
    final_approval = {
        "status": "approved" if approved else "rejected",
        "approved": approved,
        "decision": "approve" if approved else "reject",
        "feedback": feedback,
        "request_id": request_id,
        "decided_at": decided_at,
    }

    manifest = dict(output.get("manifest") or {})
    manifest["final_approval"] = final_approval
    manifest["approval_state"] = final_approval
    output["manifest"] = manifest
    output["final_approval"] = final_approval
    output["approval_state"] = final_approval
    output["approved"] = approved

    manifest_json = json.dumps(manifest, indent=2)
    try:
        await file_store.save_workspace_file(
            project_id=project_id,
            run_id=run_id,
            relative_path="MANIFEST.json",
            content=manifest_json,
        )
        await file_store.save_artifact(
            project_id=project_id,
            run_id=run_id,
            filename="MANIFEST.json",
            content=manifest_json,
        )
        output["bundle_path"] = file_store.create_bundle(project_id, run_id)
    except Exception as exc:
        log.warning("_stamp_final_approval | bundle rebuild failed | run_id=%s | error=%s", run_id, exc)
    return output

async def _finalise_run(
    run_id: str,
    final_state: OrchestratorState,
    interrupted: bool = False,
) -> None:
    """Write output_data, status, and finished_at without clobbering HITL pauses."""
    has_error = bool(final_state.get("error"))
    final_status = RunStatus.FAILED if has_error else RunStatus.COMPLETED

    async with _db_session() as db:
        db_run: Optional[Run] = await db.get(Run, run_id)
        if not db_run:
            return

        existing_output = dict(db_run.output_data or {})
        output_data = {
            **existing_output,
            "completed_task_ids": final_state.get("completed_task_ids", existing_output.get("completed_task_ids", [])),
            "failed_task_ids": final_state.get("failed_task_ids", existing_output.get("failed_task_ids", [])),
            "bundle_path": final_state.get("bundle_path", existing_output.get("bundle_path")),
            "manifest": final_state.get("manifest", existing_output.get("manifest")),
            "hitl_request_id": final_state.get("hitl_request_id") or existing_output.get("hitl_request_id") or db_run.pending_hitl_request_id,
            "error": final_state.get("error"),
        }

        if interrupted or _status_str(db_run.status) == "paused_hitl":
            db_run.status = RunStatus.PAUSED_HITL
            db_run.output_data = output_data
            log.info("_finalise_run | run_id=%s | status=paused_hitl", run_id)
            return

        db_run.status = final_status
        db_run.output_data = output_data
        db_run.error = final_state.get("error")
        db_run.pending_hitl_request_id = None
        db_run.pending_hitl_type = None
        db_run.finished_at = datetime.now(timezone.utc)

    await emit_event(
        "run_failed" if has_error else "run_completed",
        {"status": final_status.value, "error": final_state.get("error")},
        run_id=run_id,
        project_id=final_state.get("project_id"),
        message="Codegen run finished",
    )
    log.info("_finalise_run | run_id=%s | status=%s", run_id, final_status.value)


async def _get_run_status(run_id: str) -> str:
    async with _db_session() as db:
        db_run: Optional[Run] = await db.get(Run, run_id)
        if not db_run:
            return "unknown"
        return db_run.status.value if hasattr(db_run.status, "value") else str(db_run.status)

async def _mark_run_failed(run_id: str, error: str) -> None:
    """Mark a Run as FAILED â€” called when the orchestrator raises unexpectedly."""
    try:
        async with _db_session() as db:
            db_run: Optional[Run] = await db.get(Run, run_id)
            if db_run:
                db_run.status      = RunStatus.FAILED
                db_run.error       = error
                db_run.finished_at = datetime.now(timezone.utc)
    except Exception as exc:
        log.error("_mark_run_failed | DB update failed: %s", exc)

