# Code Generated by Sidekick is for learning and experimentation purposes only.
"""
app/workflows/codegen/schemas.py
---------------------------------
Pydantic request and response models for the codegen workflow API.

These models are the public contract between the API layer and callers.
They are deliberately separate from the internal state dataclasses
(TaskRecord, GeneratedFile, etc.) in state.py — the internal shapes
can evolve independently of the API contract.

Versioning note
---------------
All models use model_config = ConfigDict(from_attributes=True) so they
can be constructed directly from ORM instances via model_validate().
"""

from __future__ import annotations

from datetime import datetime
from typing import Optional
from pydantic import BaseModel, ConfigDict, Field


# ---------------------------------------------------------------------------
# Request models
# ---------------------------------------------------------------------------

class TriggerCodegenRequest(BaseModel):
    """
    POST /projects/{project_id}/codegen/runs

    Kicks off a new codegen run against a completed architecture run.
    """
    architecture_run_id: str = Field(
        ...,
        description=(
            "ID of the completed architecture workflow run to execute.  "
            "The run must have status='completed' and output_data['tasks'] populated."
        ),
    )
    document_ids: list[str] = Field(
        default_factory=list,
        description=(
            "Optional list of additional document IDs to inject into the "
            "developer agent's context.  Use this to provide supplementary "
            "reference material beyond the architecture spec."
        ),
    )
    max_retries: int = Field(
        default=3,
        ge=1,
        le=10,
        description=(
            "Maximum number of developer→reviewer retry cycles per task.  "
            "Each retry costs one LLM call per reviewer (3 total) plus one "
            "developer call.  Default 3 is appropriate for most tasks."
        ),
    )
    idempotency_key: Optional[str] = Field(
        default=None,
        description=(
            "Optional idempotency key.  If a non-failed, non-cancelled run "
            "with this key already exists for this project, it is returned "
            "instead of starting a new run."
        ),
    )


class ApproveCodegenRequest(BaseModel):
    """
    POST /projects/{project_id}/codegen/runs/{run_id}/approve

    Human approval or rejection of a completed codegen bundle.
    """
    approved: bool = Field(
        ...,
        description="True to approve the bundle; False to reject.",
    )
    feedback: Optional[str] = Field(
        default=None,
        description=(
            "Required when approved=False.  Reason for rejection — "
            "stored on the Run record and surfaced in the detail response."
        ),
    )


# ---------------------------------------------------------------------------
# Response models
# ---------------------------------------------------------------------------

class TriggerCodegenResponse(BaseModel):
    """Returned immediately (202) after a trigger request is accepted."""
    run_id:     str
    project_id: str
    status:     str
    message:    str


class TaskSummary(BaseModel):
    """
    Concise per-task view embedded in CodegenRunDetail.
    Constructed from Task ORM rows.
    """
    model_config = ConfigDict(from_attributes=True)

    id:              str
    title:           str
    order_index:     int
    status:          str
    pattern_refs:    list[str]
    retry_count:     int
    generated_files: list[str]
    feedback:        Optional[str]  = None
    error:           Optional[str]  = None
    started_at:      Optional[datetime] = None
    finished_at:     Optional[datetime] = None


class CodegenRunDetail(BaseModel):
    """
    Detailed run view returned by GET /runs/{run_id}.

    Includes the full task list with per-task status, the bundle path
    (if bundling has completed), and the manifest summary.
    """
    model_config = ConfigDict(from_attributes=True)

    run_id:               str
    project_id:           str
    architecture_run_id:  str
    status:               str
    max_retries:          int
    started_at:           Optional[datetime]  = None
    finished_at:          Optional[datetime]  = None
    error:                Optional[str]       = None

    # Task-level detail
    tasks:                list[TaskSummary]   = Field(default_factory=list)
    completed_task_count: int                 = 0
    failed_task_count:    int                 = 0
    total_task_count:     int                 = 0

    # Bundle output
    bundle_path:          Optional[str]       = None
    all_files:            list[str]           = Field(default_factory=list)
    manifest:             dict                = Field(default_factory=dict)
    final_approval:       Optional[dict]      = None

    # HITL gate
    hitl_request_id:      Optional[str]       = None
    pending_approval:     bool                = False


class ApproveCodegenResponse(BaseModel):
    """Returned after a human approval or rejection decision."""
    run_id:   str
    status:   str
    message:  str


class CodegenRunListItem(BaseModel):
    """
    Compact run summary for list views.
    Returned by GET /projects/{project_id}/codegen/runs.
    """
    model_config = ConfigDict(from_attributes=True)

    run_id:               str
    project_id:           str
    architecture_run_id:  str
    status:               str
    started_at:           Optional[datetime] = None
    finished_at:          Optional[datetime] = None
    completed_task_count: int                = 0
    failed_task_count:    int                = 0
    total_task_count:     int                = 0


class ErrorResponse(BaseModel):
    """Uniform error shape for all 4xx/5xx responses from this router."""
    detail: str
    run_id: Optional[str] = None
