# Code Generated by Sidekick is for learning and experimentation purposes only.
"""
app/workflows/codegen/state.py
------------------------------
LangGraph state definitions for the Milestone 5 Code Generation workflow.

Architecture
------------
Two distinct state scopes:

  OrchestratorState
      Top-level graph.  Carries the full task list, current position in
      that list, loaded document context, and run-level bookkeeping.
      Lives for the entire duration of the codegen run.

  TaskState
      Subgraph scope.  One instance per task execution.  Carries the
      current task, the developer's output, individual reviewer verdicts,
      the aggregated pass/fail, and retry tracking.
      Created fresh at the start of each task; results are written back
      into OrchestratorState by the orchestrator after the subgraph
      returns.

Supporting dataclasses
----------------------
  TaskRecord      â€” serializable mirror of the Task ORM model
  GeneratedFile   â€” one file written to the workspace by the developer
  ReviewerVerdict â€” one reviewer's pass/fail + feedback

Serialization note
------------------
All types used in state must be JSON-serializable â€” the SQLite checkpointer
stores state as JSON.  ORM objects (Task, Run, â€¦) are never placed directly
in state; nodes translate at the ORM boundary.

Reducer note
------------
Fields written by concurrent nodes (reviewer_verdicts during parallel fan-out)
use Annotated[list, operator.add] so each branch appends rather than
overwrites.  All other fields are last-write-wins (LangGraph default).
"""

from __future__ import annotations

import operator
from dataclasses import dataclass, field
from typing import Annotated, Optional
from typing_extensions import TypedDict

from app.workflows.models import TaskStatus


# ---------------------------------------------------------------------------
# Supporting dataclasses
# ---------------------------------------------------------------------------

@dataclass
class TaskRecord:
    """
    Serializable representation of a Task ORM row.

    Flows through OrchestratorState.tasks and into TaskState.task.
    Nodes that need to mutate task state (mark in_progress, increment
    retry_count, append generated_files) do so on the ORM object via the
    DB session â€” then write an updated TaskRecord back into state so the
    checkpointer sees the latest values.

    Fields
    ------
    id              : UUID string (matches Task.id)
    run_id          : parent run UUID
    title           : short label
    description     : full prose â€” injected into the developer prompt
    order_index     : position in the task list (orchestrator sorts by this)
    pattern_refs    : list of pattern tags e.g. ["Reflection", "Tool-Use"]
                      drives subgraph composition in subgraph.py
    status          : "pending" | "in_progress" | "completed" | "failed"
    retry_count     : how many developerâ†’reviewer loops have run so far
    generated_files : relative workspace paths written by the developer
    feedback        : aggregated reviewer feedback injected on retry
    error           : set when status â†’ "failed"
    """
    id:              str
    title:           str
    order_index:     int
    run_id:          str             = ""
    description:     str             = ""
    pattern_refs:    list[str]       = field(default_factory=list)
    status:          str             = "pending"
    retry_count:     int             = 0
    generated_files: list[str]       = field(default_factory=list)
    feedback:        Optional[str]   = None
    error:           Optional[str]   = None

    @classmethod
    def from_orm(cls, task) -> "TaskRecord":
        """
        Construct a TaskRecord from a Task ORM instance.
        Called at the start of the orchestrator loop when the task list
        is loaded from the DB.
        """
        return cls(
            id              = task.id,
            run_id          = task.run_id,
            title           = task.title,
            order_index     = task.order_index,
            description     = task.description or "",
            pattern_refs    = task.pattern_refs or [],
            status          = task.status,
            retry_count     = task.retry_count,
            generated_files = task.generated_files or [],
            feedback        = task.feedback,
            error           = task.error,
        )

    def to_dict(self) -> dict:
        """Serialize to a plain dict for JSON checkpointing."""
        return {
            "id":              self.id,
            "run_id":          self.run_id,
            "title":           self.title,
            "order_index":     self.order_index,
            "description":     self.description,
            "pattern_refs":    self.pattern_refs,
            "status":          self.status,
            "retry_count":     self.retry_count,
            "generated_files": self.generated_files,
            "feedback":        self.feedback,
            "error":           self.error,
        }

    @classmethod
    def from_dict(cls, d: dict) -> "TaskRecord":
        """Deserialize from a plain dict (checkpointer round-trip)."""
        return cls(**d)


@dataclass
class GeneratedFile:
    """
    One file written to the workspace by the developer agent.

    relative_path
        Path relative to the run's workspace root,
        e.g. "src/agents/planner.py" or "tests/test_planner.py".
        This is what goes into MANIFEST.json and task.generated_files.

    content
        Full file content as a string.  Written to disk by the developer
        node via FileStore.save_workspace_file().

    task_id
        Which task produced this file â€” used when building MANIFEST.json
        so each entry maps task_id â†’ [relative_paths].
    """
    relative_path: str
    content:       str
    task_id:       str

    def to_dict(self) -> dict:
        return {
            "relative_path": self.relative_path,
            "content":       self.content,
            "task_id":       self.task_id,
        }

    @classmethod
    def from_dict(cls, d: dict) -> "GeneratedFile":
        return cls(**d)


@dataclass
class ReviewerVerdict:
    """
    One reviewer's assessment of the developer's output.

    reviewer
        Identifier for the reviewer agent:
        "workflow_reviewer" | "prompt_reviewer" | "security_reviewer"

    passed
        True  â†’ this reviewer is satisfied with the output.
        False â†’ developer must iterate.

    feedback
        Required when passed=False.  Injected into the developer prompt
        on the next retry.  May be empty string when passed=True.

    severity
        "blocking" â†’ counts against pass/fail
        "advisory" â†’ logged but does not force a retry
        Defaults to "blocking" â€” reviewers should explicitly downgrade
        nits to advisory.
    """
    reviewer: str
    passed:   bool
    feedback: str       = ""
    severity: str       = "blocking"   # "blocking" | "advisory"
    attempt:  int       = 0

    def to_dict(self) -> dict:
        return {
            "reviewer": self.reviewer,
            "passed":   self.passed,
            "feedback": self.feedback,
            "severity": self.severity,
            "attempt":  self.attempt,
        }

    @classmethod
    def from_dict(cls, d: dict) -> "ReviewerVerdict":
        return cls(**d)


# ---------------------------------------------------------------------------
# OrchestratorState
# ---------------------------------------------------------------------------

class OrchestratorState(TypedDict, total=False):
    """
    Top-level state for the codegen orchestrator graph.

    Lifecycle
    ---------
    1. Populated by the `load_context` node at graph entry:
       tasks, requirements_context, architecture_context.
    2. The `pick_next_task` node advances current_task_index each iteration.
    3. After each subgraph returns, `record_task_result` appends to
       completed_task_ids or failed_task_ids and updates the TaskRecord
       in tasks[current_task_index].
    4. After the loop, `bundle_workspace` sets bundle_path and manifest.
    5. `request_approval` sets hitl_request_id and pauses the graph.

    Serialization
    -------------
    tasks is stored as list[dict] (TaskRecord.to_dict()) â€” LangGraph's
    checkpointer cannot serialize dataclass instances directly.
    Nodes call TaskRecord.from_dict(t) when they need to work with a task.

    Fields
    ------
    run_id               : current codegen run UUID
    project_id           : parent project UUID
    architecture_run_id  : run_id of the architecture workflow we're executing
    tasks                : full ordered task list as list[dict]
    current_task_index   : index into tasks[] of the task being processed
    max_retries          : per-task reviewer retry cap (from TriggerCodegenRequest)
    requirements_context : full text of the requirements document
    architecture_context : full text of the architecture spec
    completed_task_ids   : task IDs that reached "completed"
    failed_task_ids      : task IDs that exhausted retries and were marked "failed"
    bundle_path          : absolute path to bundle.zip after bundling
    manifest             : MANIFEST.json content as a dict
    hitl_request_id      : UUID of the pending approval HITL request
    error                : top-level run error (set on unrecoverable failure)
    """

    # -- Run identity ---------------------------------------------------------
    run_id:              str
    project_id:          str
    architecture_run_id: str

    # -- Task list ------------------------------------------------------------
    # Stored as list[dict] for checkpointer compatibility.
    # Use TaskRecord.from_dict(t) / TaskRecord.to_dict() at node boundaries.
    tasks:               list[dict]

    # -- Orchestrator cursor --------------------------------------------------
    current_task_index:  int
    max_retries:         int

    # -- Document context loaded once at graph entry --------------------------
    requirements_context: str
    architecture_context: str

    # -- Progress tracking ----------------------------------------------------
    # Annotated with operator.add so that multiple nodes can safely
    # append without overwriting each other (though in practice only
    # record_task_result writes here â€” the annotation is defensive).
    completed_task_ids: list[str]
    failed_task_ids:    list[str]

    # -- Bundle output --------------------------------------------------------
    bundle_path: Optional[str]
    manifest:    Optional[dict]

    # -- HITL gate ------------------------------------------------------------
    hitl_request_id: Optional[str]
    approval_decision: Optional[str]
    approval_feedback: Optional[str]

    # -- Error -----------------------------------------------------------------
    error: Optional[str]
    _last_task_result: Optional[dict]


# ---------------------------------------------------------------------------
# TaskState
# ---------------------------------------------------------------------------

class TaskState(TypedDict, total=False):
    """
    Subgraph state for a single task execution.

    Lifecycle
    ---------
    1. Initialized by the orchestrator before invoking the subgraph â€”
       run_id, project_id, task (as dict), context strings, max_retries
       are passed in as the initial state.
    2. `developer_node` writes developer_output and pending_files.
    3. If pattern_refs includes "Reflection", `critic_node` writes
       critic_feedback; the router sends back to developer_node.
    4. Three reviewer nodes run in parallel, each appending one
       ReviewerVerdict dict to reviewer_verdicts.
    5. `reduce_verdicts` collapses reviewer_verdicts â†’ review_passed +
       aggregated_feedback.
    6. If review_passed=False and retry_count < max_retries, the router
       sends back to developer_node with aggregated_feedback in state.
    7. On success or retry exhaustion, `finalize_task` writes the files
       to disk via FileStore and sets final_status + generated_files.

    Serialization
    -------------
    task, pending_files, and reviewer_verdicts are all stored as
    list[dict] / dict for checkpointer compatibility.

    Fields
    ------
    run_id               : inherited from OrchestratorState
    project_id           : inherited from OrchestratorState
    task                 : current TaskRecord as dict
    requirements_context : inherited from OrchestratorState
    architecture_context : inherited from OrchestratorState
    max_retries          : inherited from OrchestratorState
    developer_output     : raw LLM response from the developer agent
    pending_files        : list[dict] (GeneratedFile.to_dict()) staged
                           by the developer, written to disk on success
    critic_feedback      : feedback from the critic node (Reflection pattern)
    reviewer_verdicts    : list[dict] (ReviewerVerdict.to_dict())
                           REDUCER: operator.add â€” parallel branches append
    review_passed        : True if all blocking reviewers passed
    aggregated_feedback  : combined feedback string injected on retry
    retry_count          : how many developerâ†’reviewer loops have run
    final_status         : "completed" | "failed" â€” set by finalize_task
    generated_files      : relative paths successfully written to disk
    error                : node-level error message
    """

    # -- Identity (inherited from orchestrator) -------------------------------
    run_id:     str
    project_id: str

    # -- Current task ---------------------------------------------------------
    # Stored as dict for checkpointer compatibility.
    # Use TaskRecord.from_dict(state["task"]) inside nodes.
    task: dict

    # -- Context (inherited from orchestrator) --------------------------------
    requirements_context: str
    architecture_context: str
    max_retries:          int

    # -- Developer output -----------------------------------------------------
    developer_output: Optional[str]

    # Staged files: list[dict] (GeneratedFile.to_dict())
    # Written to disk by finalize_task only on successful review.
    # Staged separately so a failed review doesn't leave partial files.
    pending_files: list[dict]

    # -- Critic (Reflection pattern only) -------------------------------------
    critic_feedback: Optional[str]

    # -- Reviewer verdicts (parallel fan-out) ---------------------------------
    # IMPORTANT: operator.add reducer â€” each of the three reviewer nodes
    # appends one dict; reduce_verdicts reads the full list.
    reviewer_verdicts: Annotated[list[dict], operator.add]

    # -- Aggregated review result ---------------------------------------------
    review_passed:       bool
    aggregated_feedback: Optional[str]

    # -- Retry tracking -------------------------------------------------------
    retry_count: int

    # -- Final output ---------------------------------------------------------
    final_status:    Optional[str]    # "completed" | "failed"
    generated_files: list[str]        # relative paths confirmed written to disk

    # -- Error ----------------------------------------------------------------
    error: Optional[str]
    _last_task_result: Optional[dict]


# ---------------------------------------------------------------------------
# Routing constants
# ---------------------------------------------------------------------------

class OrchestratorRoute:
    """
    String constants for orchestrator graph edges.
    Using a class of constants (rather than raw strings) means a typo
    becomes an AttributeError at import time rather than a silent wrong-
    branch at runtime.
    """
    EXECUTE_TASK  = "execute_task"    # â†’ run the subgraph for current task
    NEXT_TASK     = "next_task"       # â†’ advance index and loop
    BUNDLE        = "bundle"          # â†’ all tasks done, build bundle
    FAIL          = "fail"            # â†’ unrecoverable error, abort run
    APPROVE       = "request_approval"# â†’ push approval_request over HITL


class TaskRoute:
    """String constants for task subgraph edges."""
    TO_CRITIC     = "to_critic"       # developer â†’ critic (Reflection)
    TO_REVIEWERS  = "to_reviewers"    # developer/critic â†’ reviewer fan-out
    RETRY         = "retry"           # reduce_verdicts â†’ developer (retry)
    FINALIZE      = "finalize"        # reduce_verdicts â†’ finalize_task (pass)
    FAIL          = "fail"            # retry cap hit â†’ finalize as failed



