# Code Generated by Sidekick is for learning and experimentation purposes only.
"""
Diagnostic script — checks all runs for a given project.
Run from project root: python check_runs.py
"""
import asyncio
from sqlalchemy import select, text

PROJECT_ID = "b774809e-47c5-42fc-8e95-c23935c3631d"

async def check():
    # init_db imports ALL models — resolves all SQLAlchemy relationship chains
    from app.storage.database import init_db, AsyncSessionLocal
    await init_db()

    async with AsyncSessionLocal() as db:

        # ── 1. Raw SQL — no ORM mapper involved, always works ──────────────
        print("=" * 60)
        print("RAW SQL — runs table")
        print("=" * 60)
        result = await db.execute(
            text("""
                SELECT
                    id,
                    workflow_type,
                    status,
                    started_at,
                    finished_at,
                    error
                FROM runs
                WHERE project_id = :pid
                ORDER BY created_at DESC
            """),
            {"pid": PROJECT_ID},
        )
        rows = result.fetchall()
        print(f"Total runs found: {len(rows)}\n")

        for row in rows:
            print(f"  run_id      : {row.id}")
            print(f"  workflow    : {row.workflow_type}")
            print(f"  status      : {row.status}")
            print(f"  started_at  : {row.started_at}")
            print(f"  finished_at : {row.finished_at}")
            print(f"  error       : {row.error}")
            print()

        # ── 2. Summary ──────────────────────────────────────────────────────
        print("=" * 60)
        print("STATUS SUMMARY")
        print("=" * 60)
        summary = await db.execute(
            text("""
                SELECT status, COUNT(*) as cnt
                FROM runs
                WHERE project_id = :pid
                GROUP BY status
            """),
            {"pid": PROJECT_ID},
        )
        for s in summary.fetchall():
            print(f"  {s.status:<25} : {s.cnt} run(s)")

        print()

        # ── 3. Flag any completed requirements run ──────────────────────────
        completed = await db.execute(
            text("""
                SELECT id FROM runs
                WHERE project_id = :pid
                  AND workflow_type = 'requirements'
                  AND status = 'completed'
                LIMIT 1
            """),
            {"pid": PROJECT_ID},
        )
        row = completed.fetchone()
        print("=" * 60)
        if row:
            print(f"✅ READY TO PLAN — use this requirements_run_id:")
            print(f"   {row.id}")
        else:
            print("❌ NO completed requirements run found.")
            print("   → Trigger Workflow 1 first:")
            print("   POST /projects/{project_id}/workflows/requirements")
        print("=" * 60)

asyncio.run(check())
