# Code Generated by Sidekick is for learning and experimentation purposes only.
import os, re, sys

ROOT = os.path.dirname(os.path.abspath(__file__))

def find_in_files(pattern):
    matches = []
    for dirpath, _, files in os.walk(ROOT):
        if any(skip in dirpath for skip in ['__pycache__', '.git', 'venv', 'node_modules']):
            continue
        for f in files:
            if not f.endswith('.py'):
                continue
            full = os.path.join(dirpath, f)
            try:
                content = open(full, encoding='utf-8').read()
                for i, line in enumerate(content.splitlines(), 1):
                    if re.search(pattern, line):
                        matches.append((full, i, line.strip()))
            except Exception:
                pass
    return matches

# ── Step 1: Find where check_project_membership is DEFINED ──────────────────
print("=" * 60)
print("STEP 1: Locating check_project_membership definition")
print("=" * 60)
defs = find_in_files(r'def check_project_membership')
if defs:
    for path, lineno, line in defs:
        rel = os.path.relpath(path, ROOT)
        print(f"  FOUND  → {rel}  (line {lineno})")
        # Convert file path to import string
        module_path = rel.replace(os.sep, '.').replace('.py', '')
        print(f"  IMPORT → from {module_path} import check_project_membership")
else:
    print("  NOT FOUND anywhere. Will need to inline the logic.")

# ── Step 2: Find the codegen router file ────────────────────────────────────
print()
print("=" * 60)
print("STEP 2: Locating codegen router file")
print("=" * 60)
codegen_files = find_in_files(r'app\.projects\.dependencies')
if codegen_files:
    for path, lineno, line in codegen_files:
        rel = os.path.relpath(path, ROOT)
        print(f"  BROKEN IMPORT in → {rel}  (line {lineno}): {line}")
else:
    print("  Broken import not found (may already be fixed or file missing)")

# ── Step 3: Auto-patch ───────────────────────────────────────────────────────
print()
print("=" * 60)
print("STEP 3: Patching")
print("=" * 60)

if defs and codegen_files:
    correct_module = os.path.relpath(defs[0][0], ROOT).replace(os.sep, '.').replace('.py', '')
    correct_import = f"from {correct_module} import check_project_membership"

    for path, lineno, _ in codegen_files:
        content = open(path, encoding='utf-8').read()
        patched = re.sub(
            r'from app\.projects\.dependencies import check_project_membership',
            correct_import,
            content
        )
        open(path, 'w', encoding='utf-8').write(patched)
        print(f"  PATCHED → {os.path.relpath(path, ROOT)}")
        print(f"  NEW IMPORT: {correct_import}")
elif not defs:
    print("  Cannot auto-patch: check_project_membership not found anywhere.")
    print("  Will inline equivalent logic into codegen router instead.")
    # Inline fallback — replace the import with a local lambda/inline
    for path, lineno, _ in (codegen_files or []):
        content = open(path, encoding='utf-8').read()
        inline = (
            "# check_project_membership inlined (app.projects.dependencies not found)\n"
            "async def check_project_membership(project, user, db):\n"
            "    from fastapi import HTTPException\n"
            "    if project.owner_id != user.id:\n"
            "        raise HTTPException(status_code=403, detail='Access denied.')\n"
        )
        patched = content.replace(
            "from fix_cogen import check_project_membership",
            inline
        )
        open(path, 'w', encoding='utf-8').write(patched)
        print(f"  INLINED fallback into {os.path.relpath(path, ROOT)}")

# ── Step 4: Verify ───────────────────────────────────────────────────────────
print()
print("=" * 60)
print("STEP 4: Verifying app routes post-patch")
print("=" * 60)
try:
    # Force fresh import
    mods_to_remove = [k for k in sys.modules if 'app' in k]
    for m in mods_to_remove:
        del sys.modules[m]

    from app.main import app
    codegen_routes = [r for r in app.routes if hasattr(r, 'path') and 'codegen' in r.path]
    print(f"  Codegen routes found: {len(codegen_routes)}")
    for r in codegen_routes:
        print(f"    {getattr(r, 'methods', 'WS')}  {r.path}")
    if not codegen_routes:
        print("  Still 0 — check that main.py calls include_router for codegen (see below)")
        # Show include_router calls in main.py
        main_path = os.path.join(ROOT, 'app', 'main.py')
        if os.path.exists(main_path):
            for i, line in enumerate(open(main_path).readlines(), 1):
                if 'include_router' in line:
                    print(f"    main.py line {i}: {line.rstrip()}")
except Exception as e:
    import traceback
    print(f"  Import still failing: {e}")
    traceback.print_exc()
