# Code Generated by Sidekick is for learning and experimentation purposes only.
from pydantic import BaseModel, Field


class TriggerCodegenRequest(BaseModel):
    planning_run_id: str = Field(..., description="Approved planning run id")
    idempotency_key: str | None = Field(default=None)


class TriggerCodegenResponse(BaseModel):
    run_id: str
    project_id: str
    status: str
    message: str | None = None
