#in milestone-1
# from app.storage.database import Base

# # Stub — full Pattern model comes in Milestone 2
# class Pattern(Base):
#     __tablename__ = "patterns"
#     __table_args__ = {"extend_existing": True}
#     from sqlalchemy import String
#     from sqlalchemy.orm import Mapped, mapped_column
#     id: Mapped[str] = mapped_column(String, primary_key=True)









#in milestone-2

# Code Generated by Sidekick is for learning and experimentation purposes only.

import uuid
import json
from datetime import datetime, timezone

from sqlalchemy import Column, String, Text, DateTime
from sqlalchemy.orm import declarative_base

from app.storage.database import Base  # reuse M1's Base


class Pattern(Base):
    __tablename__ = "patterns"

    id = Column(String, primary_key=True, default=lambda: str(uuid.uuid4()))

    name         = Column(String(120), nullable=False, unique=True, index=True)
    intent       = Column(Text, nullable=False)           # one-paragraph problem statement
    structure    = Column(Text, nullable=False)           # agents/components + interactions
    when_to_use  = Column(Text, nullable=False)           # concrete fit signals
    when_not_to_use = Column(Text, nullable=False)        # anti-patterns / failure modes
    prerequisites   = Column(Text, nullable=False)        # tools, memory, evaluators needed
    references      = Column(Text, nullable=True)         # links / citations (free text)
    _tags           = Column("tags", Text, nullable=False, default="[]")  # JSON-serialised list
    source          = Column(String(80), nullable=False, default="user")  # "seed" | "user"

    created_at = Column(DateTime, default=lambda: datetime.now(timezone.utc), nullable=False)
    updated_at = Column(
        DateTime,
        default=lambda: datetime.now(timezone.utc),
        onupdate=lambda: datetime.now(timezone.utc),
        nullable=False,
    )

    # ── helpers so callers never touch raw JSON ──────────────────────────────
    @property
    def tags(self) -> list[str]:
        try:
            return json.loads(self._tags)
        except Exception:
            return []

    @tags.setter
    def tags(self, value: list[str]) -> None:
        self._tags = json.dumps(value)
