# #milestone-1
# from fastapi import APIRouter

# # Empty router - full code will be added in Milestone 2
# router = APIRouter(prefix="/patterns", tags=["Patterns"])






# Code Generated by Sidekick is for learning and experimentation purposes only.

import json
import yaml

from fastapi import APIRouter, Depends, HTTPException, Query, UploadFile, File, status
from sqlalchemy.ext.asyncio import AsyncSession

from app.storage.database import get_db
from app.auth.dependencies import get_current_user   # reuse M1 JWT dependency
from app.patterns import service as pattern_service
from app.patterns.schemas import (
    PatternCreate, PatternUpdate, PatternResponse,
    PatternListResponse, PatternSearchRequest, PatternSearchResponse,
)

router = APIRouter(prefix="/patterns", tags=["Patterns"])


# ── CREATE (single) ───────────────────────────────────────────────────────────

@router.post(
    "",
    response_model=PatternResponse,
    status_code=status.HTTP_201_CREATED,
    summary="Create a single agentic design pattern",
)
async def create_pattern(
    body: PatternCreate,
    db: AsyncSession = Depends(get_db),
    _user=Depends(get_current_user),
):
    existing = await pattern_service.get_pattern_by_name(db, body.name)
    if existing:
        raise HTTPException(
            status_code=status.HTTP_409_CONFLICT,
            detail={"code": "PATTERN_EXISTS", "message": f"Pattern '{body.name}' already exists."},
        )
    pattern = await pattern_service.create_pattern(db, body)
    return PatternResponse.from_orm_model(pattern)


# ── CREATE (bulk) ─────────────────────────────────────────────────────────────

@router.post(
    "/bulk",
    response_model=dict,
    status_code=status.HTTP_201_CREATED,
    summary="Bulk-create patterns from a JSON array or YAML file upload",
)
async def create_patterns_bulk(
    file: UploadFile | None = File(default=None),
    db: AsyncSession = Depends(get_db),
    _user=Depends(get_current_user),
):
    """
    Accepts either:
    - A YAML file upload (Content-Type: multipart/form-data)
    - A raw JSON body array  (handled via the single POST for each item)

    YAML file format:
    ```yaml
    - name: MyPattern
      intent: ...
      ...
    ```
    """
    if file is None:
        raise HTTPException(
            status_code=status.HTTP_422_UNPROCESSABLE_ENTITY,
            detail={"code": "NO_FILE", "message": "Upload a YAML or JSON file."},
        )

    content = await file.read()
    try:
        if file.filename and file.filename.endswith((".yaml", ".yml")):
            entries = yaml.safe_load(content)
        else:
            entries = json.loads(content)
    except Exception as exc:
        raise HTTPException(
            status_code=status.HTTP_422_UNPROCESSABLE_ENTITY,
            detail={"code": "PARSE_ERROR", "message": str(exc)},
        )

    if not isinstance(entries, list):
        raise HTTPException(
            status_code=status.HTTP_422_UNPROCESSABLE_ENTITY,
            detail={"code": "INVALID_FORMAT", "message": "Root element must be a list/array."},
        )

    created, skipped, errors = 0, 0, []
    for idx, entry in enumerate(entries):
        try:
            data = PatternCreate(**entry)
        except Exception as exc:
            errors.append({"index": idx, "error": str(exc)})
            continue

        existing = await pattern_service.get_pattern_by_name(db, data.name)
        if existing:
            skipped += 1
            continue

        await pattern_service.create_pattern(db, data)
        created += 1

    return {"created": created, "skipped": skipped, "errors": errors}


# ── LIST ──────────────────────────────────────────────────────────────────────

@router.get(
    "",
    response_model=PatternListResponse,
    summary="List all patterns with optional tag filtering",
)
async def list_patterns(
    tags: list[str] = Query(default=[]),
    offset: int = Query(default=0, ge=0),
    limit: int  = Query(default=50, ge=1, le=100),
    db: AsyncSession = Depends(get_db),
    _user=Depends(get_current_user),
):
    patterns, total = await pattern_service.list_patterns(db, tags or None, offset, limit)
    return PatternListResponse(
        items=[PatternResponse.from_orm_model(p) for p in patterns],
        total=total,
    )


# ── GET (single) ──────────────────────────────────────────────────────────────

@router.get(
    "/{pattern_id}",
    response_model=PatternResponse,
    summary="Get a single pattern by ID",
)
async def get_pattern(
    pattern_id: str,
    db: AsyncSession = Depends(get_db),
    _user=Depends(get_current_user),
):
    pattern = await pattern_service.get_pattern_by_id(db, pattern_id)
    if not pattern:
        raise HTTPException(
            status_code=status.HTTP_404_NOT_FOUND,
            detail={"code": "NOT_FOUND", "message": "Pattern not found."},
        )
    return PatternResponse.from_orm_model(pattern)


# ── PATCH ─────────────────────────────────────────────────────────────────────

@router.patch(
    "/{pattern_id}",
    response_model=PatternResponse,
    summary="Partially update a pattern",
)
async def update_pattern(
    pattern_id: str,
    body: PatternUpdate,
    db: AsyncSession = Depends(get_db),
    _user=Depends(get_current_user),
):
    pattern = await pattern_service.get_pattern_by_id(db, pattern_id)
    if not pattern:
        raise HTTPException(
            status_code=status.HTTP_404_NOT_FOUND,
            detail={"code": "NOT_FOUND", "message": "Pattern not found."},
        )

    # prevent rename collision
    if body.name and body.name != pattern.name:
        clash = await pattern_service.get_pattern_by_name(db, body.name)
        if clash:
            raise HTTPException(
                status_code=status.HTTP_409_CONFLICT,
                detail={"code": "PATTERN_EXISTS", "message": f"Pattern '{body.name}' already exists."},
            )

    updated = await pattern_service.update_pattern(db, pattern, body)
    return PatternResponse.from_orm_model(updated)


# ── DELETE ────────────────────────────────────────────────────────────────────

@router.delete(
    "/{pattern_id}",
    status_code=status.HTTP_204_NO_CONTENT,
    summary="Delete a pattern (removes from DB and ChromaDB)",
)
async def delete_pattern(
    pattern_id: str,
    db: AsyncSession = Depends(get_db),
    _user=Depends(get_current_user),
):
    pattern = await pattern_service.get_pattern_by_id(db, pattern_id)
    if not pattern:
        raise HTTPException(
            status_code=status.HTTP_404_NOT_FOUND,
            detail={"code": "NOT_FOUND", "message": "Pattern not found."},
        )
    await pattern_service.delete_pattern(db, pattern)


# ── SEMANTIC SEARCH ───────────────────────────────────────────────────────────

@router.post(
    "/search",
    response_model=PatternSearchResponse,
    summary="Semantic search over the pattern KB (used internally by Planning workflow)",
)
async def search_patterns(
    body: PatternSearchRequest,
    db: AsyncSession = Depends(get_db),
    _user=Depends(get_current_user),
):
    return await pattern_service.search_patterns(
        db,
        query=body.query,
        tags=body.tags,
        top_k=body.top_k,
    )
