# import json
# from pydantic_settings import BaseSettings
# from pydantic import Field
# from functools import lru_cache


# class Settings(BaseSettings):
#     ARTIFACTS_ROOT: str = "./data/artifacts"
#     CHECKPOINTS_DIR: str = "./data/checkpoints"
#     CHROMADB_PATH: str = "./data/chromadb"
#     UPLOADS_DIR: str = "./data/uploads"
#     DATA_ROOT: str = "./data"
#     """
#     All application configuration loaded from environment variables.
#     Uses pydantic-settings so values can come from .env file or real env vars.
#     """

#     # OpenAI
#     openai_api_key: str = Field(..., env="OPENAI_API_KEY")

#     # JWT
#     jwt_secret: str = Field(..., env="JWT_SECRET")
#     jwt_algorithm: str = Field("HS256", env="JWT_ALGORITHM")
#     jwt_expire_minutes: int = Field(1440, env="JWT_EXPIRE_MINUTES")

#     # Database paths
#     sqlite_db_path: str = Field("./data/app.sqlite", env="SQLITE_DB_PATH")
#     checkpoint_db_path: str = Field("./data/checkpoints.sqlite", env="CHECKPOINT_DB_PATH")

#     # ChromaDB
#     chroma_persist_dir: str = Field("./data/chroma", env="CHROMA_PERSIST_DIR")

#     # File storage root
#     data_root: str = Field("./data/projects", env="DATA_ROOT")

#     # App
#     app_env: str = Field("development", env="APP_ENV")
#     log_level: str = Field("INFO", env="LOG_LEVEL")

#     # Cost / token ceilings per run
#     max_tokens_per_run: int = Field(200000, env="MAX_TOKENS_PER_RUN")
#     max_cost_usd_per_run: float = Field(5.00, env="MAX_COST_USD_PER_RUN")

#     # Workflow iteration limits
#     max_clarification_rounds: int = Field(3, env="MAX_CLARIFICATION_ROUNDS")
#     max_critic_iterations: int = Field(3, env="MAX_CRITIC_ITERATIONS")
#     max_reviewer_retries: int = Field(3, env="MAX_REVIEWER_RETRIES")

#     # Default LLM model
#     default_model: str = Field("gpt-4o", env="DEFAULT_MODEL")

#     # Model pricing as a JSON string, parsed into a dict
#     model_pricing_raw: str = Field(
#         '{"gpt-4o":{"input":0.005,"output":0.015}}',
#         env="MODEL_PRICING"
#     )

#     @property
#     def model_pricing(self) -> dict:
#         """Parse the JSON pricing string into a usable dict."""
#         return json.loads(self.model_pricing_raw)

#     class Config:
#         env_file = ".env"
#         env_file_encoding = "utf-8"
#         extra = "ignore"  # ignore unknown env vars


# @lru_cache()
# def get_settings() -> Settings:
#     """
#     Returns a cached singleton of Settings.
#     Using lru_cache means we only parse env vars once per process.
#     """
#     return Settings()


# # Module-level singleton so callers can do:
# # from app.config import settings
# settings = get_settings()
















# Code Generated by Sidekick is for learning and experimentation purposes only.

import json
from pydantic_settings import BaseSettings
from pydantic import Field
from functools import lru_cache


class Settings(BaseSettings):
    """
    All application configuration loaded from environment variables.
    Uses pydantic-settings so values can come from .env file or real env vars.

    IMPORTANT: All fields are UPPERCASE so they can be accessed consistently
    as settings.FIELD_NAME throughout the codebase.
    """

    # ── Gemini / Google GenAI ─────────────────────────────────────────────
    GEMINI_API_KEY: str = Field("dev-gemini-key-not-set", env="GEMINI_API_KEY")
    GOOGLE_API_KEY: str = Field("dev-gemini-key-not-set", env="GOOGLE_API_KEY")
    OPENAI_API_KEY: str = Field("dev-openai-key-not-set", env="OPENAI_API_KEY")

    # ── JWT ───────────────────────────────────────────────────────────────
    JWT_SECRET: str = Field("dev-jwt-secret-change-me", env="JWT_SECRET")
    JWT_ALGORITHM: str = Field("HS256", env="JWT_ALGORITHM")
    JWT_EXPIRE_MINUTES: int = Field(1440, env="JWT_EXPIRE_MINUTES")

    # ── Database paths ────────────────────────────────────────────────────
    SQLITE_DB_PATH: str = Field("./data/app.sqlite", env="SQLITE_DB_PATH")

    # FIX-1: was checkpoint_db_path (lowercase) — graph.py calls CHECKPOINT_DB_PATH
    CHECKPOINT_DB_PATH: str = Field("./data/checkpoints.sqlite", env="CHECKPOINT_DB_PATH")

    # ── ChromaDB ──────────────────────────────────────────────────────────
    CHROMA_PERSIST_DIR: str = Field("./data/chromadb", env="CHROMA_PERSIST_DIR")

    # ── File storage ──────────────────────────────────────────────────────
    # FIX-2: Removed conflicting class-level DATA_ROOT = "./data/artifacts"
    #         Single source of truth — nodes.py, file_store.py, graph.py all
    #         call settings.DATA_ROOT and expect "./data/projects"
    DATA_ROOT: str = Field("./data/projects", env="DATA_ROOT")

    # ── App ───────────────────────────────────────────────────────────────
    APP_ENV: str = Field("development", env="APP_ENV")
    LOG_LEVEL: str = Field("INFO", env="LOG_LEVEL")

    # ── Cost / token ceilings per run ─────────────────────────────────────
    MAX_TOKENS_PER_RUN: int = Field(200000, env="MAX_TOKENS_PER_RUN")
    MAX_COST_USD_PER_RUN: float = Field(5.00, env="MAX_COST_USD_PER_RUN")

    # ── Workflow iteration limits ─────────────────────────────────────────
    # FIX-3: was max_clarification_rounds — nodes.py calls MAX_CLARIFICATION_ROUNDS
    MAX_CLARIFICATION_ROUNDS: int = Field(3, env="MAX_CLARIFICATION_ROUNDS")

    # FIX-4: was max_critic_iterations — standardised to uppercase
    MAX_CRITIC_ITERATIONS: int = Field(3, env="MAX_CRITIC_ITERATIONS")

    MAX_REVIEWER_RETRIES: int = Field(3, env="MAX_REVIEWER_RETRIES")

    # FIX-5: MISSING FIELD — nodes.py calls settings.MAX_REFLECTION_ITERATIONS
    #         but this field did not exist at all — caused AttributeError in
    #         reflect_and_find_gaps node, silently killing the workflow
    MAX_REFLECTION_ITERATIONS: int = Field(3, env="MAX_REFLECTION_ITERATIONS")

    # ── Default LLM model ─────────────────────────────────────────────────
    DEFAULT_MODEL: str = Field("gemini-2.5-flash", env="DEFAULT_MODEL")

    # ── Model pricing ─────────────────────────────────────────────────────
    MODEL_PRICING_RAW: str = Field(
        '{"gemini-2.5-flash":{"input":0.00015,"output":0.0006},"gemini-1.5-flash":{"input":0.000075,"output":0.0003},"gemini-2.5-pro":{"input":0.00125,"output":0.005},"gemini-1.5-pro":{"input":0.00125,"output":0.005},"gpt-4o":{"input":0.005,"output":0.015}}',
        env="MODEL_PRICING"
    )

    @property
    def MODEL_PRICING(self) -> dict:
        """Parse the JSON pricing string into a usable dict."""
        return json.loads(self.MODEL_PRICING_RAW)

    class Config:
        env_file = ".env"
        env_file_encoding = "utf-8"
        extra = "ignore"   # ignore unknown env vars


@lru_cache()
def get_settings() -> Settings:
    """
    Returns a cached singleton of Settings.
    Using lru_cache means we only parse env vars once per process.
    """
    return Settings()


# Module-level singleton so callers can do:
#   from app.config import settings
settings = get_settings()
