# Code Generated by Sidekick is for learning and experimentation purposes only.
"""
tests/workflows/codegen/conftest.py
-------------------------------------
Shared fixtures for the codegen workflow test suite.

DB Strategy
-----------
In-memory SQLite with a single AsyncEngine per session.
Each test function gets its own transaction via the `db` fixture â€”
the transaction is rolled back on teardown so tests are fully isolated.

The `async_engine` and `async_session_factory` fixtures are session-scoped
(created once per pytest session).  The `db` fixture is function-scoped
(fresh transaction per test).

OpenAI Mock
-----------
`mock_openai` is a function-scoped fixture that patches
`app.workflows.codegen.nodes._oai.chat.completions.create`.
Tests configure the mock's return values per-scenario.

Architecture Run Seed
----------------------
`seeded_arch_run` creates a completed architecture Run with a realistic
output_data["tasks"] list.  Used by subgraph and orchestrator tests.
"""

from __future__ import annotations

import asyncio
import uuid
from datetime import datetime, timezone
from typing import AsyncGenerator
from unittest.mock import AsyncMock, MagicMock, patch

import pytest
import pytest_asyncio
from sqlalchemy.ext.asyncio import AsyncSession, create_async_engine, async_sessionmaker

from app.storage.models import Base, Run
from app.workflows.models import Task, TaskStatus, RunStatus
from app.workflows.codegen.subgraph import clear_subgraph_cache


# ---------------------------------------------------------------------------
# pytest-asyncio configuration
# ---------------------------------------------------------------------------
# Place asyncio_mode = "auto" in pytest.ini or pyproject.toml:
#
#   [tool.pytest.ini_options]
#   asyncio_mode = "auto"
#
# This allows all async test functions and fixtures to run without
# @pytest.mark.asyncio decorators.


# ---------------------------------------------------------------------------
# In-memory DB engine (session-scoped)
# ---------------------------------------------------------------------------

@pytest_asyncio.fixture(scope="session")
async def async_engine():
    """
    Create a single in-memory SQLite AsyncEngine for the test session.
    Schema is created once and shared across all tests.
    """
    engine = create_async_engine(
        "sqlite+aiosqlite:///:memory:",
        echo=False,
    )
    async with engine.begin() as conn:
        await conn.run_sync(Base.metadata.create_all)
    yield engine
    await engine.dispose()


@pytest_asyncio.fixture(scope="session")
def async_session_factory(async_engine):
    """Session-scoped factory â€” shared across all tests in the session."""
    return async_sessionmaker(
        async_engine,
        class_         = AsyncSession,
        expire_on_commit = False,
    )


@pytest_asyncio.fixture
async def db(async_session_factory) -> AsyncGenerator[AsyncSession, None]:
    """
    Function-scoped DB session with transaction rollback on teardown.

    Every test that uses `db` gets a clean slate â€” no data from previous
    tests is visible, and no data written in this test persists.
    """
    async with async_session_factory() as session:
        async with session.begin():
            yield session
            await session.rollback()


# ---------------------------------------------------------------------------
# OpenAI mock
# ---------------------------------------------------------------------------

def _make_chat_response(content: str) -> MagicMock:
    """
    Build a minimal mock object that mimics:
        response.choices[0].message.content
    """
    message  = MagicMock()
    message.content = content
    choice   = MagicMock()
    choice.message = message
    response = MagicMock()
    response.choices = [choice]
    return response


@pytest_asyncio.fixture
def mock_openai():
    """
    Patch _oai.chat.completions.create with an AsyncMock.

    Usage in tests:
        mock_openai.return_value = _make_chat_response("<file ...>...</file>")

    Or for per-call variation:
        mock_openai.side_effect = [resp1, resp2, resp3]
    """
    with patch(
        "app.workflows.codegen.nodes._oai",
        autospec=True,
    ) as mock_client:
        mock_client.chat.completions.create = AsyncMock()
        yield mock_client.chat.completions.create


# ---------------------------------------------------------------------------
# Subgraph cache cleanup
# ---------------------------------------------------------------------------

@pytest_asyncio.fixture(autouse=True)
def reset_subgraph_cache():
    """
    Auto-use fixture that clears the subgraph compilation cache before
    every test.  Prevents cross-test topology pollution.
    """
    clear_subgraph_cache()
    yield
    clear_subgraph_cache()


# ---------------------------------------------------------------------------
# Canonical LLM response factories
# ---------------------------------------------------------------------------

def make_developer_response(
    files: dict[str, str] | None = None,
) -> MagicMock:
    """
    Build a mock developer LLM response with well-formed <file> blocks.

    Parameters
    ----------
    files
        {relative_path: file_content} â€” defaults to a single placeholder file.
    """
    if files is None:
        files = {
            "src/agents/planner.py": (
                "# Code Generated by Sidekick is for learning and experimentation purposes only.\n"
                '"""Planner agent."""\n'
                "from __future__ import annotations\n\n"
                "def plan(task: str) -> list[str]:\n"
                '    """Break task into steps."""\n'
                "    return [task]\n"
            )
        }

    blocks = "\n".join(
        f'<file path="{path}">\n{content}\n</file>'
        for path, content in files.items()
    )
    return _make_chat_response(f"Here are the generated files:\n\n{blocks}")


def make_reviewer_pass_response(reviewer: str = "workflow_reviewer") -> MagicMock:
    """Build a passing reviewer JSON response."""
    return _make_chat_response(
        '{"passed": true, "feedback": "", "severity": "blocking"}'
    )


def make_reviewer_fail_response(
    reviewer: str  = "workflow_reviewer",
    feedback: str  = "Missing orchestrator dispatch logic.",
    severity: str  = "blocking",
) -> MagicMock:
    """Build a failing reviewer JSON response."""
    return _make_chat_response(
        f'{{"passed": false, "feedback": "{feedback}", "severity": "{severity}"}}'
    )


def make_critic_pass_response() -> MagicMock:
    """Build a passing critic JSON response."""
    return _make_chat_response(
        '{"passed": true, "issues": [], "feedback": ""}'
    )


def make_critic_fail_response(feedback: str = "Loop is unbounded.") -> MagicMock:
    """Build a failing critic JSON response."""
    return _make_chat_response(
        f'{{"passed": false, "issues": ["{feedback}"], "feedback": "{feedback}"}}'
    )


# ---------------------------------------------------------------------------
# Architecture run seed fixture
# ---------------------------------------------------------------------------

@pytest_asyncio.fixture
async def seeded_arch_run(db: AsyncSession) -> Run:
    """
    Seed a completed architecture Run with realistic output_data["tasks"].

    Returns the created Run ORM row.

    Task list covers three common pattern combinations so subgraph and
    orchestrator tests have variety without needing to create their own data.
    """
    run = Run(
        id            = str(uuid.uuid4()),
        project_id    = "proj-test-001",
        workflow_type = "architecture",
        status        = RunStatus.COMPLETED,
        input_data    = {},
        output_data   = {
            "tasks": [
                {
                    "title":        "Implement planner agent",
                    "description":  "Build the orchestrator-worker planner node.",
                    "order_index":  0,
                    "pattern_refs": [],
                },
                {
                    "title":        "Implement reflection loop",
                    "description":  "Build the generate-critique-revise loop.",
                    "order_index":  1,
                    "pattern_refs": ["Reflection"],
                },
                {
                    "title":        "Implement tool registry",
                    "description":  "Build the tool-use infrastructure.",
                    "order_index":  2,
                    "pattern_refs": ["Tool-Use"],
                },
            ],
            "requirements": "Build a LangGraph multi-agent system.",
            "architecture":  '{"nodes": ["planner", "executor", "critic"]}',
        },
        run_metadata  = {},
        started_at    = datetime.now(timezone.utc),
        finished_at   = datetime.now(timezone.utc),
    )
    db.add(run)
    await db.flush()
    return run


@pytest_asyncio.fixture
def project_id() -> str:
    return "proj-test-001"


@pytest_asyncio.fixture
def run_id() -> str:
    return str(uuid.uuid4())

@pytest_asyncio.fixture(autouse=True)
def patch_codegen_db_sessions(db: AsyncSession):
    """Route codegen runner/node DB sessions through the in-memory test DB."""
    from contextlib import asynccontextmanager

    @asynccontextmanager
    async def _test_db_session():
        try:
            yield db
            await db.flush()
        except Exception:
            await db.rollback()
            raise

    with patch("app.workflows.codegen.nodes._db_session", _test_db_session), patch(
        "app.workflows.codegen.runner._db_session", _test_db_session
    ):
        yield
