# Code Generated by Sidekick is for learning and experimentation purposes only.
"""
tests/workflows/codegen/test_subgraph.py
------------------------------------------
Integration tests for the per-task subgraph.

Strategy
--------
- Mock OpenAI at _oai.chat.completions.create
- Compile subgraphs for each topology variant
- Invoke with an initial TaskState and assert on final state

Tests cover
-----------
Base topology
    - Happy path: developer â†’ reviewers pass â†’ COMPLETED
    - Retry: reviewers fail once â†’ developer retries â†’ reviewers pass â†’ COMPLETED
    - Exhausted retries: reviewers fail every attempt â†’ FAILED
    - Advisory failure: non-blocking reviewer failure â†’ COMPLETED
    - All three reviewers fail: task FAILED after retries exhausted

Reflection topology
    - Critic passes immediately â†’ proceeds to reviewers
    - Critic fails once â†’ developer revises â†’ critic passes â†’ reviewers pass
    - Critic fails until retry cap hit â†’ FAILED

Tool-Use topology
    - Tool check passes first time â†’ 1 developer call before reviewers
    - Tool check fails first, passes on retry â†’ COMPLETED
    - Tool check fails until retry cap hit â†’ FAILED

Reflection + Tool-Use combined
    - Tool check pass, critic pass, reviewers pass â†’ COMPLETED
    - Tool check fail â†’ fix â†’ critic fail â†’ revise â†’ reviewers pass â†’ COMPLETED

Edge cases
    - Developer parse failure (no <file> blocks) â†’ FAILED
    - Developer LLM call raises exception â†’ FAILED gracefully
    - Reviewer LLM call raises exception â†’ blocking FAILED (not silent pass)
    - Empty pending_files after parse â†’ FAILED

Compilation cache
    - Same patterns return cached instance (identity check)
    - Different patterns return distinct instances
    - Pattern order is irrelevant for cache key
    - cache is cleared by clear_subgraph_cache()
"""

from __future__ import annotations

import uuid
from unittest.mock import AsyncMock, MagicMock, patch

import pytest
import pytest_asyncio

from app.workflows.codegen.state import TaskRecord, TaskStatus
from app.workflows.codegen.subgraph import (
    _SUBGRAPH_CACHE,
    build_task_subgraph,
    clear_subgraph_cache,
    get_cached_patterns,
)
from tests.workflows.codegen.conftest import (
    _make_chat_response,
    make_critic_fail_response,
    make_critic_pass_response,
    make_developer_response,
    make_reviewer_fail_response,
    make_reviewer_pass_response,
)


# ---------------------------------------------------------------------------
# Internal helpers
# ---------------------------------------------------------------------------

def _make_task(
    pattern_refs: list[str] | None = None,
    title: str = "Test Task",
) -> TaskRecord:
    """Construct a minimal TaskRecord for subgraph tests."""
    return TaskRecord(
        id           = str(uuid.uuid4()),
        title        = title,
        description  = "A test task â€” build the thing.",
        order_index  = 0,
        pattern_refs = pattern_refs or [],
        status       = TaskStatus.IN_PROGRESS.value,
    )


def _initial_state(task: TaskRecord, max_retries: int = 3) -> dict:
    """Construct a clean initial TaskState dict for subgraph invocation."""
    return {
        "run_id":               "run-test-001",
        "project_id":           "proj-test-001",
        "task":                 task.to_dict(),
        "requirements_context": "Build a multi-agent LangGraph system.",
        "architecture_context": '{"nodes": ["planner", "executor"]}',
        "max_retries":          max_retries,
        "developer_output":     None,
        "pending_files":        [],
        "critic_feedback":      None,
        "reviewer_verdicts":    [],
        "review_passed":        False,
        "aggregated_feedback":  None,
        "retry_count":          0,
        "final_status":         None,
        "generated_files":      [],
        "error":                None,
    }


# ---------------------------------------------------------------------------
# Shared auto-use fixture: patch file_store to avoid filesystem I/O
# ---------------------------------------------------------------------------

@pytest_asyncio.fixture(autouse=True)
def mock_file_store():
    """
    Patch file_store in nodes.py to avoid real filesystem writes.
    Applied automatically to every test in this module.

    save_workspace_file is an AsyncMock (coroutine).
    list_workspace_files returns an empty list.
    file_exists returns False (no pre-existing artifacts).
    """
    mock = MagicMock()
    mock.list_workspace_files.return_value = []
    mock.save_workspace_file = AsyncMock(return_value=None)
    mock.file_exists.return_value = False

    # Some legacy tests refer to the autouse fixture function directly.
    # Attach the mock methods to that function object for compatibility.
    mock_file_store.list_workspace_files = mock.list_workspace_files
    mock_file_store.save_workspace_file = mock.save_workspace_file
    mock_file_store.file_exists = mock.file_exists

    with patch("app.workflows.codegen.nodes.file_store", mock):
        yield mock


# ===========================================================================
# BASE TOPOLOGY  (no optional patterns)
# ===========================================================================

class TestBaseTopology:
    """
    Tests for tasks with pattern_refs=[] â€” the simplest graph variant:
    developer_node â†’ fan-out reviewers â†’ reduce â†’ finalize
    """

    @pytest.mark.asyncio
    async def test_happy_path_completed(self, mock_openai):
        """
        Developer produces valid output on first attempt.
        All three reviewers pass.
        Task finalises as COMPLETED. File is written to disk.
        """
        task = _make_task(pattern_refs=[])

        mock_openai.side_effect = [
            make_developer_response({"src/planner.py": "def plan(): pass"}),
            make_reviewer_pass_response(),
            make_reviewer_pass_response(),
            make_reviewer_pass_response(),
        ]

        subgraph    = build_task_subgraph(task, max_retries=3)
        final_state = await subgraph.ainvoke(
            _initial_state(task),
            config={"recursion_limit": 50},
        )

        assert final_state["final_status"] == TaskStatus.COMPLETED.value
        assert "src/planner.py" in final_state["generated_files"]
        assert final_state["error"] is None
        mock_file_store.save_workspace_file.assert_called_once()

    @pytest.mark.asyncio
    async def test_retry_on_blocking_reviewer_failure(self, mock_openai):
        """
        One blocking reviewer fails on first attempt.
        Developer retries with aggregated feedback.
        All reviewers pass on second attempt â†’ COMPLETED.
        """
        task = _make_task(pattern_refs=[])

        mock_openai.side_effect = [
            # Attempt 1
            make_developer_response({"src/planner.py": "def plan(): pass"}),
            make_reviewer_fail_response(feedback="Missing dispatch logic."),
            make_reviewer_pass_response(),
            make_reviewer_pass_response(),
            # Attempt 2 (retry)
            make_developer_response({"src/planner.py": "def plan():\n    dispatch()"}),
            make_reviewer_pass_response(),
            make_reviewer_pass_response(),
            make_reviewer_pass_response(),
        ]

        subgraph    = build_task_subgraph(task, max_retries=3)
        final_state = await subgraph.ainvoke(
            _initial_state(task),
            config={"recursion_limit": 50},
        )

        assert final_state["final_status"] == TaskStatus.COMPLETED.value
        assert final_state["retry_count"] == 1
        assert mock_file_store.save_workspace_file.call_count == 1

    @pytest.mark.asyncio
    async def test_all_retries_exhausted_fails(self, mock_openai):
        """
        Reviewers fail on every attempt.
        After max_retries=2 (3 total attempts), task finalises as FAILED.
        No files written to disk.
        """
        task = _make_task(pattern_refs=[])

        # 3 attempts Ã— (1 developer + 1 failing reviewer + 2 passing reviewers)
        mock_openai.side_effect = [
            make_developer_response({"src/bad.py": "BROKEN"}),
            make_reviewer_fail_response(feedback="Broken on attempt 1."),
            make_reviewer_pass_response(),
            make_reviewer_pass_response(),

            make_developer_response({"src/bad.py": "STILL BROKEN"}),
            make_reviewer_fail_response(feedback="Broken on attempt 2."),
            make_reviewer_pass_response(),
            make_reviewer_pass_response(),

            make_developer_response({"src/bad.py": "BROKEN AGAIN"}),
            make_reviewer_fail_response(feedback="Broken on attempt 3."),
            make_reviewer_pass_response(),
            make_reviewer_pass_response(),
        ]

        subgraph    = build_task_subgraph(task, max_retries=2)
        final_state = await subgraph.ainvoke(
            _initial_state(task, max_retries=2),
            config={"recursion_limit": 50},
        )

        assert final_state["final_status"] == TaskStatus.FAILED.value
        assert final_state["generated_files"] == []
        mock_file_store.save_workspace_file.assert_not_called()

    @pytest.mark.asyncio
    async def test_advisory_failure_does_not_block_completion(self, mock_openai):
        """
        One reviewer returns severity=advisory.
        Advisory failures do not block â€” task still completes.
        """
        task = _make_task(pattern_refs=[])

        mock_openai.side_effect = [
            make_developer_response({"src/ok.py": "pass"}),
            make_reviewer_pass_response(),
            _make_chat_response(
                '{"passed": false, "feedback": "Minor nit.", "severity": "advisory"}'
            ),
            make_reviewer_pass_response(),
        ]

        subgraph    = build_task_subgraph(task, max_retries=3)
        final_state = await subgraph.ainvoke(
            _initial_state(task),
            config={"recursion_limit": 50},
        )

        assert final_state["final_status"] == TaskStatus.COMPLETED.value
        assert "src/ok.py" in final_state["generated_files"]

    @pytest.mark.asyncio
    async def test_all_three_reviewers_blocking_fail(self, mock_openai):
        """
        All three reviewers return blocking failures simultaneously.
        Feedback from all three is collected in aggregated_feedback.
        Task retries, then eventually fails if cap is hit.
        """
        task = _make_task(pattern_refs=[])

        # max_retries=1: 2 attempts total, each gets 3 blocking fails
        mock_openai.side_effect = [
            make_developer_response({"src/a.py": "bad"}),
            make_reviewer_fail_response(reviewer="workflow_reviewer",  feedback="W fail"),
            make_reviewer_fail_response(reviewer="prompt_reviewer",    feedback="P fail"),
            make_reviewer_fail_response(reviewer="security_reviewer",  feedback="S fail"),

            make_developer_response({"src/a.py": "still bad"}),
            make_reviewer_fail_response(reviewer="workflow_reviewer",  feedback="W fail again"),
            make_reviewer_fail_response(reviewer="prompt_reviewer",    feedback="P fail again"),
            make_reviewer_fail_response(reviewer="security_reviewer",  feedback="S fail again"),
        ]

        subgraph    = build_task_subgraph(task, max_retries=1)
        final_state = await subgraph.ainvoke(
            _initial_state(task, max_retries=1),
            config={"recursion_limit": 50},
        )

        assert final_state["final_status"] == TaskStatus.FAILED.value
        # Aggregated feedback should mention at least one reviewer
        feedback = final_state.get("aggregated_feedback") or ""
        assert len(feedback) > 0

    @pytest.mark.asyncio
    async def test_multiple_files_all_written(self, mock_openai):
        """
        Developer produces three files.
        All are written to disk on successful review.
        generated_files contains all three paths.
        """
        task = _make_task(pattern_refs=[])

        mock_openai.side_effect = [
            make_developer_response({
                "src/a.py": "# a",
                "src/b.py": "# b",
                "src/c.py": "# c",
            }),
            make_reviewer_pass_response(),
            make_reviewer_pass_response(),
            make_reviewer_pass_response(),
        ]

        subgraph    = build_task_subgraph(task, max_retries=3)
        final_state = await subgraph.ainvoke(
            _initial_state(task),
            config={"recursion_limit": 50},
        )

        assert final_state["final_status"] == TaskStatus.COMPLETED.value
        assert set(final_state["generated_files"]) == {"src/a.py", "src/b.py", "src/c.py"}
        assert mock_file_store.save_workspace_file.call_count == 3


# ===========================================================================
# REFLECTION TOPOLOGY
# ===========================================================================

class TestReflectionTopology:
    """
    Tests for tasks with pattern_refs=["Reflection"].
    Inserts critic_node between developer_node and reviewer fan-out.
    """

    @pytest.mark.asyncio
    async def test_critic_passes_first_time(self, mock_openai):
        """
        Critic approves on first attempt.
        Graph proceeds directly to reviewers â€” no revision cycle.
        LLM calls: 1 developer + 1 critic + 3 reviewers = 5 total.
        """
        task = _make_task(pattern_refs=["Reflection"])

        mock_openai.side_effect = [
            make_developer_response({"src/loop.py": "for i in range(n): pass"}),
            make_critic_pass_response(),
            make_reviewer_pass_response(),
            make_reviewer_pass_response(),
            make_reviewer_pass_response(),
        ]

        subgraph    = build_task_subgraph(task, max_retries=3)
        final_state = await subgraph.ainvoke(
            _initial_state(task),
            config={"recursion_limit": 50},
        )

        assert final_state["final_status"] == TaskStatus.COMPLETED.value
        assert "src/loop.py" in final_state["generated_files"]
        assert mock_openai.call_count == 5

    @pytest.mark.asyncio
    async def test_critic_fails_once_then_passes(self, mock_openai):
        """
        Critic identifies a problem.
        Developer revises.
        Critic approves the revision.
        Reviewers all pass.
        Task completes.
        """
        task = _make_task(pattern_refs=["Reflection"])

        mock_openai.side_effect = [
            # Developer attempt 1
            make_developer_response({"src/loop.py": "while True: pass"}),
            # Critic: fail
            make_critic_fail_response("Loop is unbounded."),
            # Developer revision (attempt 2)
            make_developer_response({"src/loop.py": "for i in range(max_iter): pass"}),
            # Critic: pass
            make_critic_pass_response(),
            # Three reviewers pass
            make_reviewer_pass_response(),
            make_reviewer_pass_response(),
            make_reviewer_pass_response(),
        ]

        subgraph    = build_task_subgraph(task, max_retries=3)
        final_state = await subgraph.ainvoke(
            _initial_state(task),
            config={"recursion_limit": 50},
        )

        assert final_state["final_status"] == TaskStatus.COMPLETED.value
        # critic_feedback should be cleared after passing
        assert not final_state.get("critic_feedback")

    @pytest.mark.asyncio
    async def test_critic_fail_followed_by_reviewer_fail_then_recovery(
        self, mock_openai
    ):
        """
        Critic fails once (inner loop revision).
        After critic passes, one reviewer fails (outer retry loop).
        Developer retries again.
        All reviewers pass on second outer attempt.
        """
        task = _make_task(pattern_refs=["Reflection"])

        mock_openai.side_effect = [
            # Developer attempt 1
            make_developer_response({"src/a.py": "v1"}),
            # Critic fail
            make_critic_fail_response("Issue found."),
            # Developer revision
            make_developer_response({"src/a.py": "v2"}),
            # Critic pass
            make_critic_pass_response(),
            # Reviewer fail on first outer attempt
            make_reviewer_fail_response(feedback="Needs improvement."),
            make_reviewer_pass_response(),
            make_reviewer_pass_response(),
            # Developer retry (outer)
            make_developer_response({"src/a.py": "v3"}),
            # Critic pass (second outer attempt enters critic again)
            make_critic_pass_response(),
            # All reviewers pass
            make_reviewer_pass_response(),
            make_reviewer_pass_response(),
            make_reviewer_pass_response(),
        ]

        subgraph    = build_task_subgraph(task, max_retries=3)
        final_state = await subgraph.ainvoke(
            _initial_state(task),
            config={"recursion_limit": 50},
        )

        assert final_state["final_status"] == TaskStatus.COMPLETED.value

    @pytest.mark.asyncio
    async def test_reflection_retry_cap_exhausted(self, mock_openai):
        """
        Critic keeps failing. Retry count increments per developer call.
        When retry_count exceeds max_retries, route_after_reduce sends to FAIL.
        Note: critic failures count against the retry budget via retry_count
        increment in developer_node â€” the same budget governs both loops.
        """
        task = _make_task(pattern_refs=["Reflection"])

        # max_retries=1: critic will fail both attempts
        mock_openai.side_effect = [
            make_developer_response({"src/a.py": "v1"}),
            make_critic_fail_response("Still broken."),
            make_developer_response({"src/a.py": "v2"}),
            make_critic_fail_response("Still broken."),
            make_developer_response({"src/a.py": "v3"}),
            make_critic_pass_response(),          # eventually passes critic
            make_reviewer_fail_response(),        # but reviewer blocks
            make_reviewer_pass_response(),
            make_reviewer_pass_response(),
        ]

        subgraph    = build_task_subgraph(task, max_retries=1)
        final_state = await subgraph.ainvoke(
            _initial_state(task, max_retries=1),
            config={"recursion_limit": 50},
        )

        # With max_retries=1, cap is hit before reviewers can pass
        assert final_state["final_status"] == TaskStatus.FAILED.value


# ===========================================================================
# TOOL-USE TOPOLOGY
# ===========================================================================

class TestToolUseTopology:
    """
    Tests for tasks with pattern_refs=["Tool-Use"].
    Inserts tool_syntax_check_node before the reviewer fan-out.
    """

    # Canonical good Tool-Use output â€” passes all three tool checks.
    _GOOD_TOOLS = (
        "from langgraph.prebuilt import ToolNode\n\n"
        "def search_documents(query: str) -> dict:\n"
        '    """Search the document store for relevant chunks."""\n'
        "    return {}\n\n"
        "tools = [search_documents]\n"
        "tool_node = ToolNode(tools)\n"
    )

    # Bad output â€” no ToolNode, no tools list, no docstring.
    _BAD_TOOLS = (
        "def search(q):\n"
        "    return q\n"
    )

    @pytest.mark.asyncio
    async def test_tool_check_passes_first_time(self, mock_openai):
        """
        Developer output includes ToolNode, tools list, and docstring.
        tool_syntax_check_node passes without retry.
        Reviewers all pass.
        Exactly 4 LLM calls: 1 developer + 3 reviewers.
        """
        task = _make_task(pattern_refs=["Tool-Use"])

        mock_openai.side_effect = [
            _make_chat_response(
                f'<file path="tools.py">\n{self._GOOD_TOOLS}\n</file>'
            ),
            make_reviewer_pass_response(),
            make_reviewer_pass_response(),
            make_reviewer_pass_response(),
        ]

        subgraph    = build_task_subgraph(task, max_retries=3)
        final_state = await subgraph.ainvoke(
            _initial_state(task),
            config={"recursion_limit": 50},
        )

        assert final_state["final_status"] == TaskStatus.COMPLETED.value
        assert "tools.py" in final_state["generated_files"]
        assert mock_openai.call_count == 4

    @pytest.mark.asyncio
    async def test_tool_check_fails_then_passes(self, mock_openai):
        """
        First output fails tool check (no ToolNode).
        Second output passes.
        Reviewers all pass.
        Task completes.
        """
        task = _make_task(pattern_refs=["Tool-Use"])

        mock_openai.side_effect = [
            _make_chat_response(
                f'<file path="tools.py">\n{self._BAD_TOOLS}\n</file>'
            ),
            _make_chat_response(
                f'<file path="tools.py">\n{self._GOOD_TOOLS}\n</file>'
            ),
            make_reviewer_pass_response(),
            make_reviewer_pass_response(),
            make_reviewer_pass_response(),
        ]

        subgraph    = build_task_subgraph(task, max_retries=3)
        final_state = await subgraph.ainvoke(
            _initial_state(task),
            config={"recursion_limit": 50},
        )

        assert final_state["final_status"] == TaskStatus.COMPLETED.value
        assert "tools.py" in final_state["generated_files"]

    @pytest.mark.asyncio
    async def test_tool_check_fail_exhausts_cap(self, mock_openai):
        """
        Developer always produces output without ToolNode.
        Tool check increments retry_count on each failure.
        Cap is hit â†’ task finalises as FAILED.
        """
        task = _make_task(pattern_refs=["Tool-Use"])

        bad_resp = _make_chat_response(
            f'<file path="tools.py">\n{self._BAD_TOOLS}\n</file>'
        )
        # max_retries=2: cap hit after 3 total attempts at tool check
        mock_openai.side_effect = [bad_resp] * 10  # more than enough

        subgraph    = build_task_subgraph(task, max_retries=2)
        final_state = await subgraph.ainvoke(
            _initial_state(task, max_retries=2),
            config={"recursion_limit": 50},
        )

        assert final_state["final_status"] == TaskStatus.FAILED.value
        mock_file_store.save_workspace_file.assert_not_called()

    @pytest.mark.asyncio
    async def test_tool_check_pass_then_reviewer_fail_retries(self, mock_openai):
        """
        Tool check passes on first attempt.
        One reviewer fails.
        Developer retries (tool check must pass again on retry).
        Reviewers all pass on second attempt.
        """
        task = _make_task(pattern_refs=["Tool-Use"])

        good_resp = _make_chat_response(
            f'<file path="tools.py">\n{self._GOOD_TOOLS}\n</file>'
        )

        mock_openai.side_effect = [
            # Attempt 1: tool check passes, reviewer fails
            good_resp,
            make_reviewer_fail_response(feedback="Needs more tools."),
            make_reviewer_pass_response(),
            make_reviewer_pass_response(),
            # Attempt 2: tool check passes again, all reviewers pass
            good_resp,
            make_reviewer_pass_response(),
            make_reviewer_pass_response(),
            make_reviewer_pass_response(),
        ]

        subgraph    = build_task_subgraph(task, max_retries=3)
        final_state = await subgraph.ainvoke(
            _initial_state(task),
            config={"recursion_limit": 50},
        )

        assert final_state["final_status"] == TaskStatus.COMPLETED.value


# ===========================================================================
# REFLECTION + TOOL-USE COMBINED TOPOLOGY
# ===========================================================================

class TestReflectionAndToolUseTopology:
    """
    Tests for tasks with pattern_refs=["Reflection", "Tool-Use"].
    Most complex topology:
        developer â†’ tool_check â†’ critic â†’ _proceed_to_review â†’ reviewers
    """

    _GOOD = (
        "from langgraph.prebuilt import ToolNode\n\n"
        "def get_status(run_id: str) -> dict:\n"
        '    """Get the current run status."""\n'
        "    return {}\n\n"
        "tools = [get_status]\n"
        "tool_node = ToolNode(tools)\n\n"
        "for i in range(max_iter):\n    pass\n"
    )

    _BAD_TOOLS = "def helper(): pass\n"

    @pytest.mark.asyncio
    async def test_full_happy_path(self, mock_openai):
        """
        Tool check passes, critic passes, reviewers all pass.
        Happy path through the most complex topology.
        LLM calls: 1 developer + 1 critic + 3 reviewers = 5 total.
        """
        task = _make_task(pattern_refs=["Reflection", "Tool-Use"])

        mock_openai.side_effect = [
            _make_chat_response(f'<file path="agent.py">\n{self._GOOD}\n</file>'),
            make_critic_pass_response(),
            make_reviewer_pass_response(),
            make_reviewer_pass_response(),
            make_reviewer_pass_response(),
        ]

        subgraph    = build_task_subgraph(task, max_retries=3)
        final_state = await subgraph.ainvoke(
            _initial_state(task),
            config={"recursion_limit": 50},
        )

        assert final_state["final_status"] == TaskStatus.COMPLETED.value
        assert "agent.py" in final_state["generated_files"]
        assert mock_openai.call_count == 5

    @pytest.mark.asyncio
    async def test_tool_fail_then_critic_fail_then_pass(self, mock_openai):
        """
        First developer output fails tool check.
        After fix, critic fails.
        Developer revises again.
        Critic passes. Reviewers pass.
        Task completes.
        """
        task = _make_task(pattern_refs=["Reflection", "Tool-Use"])

        mock_openai.side_effect = [
            # Attempt 1: tool check fail
            _make_chat_response(
                f'<file path="agent.py">\n{self._BAD_TOOLS}\n</file>'
            ),
            # Attempt 2: tool check pass, critic fail
            _make_chat_response(f'<file path="agent.py">\n{self._GOOD}\n</file>'),
            make_critic_fail_response("Planner dispatch missing."),
            # Attempt 3: tool check pass, critic pass, reviewers pass
            _make_chat_response(f'<file path="agent.py">\n{self._GOOD}\n</file>'),
            make_critic_pass_response(),
            make_reviewer_pass_response(),
            make_reviewer_pass_response(),
            make_reviewer_pass_response(),
        ]

        subgraph    = build_task_subgraph(task, max_retries=3)
        final_state = await subgraph.ainvoke(
            _initial_state(task),
            config={"recursion_limit": 50},
        )

        assert final_state["final_status"] == TaskStatus.COMPLETED.value

    @pytest.mark.asyncio
    async def test_pattern_order_does_not_affect_topology(self, mock_openai):
        """
        ["Tool-Use", "Reflection"] and ["Reflection", "Tool-Use"] produce
        the same compiled graph (cache key is a frozenset).
        Both reach COMPLETED with identical mock call sequences.
        """
        task_a = _make_task(pattern_refs=["Reflection", "Tool-Use"])
        task_b = _make_task(pattern_refs=["Tool-Use", "Reflection"])

        shared_side_effect = [
            _make_chat_response(f'<file path="a.py">\n{self._GOOD}\n</file>'),
            make_critic_pass_response(),
            make_reviewer_pass_response(),
            make_reviewer_pass_response(),
            make_reviewer_pass_response(),
        ]

        mock_openai.side_effect = shared_side_effect.copy()
        g_a = build_task_subgraph(task_a, max_retries=3)
        s_a = await g_a.ainvoke(_initial_state(task_a), config={"recursion_limit": 50})

        mock_openai.side_effect = shared_side_effect.copy()
        g_b = build_task_subgraph(task_b, max_retries=3)
        s_b = await g_b.ainvoke(_initial_state(task_b), config={"recursion_limit": 50})

        assert g_a is g_b  # same compiled graph object
        assert s_a["final_status"] == TaskStatus.COMPLETED.value
        assert s_b["final_status"] == TaskStatus.COMPLETED.value


# ===========================================================================
# EDGE CASES
# ===========================================================================

class TestEdgeCases:

    @pytest.mark.asyncio
    async def test_developer_parse_failure_marks_task_failed(self, mock_openai):
        """
        Developer returns prose with no <file> blocks.
        parse_developer_output raises ValueError.
        developer_node sets state["error"] and pending_files=[].
        finalize_task_node marks the task FAILED.
        No files written to disk.
        """
        task = _make_task(pattern_refs=[])

        mock_openai.return_value = _make_chat_response(
            "I have analysed the requirements. Here is my plan: ..."
        )

        subgraph    = build_task_subgraph(task, max_retries=1)
        final_state = await subgraph.ainvoke(
            _initial_state(task, max_retries=1),
            config={"recursion_limit": 50},
        )

        assert final_state["final_status"] == TaskStatus.FAILED.value
        assert final_state["generated_files"] == []
        mock_file_store.save_workspace_file.assert_not_called()

    @pytest.mark.asyncio
    async def test_developer_llm_exception_marks_task_failed(self, mock_openai):
        """
        OpenAI call raises a connection error.
        developer_node catches it and sets state["error"].
        Task ultimately fails gracefully â€” no unhandled exception propagates.
        """
        task = _make_task(pattern_refs=[])

        mock_openai.side_effect = Exception("Connection reset by peer.")

        subgraph    = build_task_subgraph(task, max_retries=1)
        final_state = await subgraph.ainvoke(
            _initial_state(task, max_retries=1),
            config={"recursion_limit": 50},
        )

        assert final_state["final_status"] == TaskStatus.FAILED.value
        assert "Connection reset" in (final_state.get("error") or "")

    @pytest.mark.asyncio
    async def test_reviewer_llm_exception_is_blocking_not_silent_pass(
        self, mock_openai
    ):
        """
        One reviewer's LLM call raises an exception.
        _call_reviewer() catches it and returns a blocking ReviewerVerdict
        with passed=False.  The task fails â€” an infrastructure error does
        not silently pass a review.
        """
        task = _make_task(pattern_refs=[])

        mock_openai.side_effect = [
            make_developer_response({"src/a.py": "pass"}),
            Exception("Reviewer LLM timeout."),  # workflow_reviewer fails
            make_reviewer_pass_response(),        # prompt_reviewer passes
            make_reviewer_pass_response(),        # security_reviewer passes
        ]

        subgraph    = build_task_subgraph(task, max_retries=0)
        final_state = await subgraph.ainvoke(
            _initial_state(task, max_retries=0),
            config={"recursion_limit": 50},
        )

        # max_retries=0 means the single failure immediately exhausts the cap
        assert final_state["final_status"] == TaskStatus.FAILED.value

    @pytest.mark.asyncio
    async def test_empty_file_content_still_written(self, mock_openai):
        """
        Developer produces a file with empty content.
        Empty files are valid â€” written to disk, task completes.
        """
        task = _make_task(pattern_refs=[])

        mock_openai.side_effect = [
            make_developer_response({"src/__init__.py": ""}),
            make_reviewer_pass_response(),
            make_reviewer_pass_response(),
            make_reviewer_pass_response(),
        ]

        subgraph    = build_task_subgraph(task, max_retries=3)
        final_state = await subgraph.ainvoke(
            _initial_state(task),
            config={"recursion_limit": 50},
        )

        assert final_state["final_status"] == TaskStatus.COMPLETED.value
        assert "src/__init__.py" in final_state["generated_files"]

    @pytest.mark.asyncio
    async def test_max_retries_zero_means_one_attempt_only(self, mock_openai):
        """
        max_retries=0 allows exactly one attempt.
        If reviewers fail, the task immediately fails â€” no retry cycle.
        """
        task = _make_task(pattern_refs=[])

        mock_openai.side_effect = [
            make_developer_response({"src/a.py": "pass"}),
            make_reviewer_fail_response(feedback="Instant fail."),
            make_reviewer_pass_response(),
            make_reviewer_pass_response(),
        ]

        subgraph    = build_task_subgraph(task, max_retries=0)
        final_state = await subgraph.ainvoke(
            _initial_state(task, max_retries=0),
            config={"recursion_limit": 50},
        )

        assert final_state["final_status"] == TaskStatus.FAILED.value
        # Developer was called exactly once
        # (1 dev + 3 reviewers = 4 total calls)
        assert mock_openai.call_count == 4

    @pytest.mark.asyncio
    async def test_last_file_write_fails_task_marked_failed(self, mock_openai):
        """
        Review passes but every file write raises an exception.
        finalize_task_node catches the write errors.
        Task is marked FAILED (no files successfully written).
        """
        task = _make_task(pattern_refs=[])

        mock_openai.side_effect = [
            make_developer_response({"src/a.py": "pass"}),
            make_reviewer_pass_response(),
            make_reviewer_pass_response(),
            make_reviewer_pass_response(),
        ]

        mock_file_store.save_workspace_file.side_effect = OSError("Disk full.")

        subgraph    = build_task_subgraph(task, max_retries=3)
        final_state = await subgraph.ainvoke(
            _initial_state(task),
            config={"recursion_limit": 50},
        )

        assert final_state["final_status"] == TaskStatus.FAILED.value
        assert final_state["generated_files"] == []


# ===========================================================================
# COMPILATION CACHE
# ===========================================================================

class TestCompilationCache:

    def test_same_patterns_returns_cached_instance(self):
        """
        Two calls with identical pattern_refs return the same object.
        """
        t1 = _make_task(pattern_refs=["Reflection"])
        t2 = _make_task(pattern_refs=["Reflection"])

        g1 = build_task_subgraph(t1)
        g2 = build_task_subgraph(t2)

        assert g1 is g2

    def test_different_patterns_return_distinct_instances(self):
        """
        All four topology combinations produce distinct compiled graphs.
        """
        t_base    = _make_task(pattern_refs=[])
        t_reflect = _make_task(pattern_refs=["Reflection"])
        t_tool    = _make_task(pattern_refs=["Tool-Use"])
        t_both    = _make_task(pattern_refs=["Reflection", "Tool-Use"])

        g_base    = build_task_subgraph(t_base)
        g_reflect = build_task_subgraph(t_reflect)
        g_tool    = build_task_subgraph(t_tool)
        g_both    = build_task_subgraph(t_both)

        ids = {id(g_base), id(g_reflect), id(g_tool), id(g_both)}
        assert len(ids) == 4

    def test_pattern_order_irrelevant_for_cache_key(self):
        """
        ["Reflection", "Tool-Use"] and ["Tool-Use", "Reflection"]
        resolve to the same frozenset cache key and return the same graph.
        """
        t_a = _make_task(pattern_refs=["Reflection", "Tool-Use"])
        t_b = _make_task(pattern_refs=["Tool-Use", "Reflection"])

        g_a = build_task_subgraph(t_a)
        g_b = build_task_subgraph(t_b)

        assert g_a is g_b

    def test_unknown_patterns_do_not_create_new_topology(self):
        """
        An unrecognised pattern tag is silently ignored for topology purposes.
        A task with ["UnknownPattern"] compiles the same base topology as [].
        The two graphs are the same cached instance.
        """
        t_unknown = _make_task(pattern_refs=["UnknownPattern"])
        t_base    = _make_task(pattern_refs=[])

        g_unknown = build_task_subgraph(t_unknown)
        g_base    = build_task_subgraph(t_base)

        # frozenset(["UnknownPattern"]) != frozenset([]) so they are cached
        # separately, but both should compile to the base topology successfully.
        assert g_unknown is not None
        assert g_base    is not None

    def test_clear_cache_removes_all_entries(self):
        """
        clear_subgraph_cache() empties _SUBGRAPH_CACHE.
        After clearing, a fresh compile produces a new graph instance.
        """
        task = _make_task(pattern_refs=["Reflection"])

        g_before = build_task_subgraph(task)
        assert len(_SUBGRAPH_CACHE) > 0

        clear_subgraph_cache()
        assert len(_SUBGRAPH_CACHE) == 0

        g_after = build_task_subgraph(task)
        # Different instance â€” cache was cleared and recompiled
        assert g_before is not g_after

    def test_get_cached_patterns_returns_current_keys(self):
        """
        get_cached_patterns() reflects what is currently in the cache.
        """
        _make_task(pattern_refs=[])
        _make_task(pattern_refs=["Reflection"])

        build_task_subgraph(_make_task(pattern_refs=[]))
        build_task_subgraph(_make_task(pattern_refs=["Reflection"]))

        cached = get_cached_patterns()
        assert [] in cached
        assert ["Reflection"] in cached

    def test_cache_populated_after_first_compile(self):
        """
        Cache is empty before any build call (reset_subgraph_cache runs before each test).
        After one build, cache has exactly one entry.
        """
        assert len(_SUBGRAPH_CACHE) == 0

        task = _make_task(pattern_refs=["Tool-Use"])
        build_task_subgraph(task)

        assert len(_SUBGRAPH_CACHE) == 1
        assert frozenset(["Tool-Use"]) in _SUBGRAPH_CACHE


