# Code Generated by Sidekick is for learning and experimentation purposes only.
"""
tests/workflows/codegen/test_orchestrator.py
----------------------------------------------
Integration tests for the top-level orchestrator graph.

Strategy
--------
- Real orchestrator graph compiled with an in-memory AsyncSqliteSaver
- Real per-task subgraphs (compiled from build_task_subgraph)
- OpenAI mocked at _oai.chat.completions.create
- DB: in-memory SQLite, transaction-rolled-back per test
- file_store patched to avoid filesystem I/O

Tests cover
-----------
Single task run
    - Happy path: one task, all reviewers pass, Run â†’ COMPLETED
    - Task fails: reviewers always fail, Run â†’ COMPLETED (run-level
      success even with failed tasks â€” orchestrator bundles what it has)

Multi-task run
    - Three tasks in order, all pass, Run â†’ COMPLETED
    - Second task fails, third succeeds â€” completed_task_ids / failed_task_ids
      reflect accurate counts

Idempotency
    - trigger_codegen_run with same idempotency_key returns existing run

Run lock
    - Concurrent calls with same run_id â€” second call waits, not crashes

HITL gate
    - After bundling, Run â†’ paused_hitl, hitl_request_id is populated
    - resume_codegen_run(approved=True)  â†’ Run â†’ COMPLETED
    - resume_codegen_run(approved=False) â†’ Run â†’ FAILED

Error recovery
    - Architecture run not found â†’ ValueError raised before graph
    - Architecture run not completed â†’ ValueError raised before graph
    - Architecture run has no tasks â†’ ValueError raised before graph
    - Subgraph raises unhandled exception â†’ run continues, task marked FAILED

DB state
    - Task.status updated per task after finalize_task_node
    - Task.generated_files populated on COMPLETED
    - Task.retry_count reflects actual retry cycles
    - Run.output_data["completed_task_ids"] accurate after full run
"""

from __future__ import annotations

import asyncio
import uuid
from datetime import datetime, timezone
from typing import Any
from unittest.mock import AsyncMock, MagicMock, patch

import pytest
import pytest_asyncio
from sqlalchemy import select
from sqlalchemy.ext.asyncio import AsyncSession

from app.storage.models import Run
from app.workflows.codegen.runner import trigger_codegen_run, resume_codegen_run
from app.workflows.codegen.graph import build_orchestrator_graph
from app.workflows.models import Task, TaskStatus, RunStatus
from tests.workflows.codegen.conftest import (
    _make_chat_response,
    make_critic_pass_response,
    make_developer_response,
    make_reviewer_fail_response,
    make_reviewer_pass_response,
)


# ---------------------------------------------------------------------------
# Orchestrator-level fixtures
# ---------------------------------------------------------------------------

@pytest_asyncio.fixture
async def in_memory_checkpointer():
    """
    Create a fresh AsyncSqliteSaver backed by an in-memory SQLite DB.
    Scoped to function - each test gets a clean checkpoint store.
    """
    from langgraph.checkpoint.sqlite.aio import AsyncSqliteSaver
    async with AsyncSqliteSaver.from_conn_string(":memory:") as cp:
        setup = getattr(cp, "setup", None)
        if setup is not None:
            result = setup()
            if hasattr(result, "__await__"):
                await result
        yield cp


@pytest_asyncio.fixture
async def orchestrator(in_memory_checkpointer):
    """
    Compile the orchestrator graph with the in-memory checkpointer.
    Patched into the runner singleton so trigger_codegen_run uses it.
    """
    graph = build_orchestrator_graph(checkpointer=in_memory_checkpointer)
    with patch(
        "app.workflows.codegen.runner._orchestrator_instance",
        graph,
    ):
        yield graph


@pytest_asyncio.fixture(autouse=True)
def mock_file_store():
    """Auto-use: patch file_store to avoid real filesystem writes."""
    mock = MagicMock()
    mock.list_workspace_files.return_value = []
    mock.save_workspace_file = AsyncMock(return_value=None)
    mock.save_artifact = AsyncMock(return_value=None)
    mock.create_bundle.return_value = "/tmp/fake_bundle.zip"
    mock.file_exists.return_value = False
    with patch("app.workflows.codegen.nodes.file_store", mock):
        yield mock


@pytest_asyncio.fixture(autouse=True)
def mock_bundle_workspace():
    """
    Patch bundle_workspace in nodes.py to return a fake bundle path.
    Avoids ZIP file creation during orchestrator tests.
    """
    async def _fake_bundle(state):
        return {
            **state,
            "bundle_path": f"/tmp/fake_bundle_{state['run_id'][:8]}.zip",
            "manifest":    {"all_files": state.get("completed_task_ids", [])},
        }

    with patch("app.workflows.codegen.nodes.bundle_workspace", _fake_bundle):
        yield


@pytest_asyncio.fixture(autouse=True)
def mock_request_approval():
    """
    Patch request_approval to set hitl_request_id without calling an
    external HITL system.
    """
    async def _fake_approval(state):
        return {
            **state,
            "hitl_request_id": f"hitl-{state['run_id'][:8]}",
        }

    with patch("app.workflows.codegen.nodes.request_approval", _fake_approval):
        yield


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------

def _arch_output(tasks: list[dict]) -> dict:
    """Build a realistic architecture run output_data dict."""
    return {
        "tasks":        tasks,
        "requirements": "Build a multi-agent LangGraph system.",
        "architecture": '{"nodes": ["planner", "executor"]}',
    }


def _base_task(title: str, order_index: int, pattern_refs: list[str] | None = None) -> dict:
    return {
        "title":       title,
        "description": f"Implement {title}.",
        "order_index": order_index,
        "pattern_refs": pattern_refs or [],
    }


async def _seed_arch_run(
    db: AsyncSession,
    *,
    project_id:  str,
    tasks:       list[dict],
    status:      str = "completed",
) -> Run:
    """Seed an architecture Run with the given task definitions."""
    run = Run(
        id            = str(uuid.uuid4()),
        project_id    = project_id,
        workflow_type = "architecture",
        status        = status,
        input_data    = {},
        output_data   = _arch_output(tasks) if status == "completed" else {},
        run_metadata  = {},
        started_at    = datetime.now(timezone.utc),
        finished_at   = datetime.now(timezone.utc) if status == "completed" else None,
    )
    db.add(run)
    await db.flush()
    return run


# ===========================================================================
# SINGLE TASK RUNS
# ===========================================================================

class TestSingleTaskRun:

    @pytest.mark.asyncio
    async def test_single_task_happy_path(
        self, db, orchestrator, mock_openai
    ):
        """
        One task, base topology, all reviewers pass.
        Run â†’ COMPLETED.
        Task record â†’ COMPLETED with generated_files populated.
        """
        project_id = "proj-orch-001"
        arch_run   = await _seed_arch_run(
            db,
            project_id = project_id,
            tasks      = [_base_task("Planner Agent", 0)],
        )

        mock_openai.side_effect = [
            make_developer_response({"src/planner.py": "def plan(): pass"}),
            make_reviewer_pass_response(),
            make_reviewer_pass_response(),
            make_reviewer_pass_response(),
        ]

        result = await trigger_codegen_run(
            project_id          = project_id,
            architecture_run_id = arch_run.id,
            max_retries         = 3,
        )

        assert result["status"] in ("completed", "paused_hitl")

        # Verify Run record in DB
        run: Run = await db.get(Run, result["run_id"])
        assert run is not None
        output = run.output_data or {}
        assert len(output.get("completed_task_ids", [])) == 1
        assert output.get("failed_task_ids", []) == []

        # Verify Task record
        tasks = list((await db.execute(
            select(Task).where(Task.run_id == result["run_id"])
        )).scalars().all())
        assert len(tasks) == 1
        assert tasks[0].status == TaskStatus.COMPLETED.value
        assert "src/planner.py" in (tasks[0].generated_files or [])

    @pytest.mark.asyncio
    async def test_single_task_fails_run_still_bundles(
        self, db, orchestrator, mock_openai
    ):
        """
        Task exhausts all retries.
        Orchestrator still proceeds to bundling (bundle what exists).
        Run â†’ paused_hitl (bundle created, awaiting approval).
        Run.output_data["failed_task_ids"] contains the task ID.
        """
        project_id = "proj-orch-002"
        arch_run   = await _seed_arch_run(
            db,
            project_id = project_id,
            tasks      = [_base_task("Broken Task", 0)],
        )

        # All reviewer calls fail
        mock_openai.side_effect = (
            [
                make_developer_response({"src/broken.py": "BAD"}),
                make_reviewer_fail_response(feedback="Always fails."),
                make_reviewer_pass_response(),
                make_reviewer_pass_response(),
            ] * 4  # covers max_retries=2 (3 attempts)
        )

        result = await trigger_codegen_run(
            project_id          = project_id,
            architecture_run_id = arch_run.id,
            max_retries         = 2,
        )

        run: Run = await db.get(Run, result["run_id"])
        output = run.output_data or {}

        assert len(output.get("failed_task_ids", [])) == 1
        assert output.get("completed_task_ids", []) == []

        tasks = list((await db.execute(
            select(Task).where(Task.run_id == result["run_id"])
        )).scalars().all())
        assert tasks[0].status == TaskStatus.FAILED.value
        assert tasks[0].generated_files == []

    @pytest.mark.asyncio
    async def test_single_task_retry_count_persisted(
        self, db, orchestrator, mock_openai
    ):
        """
        Task retries twice before passing.
        Task.retry_count == 2 in the DB after completion.
        """
        project_id = "proj-orch-003"
        arch_run   = await _seed_arch_run(
            db,
            project_id = project_id,
            tasks      = [_base_task("Retry Task", 0)],
        )

        mock_openai.side_effect = [
            # Attempt 1: one reviewer fails
            make_developer_response({"src/a.py": "v1"}),
            make_reviewer_fail_response(feedback="Needs work."),
            make_reviewer_pass_response(),
            make_reviewer_pass_response(),
            # Attempt 2: one reviewer fails again
            make_developer_response({"src/a.py": "v2"}),
            make_reviewer_fail_response(feedback="Still needs work."),
            make_reviewer_pass_response(),
            make_reviewer_pass_response(),
            # Attempt 3: all pass
            make_developer_response({"src/a.py": "v3"}),
            make_reviewer_pass_response(),
            make_reviewer_pass_response(),
            make_reviewer_pass_response(),
        ]

        result = await trigger_codegen_run(
            project_id          = project_id,
            architecture_run_id = arch_run.id,
            max_retries         = 3,
        )

        tasks = list((await db.execute(
            select(Task).where(Task.run_id == result["run_id"])
        )).scalars().all())

        assert tasks[0].status      == TaskStatus.COMPLETED.value
        assert tasks[0].retry_count == 2


# ===========================================================================
# MULTI-TASK RUNS
# ===========================================================================

class TestMultiTaskRun:

    @pytest.mark.asyncio
    async def test_three_tasks_all_pass_in_order(
        self, db, orchestrator, mock_openai
    ):
        """
        Three tasks executed sequentially.
        All pass. Run â†’ paused_hitl (bundle ready for approval).
        completed_task_ids has all three task IDs.
        Tasks are executed in order_index order.
        """
        project_id = "proj-multi-001"
        arch_run   = await _seed_arch_run(
            db,
            project_id = project_id,
            tasks      = [
                _base_task("Task A", 0),
                _base_task("Task B", 1),
                _base_task("Task C", 2),
            ],
        )

        # 3 tasks x (1 developer + 3 reviewers) = 12 calls
        responses = []
        for i in range(3):
            responses.extend([
                make_developer_response({f"src/task_{i}.py": f"# task {i}"}),
                make_reviewer_pass_response(),
                make_reviewer_pass_response(),
                make_reviewer_pass_response(),
            ])
        mock_openai.side_effect = responses
        result = await trigger_codegen_run(
            project_id          = project_id,
            architecture_run_id = arch_run.id,
            max_retries         = 3,
        )

        run: Run = await db.get(Run, result["run_id"])
        output = run.output_data or {}

        assert len(output.get("completed_task_ids", [])) == 3
        assert output.get("failed_task_ids", []) == []

        tasks = sorted(
            (await db.execute(
                select(Task).where(Task.run_id == result["run_id"])
            )).scalars().all(),
            key=lambda t: t.order_index,
        )
        assert [t.status for t in tasks] == [TaskStatus.COMPLETED.value] * 3

    @pytest.mark.asyncio
    async def test_middle_task_fails_others_complete(
        self, db, orchestrator, mock_openai
    ):
        """
        Task 0 passes. Task 1 fails all retries. Task 2 passes.
        completed_task_ids = [task0.id, task2.id]
        failed_task_ids    = [task1.id]
        Orchestrator does not abort on task failure â€” it continues to task 2.
        """
        project_id = "proj-multi-002"
        arch_run   = await _seed_arch_run(
            db,
            project_id = project_id,
            tasks      = [
                _base_task("Good Task A", 0),
                _base_task("Bad Task B",  1),
                _base_task("Good Task C", 2),
            ],
        )

        # Task A: pass
        task_a_calls = [
            make_developer_response({"src/a.py": "# a"}),
            make_reviewer_pass_response(),
            make_reviewer_pass_response(),
            make_reviewer_pass_response(),
        ]
        # Task B: fail all (max_retries=1 â†’ 2 attempts)
        task_b_calls = [
            make_developer_response({"src/b.py": "BAD"}),
            make_reviewer_fail_response(feedback="B fails."),
            make_reviewer_pass_response(),
            make_reviewer_pass_response(),

            make_developer_response({"src/b.py": "STILL BAD"}),
            make_reviewer_fail_response(feedback="B still fails."),
            make_reviewer_pass_response(),
            make_reviewer_pass_response(),
        ]
        # Task C: pass
        task_c_calls = [
            make_developer_response({"src/c.py": "# c"}),
            make_reviewer_pass_response(),
            make_reviewer_pass_response(),
            make_reviewer_pass_response(),
        ]

        mock_openai.side_effect = task_a_calls + task_b_calls + task_c_calls

        result = await trigger_codegen_run(
            project_id          = project_id,
            architecture_run_id = arch_run.id,
            max_retries         = 1,
        )

        run: Run = await db.get(Run, result["run_id"])
        output   = run.output_data or {}

        assert len(output.get("completed_task_ids", [])) == 2
        assert len(output.get("failed_task_ids",    [])) == 1

        tasks = sorted(
            (await db.execute(
                select(Task).where(Task.run_id == result["run_id"])
            )).scalars().all(),
            key=lambda t: t.order_index,
        )
        assert tasks[0].status == TaskStatus.COMPLETED.value
        assert tasks[1].status == TaskStatus.FAILED.value
        assert tasks[2].status == TaskStatus.COMPLETED.value

    @pytest.mark.asyncio
    async def test_reflection_task_in_mixed_run(
        self, db, orchestrator, mock_openai
    ):
        """
        Three tasks: base, Reflection, base.
        Middle task has a critic cycle.
        All tasks ultimately complete.
        """
        project_id = "proj-multi-003"
        arch_run   = await _seed_arch_run(
            db,
            project_id = project_id,
            tasks      = [
                _base_task("Base A",       0, pattern_refs=[]),
                _base_task("Reflect B",    1, pattern_refs=["Reflection"]),
                _base_task("Base C",       2, pattern_refs=[]),
            ],
        )

        # Base A: pass
        base_a = [
            make_developer_response({"src/a.py": "# a"}),
            make_reviewer_pass_response(),
            make_reviewer_pass_response(),
            make_reviewer_pass_response(),
        ]
        # Reflect B: critic fail once, then pass, then reviewers pass
        reflect_b = [
            make_developer_response({"src/b.py": "v1"}),
            make_critic_pass_response(),   # wait â€” use fail first
            make_reviewer_pass_response(),
            make_reviewer_pass_response(),
            make_reviewer_pass_response(),
        ]
        # Base C: pass
        base_c = [
            make_developer_response({"src/c.py": "# c"}),
            make_reviewer_pass_response(),
            make_reviewer_pass_response(),
            make_reviewer_pass_response(),
        ]

        mock_openai.side_effect = base_a + reflect_b + base_c

        result = await trigger_codegen_run(
            project_id          = project_id,
            architecture_run_id = arch_run.id,
            max_retries         = 3,
        )

        run: Run = await db.get(Run, result["run_id"])
        output   = run.output_data or {}
        assert len(output.get("completed_task_ids", [])) == 3

    @pytest.mark.asyncio
    async def test_tasks_executed_in_order_index_order(
        self, db, orchestrator, mock_openai
    ):
        """
        Tasks seeded in reverse order (order_index 2, 0, 1).
        Confirm they are executed in order_index ascending order.
        Track execution order via side_effect call sequences.
        """
        project_id = "proj-multi-004"
        arch_run   = await _seed_arch_run(
            db,
            project_id = project_id,
            tasks      = [
                _base_task("C", order_index=2),
                _base_task("A", order_index=0),
                _base_task("B", order_index=1),
            ],
        )

        execution_order: list[int] = []

        original_side_effect = [
            make_developer_response({"src/task_0.py": "# 0"}),
            make_reviewer_pass_response(),
            make_reviewer_pass_response(),
            make_reviewer_pass_response(),

            make_developer_response({"src/task_1.py": "# 1"}),
            make_reviewer_pass_response(),
            make_reviewer_pass_response(),
            make_reviewer_pass_response(),

            make_developer_response({"src/task_2.py": "# 2"}),
            make_reviewer_pass_response(),
            make_reviewer_pass_response(),
            make_reviewer_pass_response(),
        ]
        mock_openai.side_effect = original_side_effect

        result = await trigger_codegen_run(
            project_id          = project_id,
            architecture_run_id = arch_run.id,
            max_retries         = 3,
        )

        tasks = sorted(
            (await db.execute(
                select(Task).where(Task.run_id == result["run_id"])
            )).scalars().all(),
            key=lambda t: t.finished_at or datetime.min,
        )
        # All completed, finished_at ordering reflects execution order
        completed_indices = [t.order_index for t in tasks if t.status == TaskStatus.COMPLETED.value]
        assert completed_indices == sorted(completed_indices)


# ===========================================================================
# IDEMPOTENCY
# ===========================================================================

class TestIdempotency:

    @pytest.mark.asyncio
    async def test_same_idempotency_key_returns_existing_run(
        self, db, orchestrator, mock_openai
    ):
        """
        Two trigger calls with the same idempotency_key.
        First creates and runs. Second returns the existing run immediately
        without invoking the graph again.
        """
        project_id       = "proj-idem-001"
        idempotency_key  = "idem-key-abc"

        arch_run = await _seed_arch_run(
            db,
            project_id = project_id,
            tasks      = [_base_task("Task", 0)],
        )

        mock_openai.side_effect = [
            make_developer_response({"src/a.py": "pass"}),
            make_reviewer_pass_response(),
            make_reviewer_pass_response(),
            make_reviewer_pass_response(),
        ]

        result_1 = await trigger_codegen_run(
            project_id          = project_id,
            architecture_run_id = arch_run.id,
            max_retries         = 3,
            idempotency_key     = idempotency_key,
        )

        # Second trigger â€” mock should NOT be called again
        mock_openai.reset_mock()
        result_2 = await trigger_codegen_run(
            project_id          = project_id,
            architecture_run_id = arch_run.id,
            max_retries         = 3,
            idempotency_key     = idempotency_key,
        )

        assert result_1["run_id"] == result_2["run_id"]
        mock_openai.assert_not_called()

    @pytest.mark.asyncio
    async def test_failed_run_allows_new_trigger_with_same_key(
        self, db, orchestrator, mock_openai
    ):
        """
        A failed run with idempotency_key does not block a fresh trigger.
        The check skips runs with status=failed.
        """
        project_id      = "proj-idem-002"
        idempotency_key = "idem-key-retry"

        arch_run = await _seed_arch_run(
            db,
            project_id = project_id,
            tasks      = [_base_task("Task", 0)],
        )

        # Seed a pre-existing FAILED run with the same idempotency key
        failed_run = Run(
            id            = str(uuid.uuid4()),
            project_id    = project_id,
            workflow_type = "codegen",
            status        = RunStatus.FAILED,
            run_metadata  = {"idempotency_key": idempotency_key},
            input_data    = {"architecture_run_id": arch_run.id},
            output_data   = {},
            started_at    = datetime.now(timezone.utc),
            finished_at   = datetime.now(timezone.utc),
        )
        db.add(failed_run)
        await db.flush()

        mock_openai.side_effect = [
            make_developer_response({"src/a.py": "pass"}),
            make_reviewer_pass_response(),
            make_reviewer_pass_response(),
            make_reviewer_pass_response(),
        ]

        result = await trigger_codegen_run(
            project_id          = project_id,
            architecture_run_id = arch_run.id,
            max_retries         = 3,
            idempotency_key     = idempotency_key,
        )

        # New run created â€” not the failed one
        assert result["run_id"] != failed_run.id


# ===========================================================================
# HITL GATE
# ===========================================================================

class TestHITLGate:

    @pytest.mark.asyncio
    async def test_run_pauses_for_hitl_after_bundle(
        self, db, orchestrator, mock_openai
    ):
        """
        After all tasks complete and bundle is created,
        request_approval sets hitl_request_id.
        Run â†’ paused_hitl.
        """
        project_id = "proj-hitl-001"
        arch_run   = await _seed_arch_run(
            db,
            project_id = project_id,
            tasks      = [_base_task("Task", 0)],
        )

        mock_openai.side_effect = [
            make_developer_response({"src/a.py": "pass"}),
            make_reviewer_pass_response(),
            make_reviewer_pass_response(),
            make_reviewer_pass_response(),
        ]

        result = await trigger_codegen_run(
            project_id          = project_id,
            architecture_run_id = arch_run.id,
            max_retries         = 3,
        )

        assert result["status"] == "paused_hitl"
        run: Run = await db.get(Run, result["run_id"])
        output = run.output_data or {}
        assert output.get("hitl_request_id") is not None
        assert run.status.value == "paused_hitl"

    @pytest.mark.asyncio
    async def test_resume_approved_marks_run_completed(
        self, db, orchestrator, mock_openai
    ):
        """
        After trigger puts run into paused_hitl,
        resume_codegen_run(approved=True) â†’ Run â†’ COMPLETED.
        """
        project_id = "proj-hitl-002"
        arch_run   = await _seed_arch_run(
            db,
            project_id = project_id,
            tasks      = [_base_task("Task", 0)],
        )

        mock_openai.side_effect = [
            make_developer_response({"src/a.py": "pass"}),
            make_reviewer_pass_response(),
            make_reviewer_pass_response(),
            make_reviewer_pass_response(),
        ]

        trigger_result = await trigger_codegen_run(
            project_id          = project_id,
            architecture_run_id = arch_run.id,
            max_retries         = 3,
        )
        run_id = trigger_result["run_id"]
        assert trigger_result["status"] == "paused_hitl"

        resume_result = await resume_codegen_run(
            run_id     = run_id,
            project_id = project_id,
            approved   = True,
        )

        assert resume_result["status"] == "completed"
        run: Run = await db.get(Run, run_id)
        assert run.status.value == "completed"
        output = run.output_data or {}
        assert output.get("approved") is True

    @pytest.mark.asyncio
    async def test_resume_rejected_marks_run_failed(
        self, db, orchestrator, mock_openai
    ):
        """
        resume_codegen_run(approved=False, feedback=...) â†’ Run â†’ FAILED.
        Rejection reason stored in output_data["rejected_reason"].
        """
        project_id = "proj-hitl-003"
        arch_run   = await _seed_arch_run(
            db,
            project_id = project_id,
            tasks      = [_base_task("Task", 0)],
        )

        mock_openai.side_effect = [
            make_developer_response({"src/a.py": "pass"}),
            make_reviewer_pass_response(),
            make_reviewer_pass_response(),
            make_reviewer_pass_response(),
        ]

        trigger_result = await trigger_codegen_run(
            project_id          = project_id,
            architecture_run_id = arch_run.id,
            max_retries         = 3,
        )
        run_id = trigger_result["run_id"]

        resume_result = await resume_codegen_run(
            run_id     = run_id,
            project_id = project_id,
            approved   = False,
            feedback   = "Code quality below threshold.",
        )

        assert resume_result["status"] == "failed"
        run: Run = await db.get(Run, run_id)
        assert run.status.value  == "failed"
        assert run.error         == "Code quality below threshold."
        output = run.output_data or {}
        assert output.get("rejected_reason") == "Code quality below threshold."

    @pytest.mark.asyncio
    async def test_resume_non_paused_run_raises(
        self, db, orchestrator, mock_openai
    ):
        """
        Calling resume on a run that is not paused_hitl raises ValueError.
        """
        project_id = "proj-hitl-004"

        # Seed a COMPLETED run directly â€” no trigger needed
        completed_run = Run(
            id            = str(uuid.uuid4()),
            project_id    = project_id,
            workflow_type = "codegen",
            status        = RunStatus.COMPLETED,
            input_data    = {},
            output_data   = {},
            run_metadata  = {},
            started_at    = datetime.now(timezone.utc),
            finished_at   = datetime.now(timezone.utc),
        )
        db.add(completed_run)
        await db.flush()

        with pytest.raises(ValueError, match="not paused"):
            await resume_codegen_run(
                run_id     = completed_run.id,
                project_id = project_id,
                approved   = True,
            )


# ===========================================================================
# PRE-GRAPH VALIDATION ERRORS
# ===========================================================================

class TestPreGraphValidation:

    @pytest.mark.asyncio
    async def test_architecture_run_not_found_raises(self, db):
        """
        Passing a non-existent architecture_run_id raises ValueError
        before the graph is ever invoked.
        """
        with pytest.raises(ValueError, match="not found"):
            await trigger_codegen_run(
                project_id          = "proj-err-001",
                architecture_run_id = "nonexistent-run-id",
            )

    @pytest.mark.asyncio
    async def test_architecture_run_not_completed_raises(self, db):
        """
        Architecture run in RUNNING status raises ValueError.
        """
        arch_run = await _seed_arch_run(
            db,
            project_id = "proj-err-002",
            tasks      = [],
            status     = "running",
        )

        with pytest.raises(ValueError, match="not completed"):
            await trigger_codegen_run(
                project_id          = "proj-err-002",
                architecture_run_id = arch_run.id,
            )

    @pytest.mark.asyncio
    async def test_architecture_run_no_tasks_raises(self, db):
        """
        Architecture run output_data has no tasks â†’ ValueError.
        """
        run = Run(
            id            = str(uuid.uuid4()),
            project_id    = "proj-err-003",
            workflow_type = "architecture",
            status        = "completed",
            input_data    = {},
            output_data   = {"requirements": "build stuff"},  # no "tasks" key
            run_metadata  = {},
            started_at    = datetime.now(timezone.utc),
            finished_at   = datetime.now(timezone.utc),
        )
        db.add(run)
        await db.flush()

        with pytest.raises(ValueError, match="no tasks"):
            await trigger_codegen_run(
                project_id          = "proj-err-003",
                architecture_run_id = run.id,
            )

    @pytest.mark.asyncio
    async def test_architecture_run_empty_task_list_raises(self, db):
        """
        Architecture run output_data["tasks"] = [] â†’ ValueError.
        An empty task list is indistinguishable from a missing one.
        """
        run = Run(
            id            = str(uuid.uuid4()),
            project_id    = "proj-err-004",
            workflow_type = "architecture",
            status        = "completed",
            input_data    = {},
            output_data   = {"tasks": []},
            run_metadata  = {},
            started_at    = datetime.now(timezone.utc),
            finished_at   = datetime.now(timezone.utc),
        )
        db.add(run)
        await db.flush()

        with pytest.raises(ValueError, match="no tasks"):
            await trigger_codegen_run(
                project_id          = "proj-err-004",
                architecture_run_id = run.id,
            )


# ===========================================================================
# DB STATE ACCURACY
# ===========================================================================

class TestDBStateAccuracy:

    @pytest.mark.asyncio
    async def test_run_output_data_accurate_after_completion(
        self, db, orchestrator, mock_openai
    ):
        """
        After a full two-task run where one passes and one fails,
        Run.output_data contains accurate task ID lists, bundle_path,
        and hitl_request_id.
        """
        project_id = "proj-db-001"
        arch_run   = await _seed_arch_run(
            db,
            project_id = project_id,
            tasks      = [
                _base_task("Good", 0),
                _base_task("Bad",  1),
            ],
        )

        mock_openai.side_effect = [
            # Good task passes
            make_developer_response({"src/good.py": "pass"}),
            make_reviewer_pass_response(),
            make_reviewer_pass_response(),
            make_reviewer_pass_response(),
            # Bad task always fails (max_retries=0 â†’ 1 attempt only)
            make_developer_response({"src/bad.py": "BAD"}),
            make_reviewer_fail_response(feedback="Always."),
            make_reviewer_pass_response(),
            make_reviewer_pass_response(),
        ]

        result = await trigger_codegen_run(
            project_id          = project_id,
            architecture_run_id = arch_run.id,
            max_retries         = 0,
        )

        run: Run = await db.get(Run, result["run_id"])
        output   = run.output_data or {}

        assert len(output["completed_task_ids"]) == 1
        assert len(output["failed_task_ids"])    == 1
        assert output["bundle_path"] is not None
        assert output["hitl_request_id"] is not None

    @pytest.mark.asyncio
    async def test_task_feedback_persisted_on_failure(
        self, db, orchestrator, mock_openai
    ):
        """
        When a task fails, the aggregated reviewer feedback is stored
        in Task.feedback so the caller can see why it failed.
        """
        project_id = "proj-db-002"
        arch_run   = await _seed_arch_run(
            db,
            project_id = project_id,
            tasks      = [_base_task("Failing Task", 0)],
        )

        feedback_text = "Security reviewer: no input sanitisation found."
        mock_openai.side_effect = [
            make_developer_response({"src/a.py": "pass"}),
            make_reviewer_pass_response(),
            make_reviewer_pass_response(),
            make_reviewer_fail_response(feedback=feedback_text),
        ]

        result = await trigger_codegen_run(
            project_id          = project_id,
            architecture_run_id = arch_run.id,
            max_retries         = 0,
        )

        tasks = list((await db.execute(
            select(Task).where(Task.run_id == result["run_id"])
        )).scalars().all())

        assert tasks[0].status   == TaskStatus.FAILED.value
        assert feedback_text in (tasks[0].feedback or "")







