# """
# app/workflows/schemas.py
# ------------------------
# Pydantic request/response schemas for the workflows router.
# Enums are imported from models (single source of truth).
# """

# from typing import Optional, Any
# from pydantic import BaseModel, Field
# from datetime import datetime

# from app.workflows.models import RunStatus, WorkflowType  # noqa: F401


# # --- Request Schemas ----------------------------------------------------------

# class TriggerRequirementsRequest(BaseModel):
#     workflow_type: WorkflowType = WorkflowType.GENERIC
#     input: Optional[dict[str, Any]] = Field(default_factory=dict)
#     requirements: list[str] = Field(default_factory=list)
#     document_ids: list[str] = Field(default_factory=list)
#     idempotency_key: Optional[str] = None
#     requirements: Optional[list[str]] = Field(default_factory=list)
#     document_ids: Optional[list[str]] = Field(
#         default=None,
#         description="Optional list of document IDs from the vector store to use as context"
#     )
#     idempotecy_key: Optional[str] = None


# class RunCreate(BaseModel):
#     workflow_type: WorkflowType = WorkflowType.GENERIC
#     input: Optional[dict[str, Any]] = Field(default_factory=dict)


# class SubmitClarificationRequest(BaseModel):
#     answer: str


# class ApproveRequest(BaseModel):
#     comment: Optional[str] = None


# class RejectRequest(BaseModel):
#     reason: Optional[str] = None


# # --- Response Schemas ---------------------------------------------------------

# class TriggerResponse(BaseModel):
#     run_id: str
#     status: str
#     message: Optional[str] = None
#     clarification_id: Optional[str] = None
#     question: Optional[str] = None

#     model_config = {"from_attributes": True}


# class RunListItem(BaseModel):
#     id: str
#     workflow_type: Optional[str] = None
#     status: str
#     created_at: Optional[datetime] = None
#     started_at: Optional[datetime] = None
#     finished_at: Optional[datetime] = None

#     model_config = {"from_attributes": True}


# class RunDetail(BaseModel):
#     id: str
#     workflow_type: Optional[str] = None
#     status: str
#     input_data: Optional[dict[str, Any]] = None
#     output_data: Optional[dict[str, Any]] = None
#     error: Optional[str] = None
#     run_metadata: Optional[dict[str, Any]] = None
#     created_at: Optional[datetime] = None
#     started_at: Optional[datetime] = None
#     finished_at: Optional[datetime] = None

#     model_config = {"from_attributes": True}


# class ClarificationRead(BaseModel):
#     id: str
#     run_id: str
#     question: str
#     answer: Optional[str] = None
#     status: str
#     created_at: Optional[datetime] = None

#     model_config = {"from_attributes": True}


# class ClarificationResponse(BaseModel):
#     answer: str























# Code Generated by Sidekick is for learning and experimentation purposes only.
"""
app/workflows/schemas.py
------------------------
Pydantic request/response schemas for the workflows router.

Changes in Milestone 5:
  - Added TriggerCodegenRequest, CodegenTaskSchema, CodegenRunDetail
  - Fixed TriggerRequirementsRequest (duplicate field removed)
  - Fixed SubmitClarificationRequest (router uses .answers list + .request_id)
  - Fixed RejectRequest (.reason → .feedback to match router.py)
  - Fixed TriggerResponse (added project_id, workflow_type, location)
"""

from __future__ import annotations

from typing import Any, List, Optional
from pydantic import BaseModel, Field
from datetime import datetime

from app.workflows.models import RunStatus, WorkflowType  # noqa: F401


# ---------------------------------------------------------------------------
# Request schemas
# ---------------------------------------------------------------------------

class TriggerRequirementsRequest(BaseModel):
    """Trigger the requirements-gathering workflow."""
    workflow_type:   WorkflowType       = WorkflowType.REQUIREMENTS
    input:           Optional[dict[str, Any]] = Field(default_factory=dict)
    document_ids:    Optional[list[str]]      = Field(
        default=None,
        description="Document IDs from the vector store to use as context",
    )
    idempotency_key: Optional[str] = None


class TriggerCodegenRequest(BaseModel):
    """
    Trigger Workflow 3 — Code Generation.

    The codegen workflow needs three pieces of context already stored on disk
    from earlier milestones:

    architecture_run_id
        The run_id of the completed architecture workflow whose approved task
        list we will execute.  The orchestrator loads the task list from the
        Run's output_data or from the artifacts directory.

    document_ids
        Optional extra document IDs to inject into the developer agent's
        context window (e.g. the original requirements doc).

    max_retries
        Per-task reviewer retry cap.  Defaults to 3 (configurable per call).
    """
    architecture_run_id: str = Field(
        ...,
        description="run_id of the approved architecture workflow to source the task list from",
    )
    document_ids:    Optional[list[str]] = Field(
        default=None,
        description="Additional document IDs to load into developer agent context",
    )
    max_retries:     int  = Field(
        default=3,
        ge=1,
        le=10,
        description="Maximum developer→reviewer retry loops per task",
    )
    idempotency_key: Optional[str] = None


class RunCreate(BaseModel):
    workflow_type: WorkflowType = WorkflowType.GENERIC
    input:         Optional[dict[str, Any]] = Field(default_factory=dict)


class ClarificationAnswer(BaseModel):
    """A single question-answer pair inside a clarification submission."""
    question_id: str
    answer:      str


class SubmitClarificationRequest(BaseModel):
    """
    REST fallback: submit answers to a pending clarification request.

    FIX: original schema had `answer: str` — router.py uses
    `body.request_id` and `body.answers` (list), so both are required here.
    """
    request_id: str
    answers:    list[ClarificationAnswer]


class ApproveRequest(BaseModel):
    comment: Optional[str] = None


class RejectRequest(BaseModel):
    """
    FIX: field renamed from `reason` → `feedback` to match router.py usage
    (`body.feedback` throughout _resume_with_approval).
    """
    feedback: Optional[str] = None


# ---------------------------------------------------------------------------
# Response schemas
# ---------------------------------------------------------------------------

class TriggerResponse(BaseModel):
    """
    FIX: added project_id, workflow_type, location — all three are
    referenced in the router's JSONResponse construction.
    """
    run_id:        str
    project_id:    str
    workflow_type: str
    status:        str
    location:      str
    message:       Optional[str] = None

    model_config = {"from_attributes": True}


class RunListItem(BaseModel):
    id:            str
    workflow_type: Optional[str]      = None
    status:        str
    created_at:    Optional[datetime] = None
    started_at:    Optional[datetime] = None
    finished_at:   Optional[datetime] = None

    model_config = {"from_attributes": True}


class RunDetail(BaseModel):
    id:            str
    project_id:    Optional[str]           = None
    workflow_type: Optional[str]           = None
    status:        str
    input_data:    Optional[dict[str, Any]] = None
    output_data:   Optional[dict[str, Any]] = None
    error:         Optional[str]           = None
    run_metadata:  Optional[dict[str, Any]] = None
    created_at:    Optional[datetime]      = None
    started_at:    Optional[datetime]      = None
    finished_at:   Optional[datetime]      = None

    model_config = {"from_attributes": True}


class CodegenTaskSchema(BaseModel):
    """
    Read-only representation of a Task record — returned inside
    CodegenRunDetail so callers can inspect per-task progress.
    """
    id:              str
    title:           str
    description:     Optional[str]      = None
    order_index:     int
    pattern_refs:    list[str]          = Field(default_factory=list)
    status:          str
    retry_count:     int                = 0
    generated_files: list[str]          = Field(default_factory=list)
    feedback:        Optional[str]      = None
    error:           Optional[str]      = None
    started_at:      Optional[datetime] = None
    finished_at:     Optional[datetime] = None

    model_config = {"from_attributes": True}


class CodegenRunDetail(RunDetail):
    """
    Extended run detail for codegen runs — includes the full task list
    so clients can render per-task progress without a separate endpoint.
    """
    tasks: List[CodegenTaskSchema] = Field(default_factory=list)


class ClarificationRead(BaseModel):
    id:         str
    run_id:     str
    question:   str
    answer:     Optional[str]      = None
    status:     str
    created_at: Optional[datetime] = None

    model_config = {"from_attributes": True}


class ClarificationResponse(BaseModel):
    answer: str
