# app/documents/parser.py
# Code Generated by Sidekick is for learning and experimentation purposes only.

import io
import re
from typing import BinaryIO


# ------------------------------------------------------------------ #
# Output format                                                         #
# ------------------------------------------------------------------ #

def make_chunk(
    section_id: str,
    text: str,
    section_title: str = "",
    page: int = 0,
    chunk_index: int = 0,
) -> dict:
    """
    Helper to build a consistent chunk dict.
    Every parser returns a list of these dicts.
    """
    return {
        "section_id":    section_id,
        "text":          text.strip(),
        "section_title": section_title.strip(),
        "page":          page,
        "chunk_index":   chunk_index,
    }


# ------------------------------------------------------------------ #
# Text splitting                                                        #
# ------------------------------------------------------------------ #

def split_text_into_chunks(
    text: str,
    chunk_size: int = 1000,
    chunk_overlap: int = 100,
) -> list[str]:
    """
    Splits a long text string into overlapping chunks.

    Why overlap? So that a sentence that falls at a chunk boundary
    appears in both chunks — this improves RAG recall.

    chunk_size    = max characters per chunk
    chunk_overlap = how many characters the next chunk shares with the previous
    """
    chunks = []
    start = 0

    while start < len(text):
        end = start + chunk_size

        # Try to break at a sentence boundary (. ! ?) rather than mid-word
        if end < len(text):
            # Look backwards from 'end' for the last sentence-ending punctuation
            break_point = max(
                text.rfind(". ", start, end),
                text.rfind("? ", start, end),
                text.rfind("! ", start, end),
                text.rfind("\n", start, end),
            )
            if break_point > start + (chunk_size // 2):
                end = break_point + 1  # include the punctuation

        chunk = text[start:end].strip()
        if chunk:
            chunks.append(chunk)

        # Move forward, stepping back by overlap amount
        start = end - chunk_overlap

    return chunks


# ------------------------------------------------------------------ #
# PDF Parser                                                            #
# ------------------------------------------------------------------ #

def parse_pdf(file_bytes: bytes) -> list[dict]:
    """
    Extract text from a PDF file, page by page.
    Each page becomes one or more chunks.
    We use pypdf which handles most standard PDFs.
    """
    from pypdf import PdfReader

    reader = PdfReader(io.BytesIO(file_bytes))
    chunks = []
    chunk_index = 0

    for page_num, page in enumerate(reader.pages):
        page_text = page.extract_text() or ""
        page_text = page_text.strip()

        if not page_text:
            # Skip empty pages (cover pages, blank pages, etc.)
            continue

        # Split each page into sub-chunks if it's long
        sub_chunks = split_text_into_chunks(page_text)

        for sub_idx, sub_text in enumerate(sub_chunks):
            if not sub_text:
                continue

            # Try to detect a heading on this page (first line often is the heading)
            lines = sub_text.split("\n")
            title = lines[0][:100] if lines else f"Page {page_num + 1}"

            chunks.append(make_chunk(
                section_id=f"page{page_num + 1}_chunk{sub_idx}",
                text=sub_text,
                section_title=title,
                page=page_num + 1,
                chunk_index=chunk_index,
            ))
            chunk_index += 1

    return chunks


# ------------------------------------------------------------------ #
# DOCX Parser                                                           #
# ------------------------------------------------------------------ #

def parse_docx(file_bytes: bytes) -> list[dict]:
    """
    Extract text from a Word document (.docx).
    Word documents have explicit paragraph styles — we use Heading styles
    to detect section boundaries, which gives us clean section_title values.
    """
    from docx import Document

    doc = Document(io.BytesIO(file_bytes))
    chunks = []
    chunk_index = 0

    # We accumulate paragraphs under each heading into a section buffer
    current_heading = "Introduction"
    current_text_parts = []
    section_num = 0

    def flush_section(heading: str, text_parts: list[str], sec_num: int) -> list[dict]:
        """
        Take the accumulated text for one section and split it into chunks.
        Returns a list of chunk dicts.
        """
        full_text = "\n".join(text_parts).strip()
        if not full_text:
            return []

        result = []
        sub_chunks = split_text_into_chunks(full_text)
        for sub_idx, sub_text in enumerate(sub_chunks):
            if sub_text:
                result.append(make_chunk(
                    section_id=f"section{sec_num}_chunk{sub_idx}",
                    text=sub_text,
                    section_title=heading,
                    page=0,   # DOCX doesn't expose page numbers easily
                    chunk_index=0,  # will be re-indexed in the main loop
                ))
        return result

    for para in doc.paragraphs:
        style_name = para.style.name if para.style else ""
        text = para.text.strip()

        if not text:
            continue  # skip empty paragraphs

        # Word heading styles are named "Heading 1", "Heading 2", etc.
        is_heading = style_name.startswith("Heading")

        if is_heading:
            # Save the previous section before starting a new one
            flushed = flush_section(current_heading, current_text_parts, section_num)
            for c in flushed:
                c["chunk_index"] = chunk_index
                chunks.append(c)
                chunk_index += 1

            # Start a new section with this heading
            current_heading = text
            current_text_parts = []
            section_num += 1
        else:
            current_text_parts.append(text)

    # Don't forget the last section
    flushed = flush_section(current_heading, current_text_parts, section_num)
    for c in flushed:
        c["chunk_index"] = chunk_index
        chunks.append(c)
        chunk_index += 1

    return chunks


# ------------------------------------------------------------------ #
# PPTX Parser                                                           #
# ------------------------------------------------------------------ #

def parse_pptx(file_bytes: bytes) -> list[dict]:
    """
    Extract text from a PowerPoint file (.pptx).
    Each slide becomes one chunk. The slide title (if present) becomes section_title.
    """
    from pptx import Presentation

    prs = Presentation(io.BytesIO(file_bytes))
    chunks = []
    chunk_index = 0

    for slide_num, slide in enumerate(prs.slides):
        slide_title = ""
        slide_texts = []

        for shape in slide.shapes:
            if not shape.has_text_frame:
                continue

            # The title placeholder usually has shape.shape_type == 13
            # but checking the placeholder type is more reliable
            is_title = (
                hasattr(shape, "placeholder_format")
                and shape.placeholder_format is not None
                and shape.placeholder_format.idx == 0  # 0 = title placeholder
            )

            shape_text = "\n".join(
                para.text.strip()
                for para in shape.text_frame.paragraphs
                if para.text.strip()
            )

            if is_title:
                slide_title = shape_text
            elif shape_text:
                slide_texts.append(shape_text)

        full_slide_text = "\n".join(slide_texts).strip()

        if not full_slide_text and not slide_title:
            continue  # skip blank slides

        # Combine title + body for the chunk text
        combined = f"{slide_title}\n\n{full_slide_text}".strip() if slide_title else full_slide_text

        # Slides are usually short enough to be a single chunk
        sub_chunks = split_text_into_chunks(combined)
        for sub_idx, sub_text in enumerate(sub_chunks):
            if sub_text:
                chunks.append(make_chunk(
                    section_id=f"slide{slide_num + 1}_chunk{sub_idx}",
                    text=sub_text,
                    section_title=slide_title or f"Slide {slide_num + 1}",
                    page=slide_num + 1,
                    chunk_index=chunk_index,
                ))
                chunk_index += 1

    return chunks


# ------------------------------------------------------------------ #
# XLSX Parser                                                           #
# ------------------------------------------------------------------ #

def parse_xlsx(file_bytes: bytes) -> list[dict]:
    """
    Extract text from an Excel file (.xlsx).
    Each sheet becomes one chunk. We convert the sheet's cells into
    a readable text representation (header row + data rows).
    """
    import openpyxl

    wb = openpyxl.load_workbook(io.BytesIO(file_bytes), read_only=True, data_only=True)
    chunks = []
    chunk_index = 0

    for sheet_num, sheet_name in enumerate(wb.sheetnames):
        ws = wb[sheet_name]
        rows_text = []

        for row in ws.iter_rows(values_only=True):
            # Convert each cell to string, skip rows that are completely empty
            row_values = [str(cell) if cell is not None else "" for cell in row]
            row_text = " | ".join(row_values).strip()
            if any(cell for cell in row_values):  # skip all-empty rows
                rows_text.append(row_text)

        if not rows_text:
            continue  # skip empty sheets

        sheet_text = "\n".join(rows_text)
        sub_chunks = split_text_into_chunks(sheet_text)

        for sub_idx, sub_text in enumerate(sub_chunks):
            if sub_text:
                chunks.append(make_chunk(
                    section_id=f"sheet{sheet_num + 1}_chunk{sub_idx}",
                    text=sub_text,
                    section_title=sheet_name,
                    page=0,
                    chunk_index=chunk_index,
                ))
                chunk_index += 1

    wb.close()
    return chunks


# ------------------------------------------------------------------ #
# Markdown Parser                                                       #
# ------------------------------------------------------------------ #

def parse_markdown(file_bytes: bytes) -> list[dict]:
    """
    Parse a Markdown file by splitting on heading lines (# ## ###).
    Each heading introduces a new section. This gives us clean, meaningful
    section boundaries for RAG — better than arbitrary character splits.
    """
    text = file_bytes.decode("utf-8", errors="replace")
    chunks = []
    chunk_index = 0

    # Split the text by Markdown headings using regex
    # Pattern: a line starting with one or more # characters
    heading_pattern = re.compile(r"^(#{1,6})\s+(.+)$", re.MULTILINE)

    # Find all heading positions
    heading_matches = list(heading_pattern.finditer(text))

    if not heading_matches:
        # No headings found — treat whole file as one section
        sub_chunks = split_text_into_chunks(text.strip())
        for sub_idx, sub_text in enumerate(sub_chunks):
            if sub_text:
                chunks.append(make_chunk(
                    section_id=f"section0_chunk{sub_idx}",
                    text=sub_text,
                    section_title="Document",
                    page=0,
                    chunk_index=chunk_index,
                ))
                chunk_index += 1
        return chunks

    # Process text before the first heading (preamble)
    preamble = text[:heading_matches[0].start()].strip()
    if preamble:
        sub_chunks = split_text_into_chunks(preamble)
        for sub_idx, sub_text in enumerate(sub_chunks):
            if sub_text:
                chunks.append(make_chunk(
                    section_id=f"preamble_chunk{sub_idx}",
                    text=sub_text,
                    section_title="Preamble",
                    page=0,
                    chunk_index=chunk_index,
                ))
                chunk_index += 1

    # Process each heading + its body text
    for i, match in enumerate(heading_matches):
        heading_text = match.group(2).strip()

        # Body text = from end of this heading line to start of next heading
        body_start = match.end()
        body_end = heading_matches[i + 1].start() if i + 1 < len(heading_matches) else len(text)
        body_text = text[body_start:body_end].strip()

        if not body_text:
            continue  # skip headings with no content

        sub_chunks = split_text_into_chunks(body_text)
        for sub_idx, sub_text in enumerate(sub_chunks):
            if sub_text:
                chunks.append(make_chunk(
                    section_id=f"section{i + 1}_chunk{sub_idx}",
                    text=sub_text,
                    section_title=heading_text,
                    page=0,
                    chunk_index=chunk_index,
                ))
                chunk_index += 1

    return chunks


# ------------------------------------------------------------------ #
# TXT Parser                                                            #
# ------------------------------------------------------------------ #

def parse_txt(file_bytes: bytes) -> list[dict]:
    """
    Parse a plain text file.
    No structure to detect, so we just split into fixed-size chunks.
    We try to detect "paragraph breaks" (double newlines) as soft boundaries.
    """
    text = file_bytes.decode("utf-8", errors="replace").strip()

    if not text:
        return []

    chunks = []
    chunk_index = 0

    # Split on double newlines first (paragraph boundaries)
    paragraphs = re.split(r"\n\s*\n", text)
    buffer = ""

    for para in paragraphs:
        para = para.strip()
        if not para:
            continue

        buffer = (buffer + "\n\n" + para).strip() if buffer else para

        # Once the buffer is large enough, flush it as a chunk
        if len(buffer) >= 800:
            sub_chunks = split_text_into_chunks(buffer)
            for sub_idx, sub_text in enumerate(sub_chunks):
                if sub_text:
                    chunks.append(make_chunk(
                        section_id=f"para_chunk{chunk_index}_{sub_idx}",
                        text=sub_text,
                        section_title=f"Section {chunk_index + 1}",
                        page=0,
                        chunk_index=chunk_index,
                    ))
            chunk_index += 1
            buffer = ""

    # Flush any remaining text
    if buffer:
        sub_chunks = split_text_into_chunks(buffer)
        for sub_idx, sub_text in enumerate(sub_chunks):
            if sub_text:
                chunks.append(make_chunk(
                    section_id=f"para_chunk{chunk_index}_{sub_idx}",
                    text=sub_text,
                    section_title=f"Section {chunk_index + 1}",
                    page=0,
                    chunk_index=chunk_index,
                ))

    return chunks


# ------------------------------------------------------------------ #
# Main dispatcher                                                       #
# ------------------------------------------------------------------ #

# Maps file extension → parser function
PARSERS = {
    "pdf":  parse_pdf,
    "docx": parse_docx,
    "pptx": parse_pptx,
    "xlsx": parse_xlsx,
    "md":   parse_markdown,
    "txt":  parse_txt,
}

# Supported MIME types and their extensions
SUPPORTED_MIME_TYPES = {
    "application/pdf":                                                  "pdf",
    "application/vnd.openxmlformats-officedocument.wordprocessingml.document": "docx",
    "application/vnd.openxmlformats-officedocument.presentationml.presentation": "pptx",
    "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet": "xlsx",
    "text/markdown":  "md",
    "text/x-markdown": "md",
    "text/plain":     "txt",
}

# Max file size: 50MB
MAX_FILE_SIZE_BYTES = 50 * 1024 * 1024


def get_extension_from_mime(mime_type: str) -> str | None:
    """
    Map a MIME type to a file extension.
    Returns None if the MIME type is not supported.
    """
    return SUPPORTED_MIME_TYPES.get(mime_type)


def parse_document(file_bytes: bytes, extension: str) -> list[dict]:
    """
    Main entry point for parsing.
    Dispatches to the correct parser based on file extension.
    Returns a list of chunk dicts.

    Raises ValueError if the extension is not supported.
    """
    parser_fn = PARSERS.get(extension.lower())

    if not parser_fn:
        raise ValueError(f"Unsupported file extension: {extension}")

    # Run the parser and filter out any empty chunks
    raw_chunks = parser_fn(file_bytes)
    return [c for c in raw_chunks if c["text"].strip()]
