# app/documents/router.py
# Code Generated by Sidekick is for learning and experimentation purposes only.

from fastapi import (
    APIRouter, Depends, HTTPException, UploadFile, File,
    BackgroundTasks, Query, status
)
from sqlalchemy.ext.asyncio import AsyncSession

from app.storage.database import get_db
from app.dependencies import get_current_user
from app.auth.models import User
from app.projects import service as project_service
from app.documents import service as doc_service
from app.documents.models import DocumentKind, ParseStatus
from app.documents.parser import (
    SUPPORTED_MIME_TYPES, MAX_FILE_SIZE_BYTES, get_extension_from_mime
)
from app.documents.schemas import (
    DocumentUploadResponse,
    DocumentStatusResponse,
    DocumentListResponse,
    DocumentSectionsResponse,
    SectionItem,
)

router = APIRouter(prefix="/projects", tags=["Documents"])


# ------------------------------------------------------------------ #
# Helper: resolve project and verify ownership                         #
# ------------------------------------------------------------------ #

async def _get_project_or_404(db, project_id: str, owner_id: str):
    """
    Shared helper used by every document endpoint.
    Loads the project and verifies ownership.
    Returns 404 (never 403) if the project doesn't exist or belongs to another user.
    This prevents existence leakage.
    """
    project = await project_service.get_project(db, project_id, owner_id)
    if not project:
        raise HTTPException(
            status_code=status.HTTP_404_NOT_FOUND,
            detail={"code": "PROJECT_NOT_FOUND", "message": "Project not found"},
        )
    return project


# ------------------------------------------------------------------ #
# POST /projects/{project_id}/documents                                #
# ------------------------------------------------------------------ #

@router.post(
    "/{project_id}/documents",
    response_model=DocumentUploadResponse,
    status_code=status.HTTP_202_ACCEPTED,
    summary="Upload a document to a project",
)
async def upload_document(
    project_id: str,
    background_tasks: BackgroundTasks,
    file: UploadFile = File(..., description="PDF, DOCX, PPTX, XLSX, MD, or TXT file"),
    kind: DocumentKind = Query(
        DocumentKind.OTHER,
        description="Document type: BRD, PRD, TRD, or other"
    ),
    current_user: User = Depends(get_current_user),
    db: AsyncSession = Depends(get_db),
):
    """
    Upload a document to the project.

    - File is saved immediately → returns document_id right away (202 Accepted)
    - Parsing + embedding runs in the background
    - Poll GET /projects/{project_id}/documents/{document_id} until status = ready
    - Duplicate uploads (same content) return the existing document_id with 200 OK
    - Returns 415 for unsupported MIME types
    - Returns 413 if file exceeds the size limit (50MB)
    """
    # Verify the project exists and belongs to this user
    await _get_project_or_404(db, project_id, current_user.id)

    # --- Validate MIME type ---
    mime_type = file.content_type or ""
    extension = get_extension_from_mime(mime_type)

    if not extension:
        raise HTTPException(
            status_code=status.HTTP_415_UNSUPPORTED_MEDIA_TYPE,
            detail={
                "code": "UNSUPPORTED_MIME_TYPE",
                "message": f"File type '{mime_type}' is not supported.",
                "details": f"Supported types: {list(SUPPORTED_MIME_TYPES.keys())}",
            },
        )

    # --- Read file content ---
    file_bytes = await file.read()

    # --- Validate file size ---
    if len(file_bytes) > MAX_FILE_SIZE_BYTES:
        raise HTTPException(
            status_code=status.HTTP_413_REQUEST_ENTITY_TOO_LARGE,
            detail={
                "code": "FILE_TOO_LARGE",
                "message": f"File exceeds the {MAX_FILE_SIZE_BYTES // (1024*1024)}MB size limit.",
                "details": f"Received {len(file_bytes)} bytes",
            },
        )

    # --- Handle upload (save file + create DB row) ---
    document = await doc_service.handle_upload(
        db=db,
        project_id=project_id,
        filename=file.filename or "upload",
        mime_type=mime_type,
        file_bytes=file_bytes,
        kind=kind,
    )

    # --- If already parsed (duplicate upload), return immediately ---
    if document.status == ParseStatus.READY:
        return DocumentUploadResponse(
            document_id=document.id,
            filename=document.filename,
            status=document.status,
            message="Duplicate file detected. Returning existing parsed document.",
        )

    # --- Schedule parse job as a background task ---
    background_tasks.add_task(
        doc_service.run_parse_job,
        document_id=document.id,
        project_id=project_id,
    )

    return DocumentUploadResponse(
        document_id=document.id,
        filename=document.filename,
        status=document.status,
        message="File uploaded successfully. Parsing started in the background.",
    )


# ------------------------------------------------------------------ #
# GET /projects/{project_id}/documents                                 #
# ------------------------------------------------------------------ #

@router.get(
    "/{project_id}/documents",
    response_model=DocumentListResponse,
    summary="List all documents in a project",
)
async def list_documents(
    project_id: str,
    current_user: User = Depends(get_current_user),
    db: AsyncSession = Depends(get_db),
):
    """Return all documents uploaded to this project."""
    await _get_project_or_404(db, project_id, current_user.id)

    documents, total = await doc_service.list_documents(db, project_id)

    return DocumentListResponse(
        items=[DocumentStatusResponse.model_validate(d) for d in documents],
        total=total,
    )


# ------------------------------------------------------------------ #
# GET /projects/{project_id}/documents/{document_id}                  #
# ------------------------------------------------------------------ #

@router.get(
    "/{project_id}/documents/{document_id}",
    response_model=DocumentStatusResponse,
    summary="Get document status and metadata",
)
async def get_document(
    project_id: str,
    document_id: str,
    current_user: User = Depends(get_current_user),
    db: AsyncSession = Depends(get_db),
):
    """
    Poll this endpoint after uploading a document.
    When status = 'ready', the document is fully parsed and embedded.
    When status = 'failed', check error_message for what went wrong.
    Returns 404 if the document_id doesn't belong to this project.
    """
    await _get_project_or_404(db, project_id, current_user.id)

    document = await doc_service.get_document(db, document_id, project_id)
    if not document:
        raise HTTPException(
            status_code=status.HTTP_404_NOT_FOUND,
            detail={
                "code": "DOCUMENT_NOT_FOUND",
                "message": "Document not found in this project",
            },
        )

    return DocumentStatusResponse.model_validate(document)


# ------------------------------------------------------------------ #
# GET /projects/{project_id}/documents/{document_id}/sections         #
# ------------------------------------------------------------------ #

@router.get(
    "/{project_id}/documents/{document_id}/sections",
    response_model=DocumentSectionsResponse,
    summary="Get the structured section outline of a parsed document",
)
async def get_document_sections(
    project_id: str,
    document_id: str,
    current_user: User = Depends(get_current_user),
    db: AsyncSession = Depends(get_db),
):
    """
    Returns the full list of parsed sections / chunks for a document.
    Only available after status = 'ready'.
    Useful for previewing what the agents will read during RAG.
    """
    await _get_project_or_404(db, project_id, current_user.id)

    document = await doc_service.get_document(db, document_id, project_id)
    if not document:
        raise HTTPException(
            status_code=status.HTTP_404_NOT_FOUND,
            detail={"code": "DOCUMENT_NOT_FOUND", "message": "Document not found"},
        )

    if document.status != ParseStatus.READY:
        raise HTTPException(
            status_code=status.HTTP_409_CONFLICT,
            detail={
                "code": "DOCUMENT_NOT_READY",
                "message": f"Document is not ready yet. Current status: {document.status}",
            },
        )

    chunks = await doc_service.get_document_sections(db, document_id, project_id)

    sections = [
        SectionItem(
            section_id=chunk.section_id,
            section_title=chunk.section_title or f"Section {chunk.chunk_index + 1}",
            chunk_index=chunk.chunk_index,
            page=chunk.page,
            # Give a 200-character preview so the user can verify parsing quality
            text_preview=chunk.text[:200] + "..." if len(chunk.text) > 200 else chunk.text,
        )
        for chunk in chunks
    ]

    return DocumentSectionsResponse(
        document_id=document_id,
        filename=document.filename,
        sections=sections,
        total_sections=len(sections),
    )
