# Code Generated by Sidekick is for learning and experimentation purposes only.
"""
Unit tests for the researcher subgraph.

All external calls (ChromaDB, OpenAI) are mocked.
Tests verify:
  1. operator.add accumulates findings from all three branches
  2. Branch failure is non-fatal — other branches still contribute
  3. synthesise_node runs after all three branches complete
  4. project_id filter is enforced on document queries
"""
from __future__ import annotations

import asyncio
from typing import Any, Dict
from unittest.mock import AsyncMock, MagicMock, patch

import pytest

from app.schemas.planning import ResearchFinding, ResearchOutput, ResearchSourceKind
from app.workflows.planning.researcher_subgraph import (
    ResearcherState,
    build_researcher_subgraph,
    doc_rag_node,
    kb_rag_node,
    synthesise_node,
    web_search_node,
)


# ─────────────────────────────────────────────────────────────────────
# Fixtures
# ─────────────────────────────────────────────────────────────────────

@pytest.fixture
def base_state() -> ResearcherState:
    return ResearcherState(
        project_id="proj_test_001",
        run_id="run_test_001",
        planning_goal="Build a multi-agent document processing system",
        requirements_json={
            "goals": ["automate document ingestion"],
            "functional_requirements": ["upload PDF", "extract text", "embed chunks"],
        },
        patterns_json=[
            {"name": "RAG", "intent": "Retrieve relevant context before generating"},
            {"name": "ReAct", "intent": "Interleave reasoning and tool use"},
        ],
    )


def _make_research_output(branch: str, count: int = 2) -> ResearchOutput:
    """Helper: build a mock ResearchOutput for a given branch."""
    return ResearchOutput(
        findings=[
            ResearchFinding(
                content=f"Finding {i} from {branch}",
                source_kind=ResearchSourceKind(
                    {"doc": "doc", "kb": "kb", "web": "web"}[branch]
                ),
                source_id=f"{branch}:source_{i}",
                relevance_score=0.85,
                citation_tag=f"[{branch}:source_{i}]",
            )
            for i in range(count)
        ],
        synthesis=f"Synthesised findings from {branch} branch",
        branch=branch,
    )


# ─────────────────────────────────────────────────────────────────────
# Individual node tests
# ─────────────────────────────────────────────────────────────────────

class TestDocRagNode:

    @pytest.mark.asyncio
    async def test_returns_findings_with_correct_branch(self, base_state):
        mock_output = _make_research_output("doc")
        mock_chunks = [
            {
                "document": "BRD section content",
                "metadata": {
                    "section_id": "sec_001",
                    "project_id": "proj_test_001",
                    "page": 1,
                    "kind": "BRD",
                },
            }
        ]

        with patch(
            "app.workflows.planning.researcher_subgraph.PlanningChromaAdapter"
        ) as MockAdapter, patch(
            "app.workflows.planning.researcher_subgraph._invoke_structured",
            new_callable=AsyncMock,
            return_value=mock_output,
        ):
            mock_adapter_instance = AsyncMock()
            mock_adapter_instance.query_documents = AsyncMock(return_value=mock_chunks)
            MockAdapter.return_value = mock_adapter_instance

            result = await doc_rag_node(base_state)

        assert len(result["research_findings"]) == 2
        assert result["doc_synthesis"] == "Synthesised findings from doc branch"
        # Verify project_id filter was passed to adapter
        mock_adapter_instance.query_documents.assert_called_once_with(
            query=base_state.planning_goal,
            project_id="proj_test_001",
            n_results=8,
        )

    @pytest.mark.asyncio
    async def test_branch_failure_is_non_fatal(self, base_state):
        """A ChromaDB error must not raise — return empty findings instead."""
        with patch(
            "app.workflows.planning.researcher_subgraph.PlanningChromaAdapter"
        ) as MockAdapter:
            mock_adapter_instance = AsyncMock()
            mock_adapter_instance.query_documents = AsyncMock(
                side_effect=ConnectionError("ChromaDB unreachable")
            )
            MockAdapter.return_value = mock_adapter_instance

            result = await doc_rag_node(base_state)

        assert result["research_findings"] == []
        assert "branch_errors" in result
        assert len(result["branch_errors"]) == 1

    @pytest.mark.asyncio
    async def test_empty_chunks_returns_graceful_message(self, base_state):
        with patch(
            "app.workflows.planning.researcher_subgraph.PlanningChromaAdapter"
        ) as MockAdapter:
            mock_adapter_instance = AsyncMock()
            mock_adapter_instance.query_documents = AsyncMock(return_value=[])
            MockAdapter.return_value = mock_adapter_instance

            result = await doc_rag_node(base_state)

        assert result["research_findings"] == []
        assert "no document chunks" in result["doc_synthesis"]


class TestKbRagNode:

    @pytest.mark.asyncio
    async def test_returns_findings_from_pattern_kb(self, base_state):
        mock_output = _make_research_output("kb")
        mock_kb_chunks = [
            {
                "document": "ReAct pattern: interleave reasoning and actions",
                "metadata": {"name": "ReAct", "tags": ["tool-use", "single-agent"]},
            }
        ]

        with patch(
            "app.workflows.planning.researcher_subgraph.PlanningChromaAdapter"
        ) as MockAdapter, patch(
            "app.workflows.planning.researcher_subgraph._invoke_structured",
            new_callable=AsyncMock,
            return_value=mock_output,
        ):
            mock_adapter_instance = AsyncMock()
            mock_adapter_instance.query_patterns = AsyncMock(return_value=mock_kb_chunks)
            MockAdapter.return_value = mock_adapter_instance

            result = await kb_rag_node(base_state)

        assert len(result["research_findings"]) == 2
        assert result["kb_synthesis"] == "Synthesised findings from kb branch"

    @pytest.mark.asyncio
    async def test_kb_failure_is_non_fatal(self, base_state):
        with patch(
            "app.workflows.planning.researcher_subgraph.PlanningChromaAdapter"
        ) as MockAdapter:
            mock_adapter_instance = AsyncMock()
            mock_adapter_instance.query_patterns = AsyncMock(
                side_effect=RuntimeError("KB unavailable")
            )
            MockAdapter.return_value = mock_adapter_instance

            result = await kb_rag_node(base_state)

        assert result["research_findings"] == []
        assert len(result["branch_errors"]) == 1


class TestWebSearchNode:

    @pytest.mark.asyncio
    async def test_extracts_findings_from_web_results(self, base_state):
        mock_output = _make_research_output("web")
        mock_web_response = MagicMock()
        mock_web_response.content = (
            "LangGraph supports parallel branches via multiple edges from START. "
            "Source: https://langchain-ai.github.io/langgraph"
        )

        with patch(
            "app.workflows.planning.researcher_subgraph._get_web_search_llm"
        ) as mock_web_llm_factory, patch(
            "app.workflows.planning.researcher_subgraph._invoke_structured",
            new_callable=AsyncMock,
            return_value=mock_output,
        ):
            mock_web_llm = AsyncMock()
            mock_web_llm.ainvoke = AsyncMock(return_value=mock_web_response)
            mock_web_llm_factory.return_value = mock_web_llm

            result = await web_search_node(base_state)

        assert len(result["research_findings"]) == 2
        assert result["web_synthesis"] == "Synthesised findings from web branch"

    @pytest.mark.asyncio
    async def test_web_failure_is_non_fatal(self, base_state):
        with patch(
            "app.workflows.planning.researcher_subgraph._get_web_search_llm"
        ) as mock_web_llm_factory:
            mock_web_llm = AsyncMock()
            mock_web_llm.ainvoke = AsyncMock(
                side_effect=Exception("OpenAI API error")
            )
            mock_web_llm_factory.return_value = mock_web_llm

            result = await web_search_node(base_state)

        assert result["research_findings"] == []
        assert len(result["branch_errors"]) == 1


class TestSynthesiseNode:

    @pytest.mark.asyncio
    async def test_synthesises_all_branches(self, base_state):
        state_with_syntheses = base_state.model_copy(update={
            "doc_synthesis": "Doc branch found: chunking strategies [doc:sec_1]",
            "kb_synthesis": "KB branch found: RAG pattern applies [kb:RAG]",
            "web_synthesis": "Web branch found: LangGraph parallel edges [web:https://...]",
            "research_findings": [
                ResearchFinding(
                    content="Finding 1",
                    source_kind=ResearchSourceKind.DOC,
                    source_id="doc:sec_1",
                    relevance_score=0.9,
                    citation_tag="[doc:sec_1]",
                )
            ],
        })

        mock_response = MagicMock()
        mock_response.content = (
            "Unified synthesis: use RAG [kb:RAG] for document retrieval [doc:sec_1]. "
            "LangGraph supports this natively [web:https://...]. "
            "Multi-agent orchestration adds resilience [llm]."
        )

        with patch(
            "app.workflows.planning.researcher_subgraph._get_llm"
        ) as mock_llm_factory:
            mock_llm = AsyncMock()
            mock_llm.ainvoke = AsyncMock(return_value=mock_response)
            mock_llm_factory.return_value = mock_llm

            result = await synthesise_node(state_with_syntheses)

        assert "Unified synthesis" in result["final_synthesis"]
        assert result["total_findings"] == 1

    @pytest.mark.asyncio
    async def test_all_branches_empty_returns_graceful_degraded(self, base_state):
        """If all branches failed, synthesise must not crash."""
        result = await synthesise_node(base_state)  # all synthesis strings empty
        assert "Research could not be completed" in result["final_synthesis"]
        assert result["total_findings"] == 0


# ─────────────────────────────────────────────────────────────────────
# Integration test — full subgraph (mocked external calls)
# ─────────────────────────────────────────────────────────────────────

class TestResearcherSubgraphIntegration:

    @pytest.mark.asyncio
    async def test_operator_add_accumulates_all_three_branches(self, base_state):
        """
        Critical test: verify that operator.add actually merges findings
        from all three branches, not just the last one to write.
        Total findings must equal sum of all branch findings.
        """
        doc_output = _make_research_output("doc", count=3)
        kb_output = _make_research_output("kb", count=2)
        web_output = _make_research_output("web", count=2)

        mock_chunks = [
            {"document": "chunk", "metadata": {"section_id": "s1", "project_id": "proj_test_001", "page": 1, "kind": "BRD"}}
        ]
        mock_kb_chunks = [
            {"document": "kb chunk", "metadata": {"name": "RAG"}}
        ]
        mock_web_response = MagicMock()
        mock_web_response.content = "web search result text"

        call_count = {"n": 0}
        outputs = [doc_output, kb_output, web_output]

        async def _mock_structured(llm, schema, system, user, run_id, branch):
            out = outputs[call_count["n"] % 3]
            call_count["n"] += 1
            return out

        mock_synthesis_response = MagicMock()
        mock_synthesis_response.content = "Combined synthesis with all citations"

        with patch(
            "app.workflows.planning.researcher_subgraph.PlanningChromaAdapter"
        ) as MockAdapter, patch(
            "app.workflows.planning.researcher_subgraph._get_web_search_llm"
        ) as mock_web_llm_factory, patch(
            "app.workflows.planning.researcher_subgraph._invoke_structured",
            side_effect=_mock_structured,
        ), patch(
            "app.workflows.planning.researcher_subgraph._get_llm"
        ) as mock_llm_factory:
            # Wire adapter
            mock_adapter_instance = AsyncMock()
            mock_adapter_instance.query_documents = AsyncMock(return_value=mock_chunks)
            mock_adapter_instance.query_patterns = AsyncMock(return_value=mock_kb_chunks)
            MockAdapter.return_value = mock_adapter_instance

            # Wire web search
            mock_web_llm = AsyncMock()
            mock_web_llm.ainvoke = AsyncMock(return_value=mock_web_response)
            mock_web_llm_factory.return_value = mock_web_llm

            # Wire synthesis LLM
            mock_llm = AsyncMock()
            mock_llm.ainvoke = AsyncMock(return_value=mock_synthesis_response)
            mock_llm_factory.return_value = mock_llm

            # Run full subgraph
            subgraph = build_researcher_subgraph()
            result = await subgraph.ainvoke(base_state.model_dump())

        # operator.add should have accumulated 3 + 2 + 2 = 7 findings
        assert len(result["research_findings"]) == 7, (
            f"Expected 7 findings (3+2+2), got {len(result['research_findings'])}. "
            "operator.add reducer may not be wired correctly."
        )
        assert result["final_synthesis"] == "Combined synthesis with all citations"
