# """
# Requirements Workflow State Schema.

# Reducer rules (LangGraph merges state between nodes using these):
#   messages          → add_messages  (append-only LangChain message list)
#   gaps              → operator.add  (accumulate across reflection rounds)
#   clarification_qa  → operator.add  (accumulate across HITL rounds)
#   All other fields  → last-write-wins (plain assignment)
# """
# import operator
# from typing import Annotated, Any, Dict, List, Optional
# from pydantic import BaseModel, Field
# from langgraph.graph.message import add_messages


# # ── Sub-schemas ───────────────────────────────────────────────────────────────

# class Gap(BaseModel):
#     id:                       str
#     description:              str
#     related_requirement_area: str
#     suggested_question:       str


# class ClarificationQA(BaseModel):
#     question_id: str
#     question:    str
#     context:     str
#     answer:      str


# class RequirementItem(BaseModel):
#     id:              str
#     category:        str   # functional | non_functional | constraint | out_of_scope
#     title:           str
#     description:     str
#     source_section:  Optional[str] = None   # "doc_id:section_id"
#     priority:        str = "medium"          # high | medium | low


# class RequirementsDocument(BaseModel):
#     goals:                     List[str]            = Field(default_factory=list)
#     personas:                  List[Dict[str, str]] = Field(default_factory=list)
#     functional_requirements:   List[RequirementItem] = Field(default_factory=list)
#     non_functional_requirements: List[RequirementItem] = Field(default_factory=list)
#     constraints:               List[str]            = Field(default_factory=list)
#     out_of_scope:              List[str]            = Field(default_factory=list)
#     open_questions:            List[str]            = Field(default_factory=list)


# # ── Main state class ──────────────────────────────────────────────────────────

# class RequirementsState(BaseModel):
#     """
#     Full state for the Requirements Gathering workflow.
#     LangGraph serialises/deserialises this via the SQLite checkpointer.
#     """

#     # ── Identity (set once at graph entry, never mutated) ─────────────────
#     run_id:       str
#     project_id:   str
#     document_ids: List[str]

#     # ── LangChain message history (append-only via add_messages reducer) ──
#     messages: Annotated[List[Any], add_messages] = Field(default_factory=list)

#     # ── Raw extraction results (doc_id → extracted text summary) ──────────
#     # NOTE: we store a short summary, never full text, to avoid logging PII
#     raw_extracts: Dict[str, str] = Field(default_factory=dict)

#     # ── Reflection state ──────────────────────────────────────────────────
#     # gaps accumulates across rounds; operator.add appends new gaps each time
#     gaps:                  Annotated[List[Gap], operator.add] = Field(default_factory=list)
#     reflection_iterations: int  = 0
#     reflection_passed:     bool = False

#     # ── HITL clarification ────────────────────────────────────────────────
#     # clarification_qa accumulates all Q&A pairs across all rounds
#     clarification_qa:         Annotated[List[ClarificationQA], operator.add] = Field(default_factory=list)
#     clarification_rounds_used: int  = 0
#     clarification_capped:      bool = False

#     # ── Requirements draft → final ────────────────────────────────────────
#     draft_requirements: Optional[RequirementsDocument] = None
#     final_requirements: Optional[RequirementsDocument] = None

#     # ── Output artifact paths (populated by finalise node) ────────────────
#     requirements_md_path:   Optional[str] = None
#     requirements_json_path: Optional[str] = None

#     # ── Approval gate ─────────────────────────────────────────────────────
#     approval_decision:   Optional[str] = None   # "approve" | "reject"
#     approval_feedback:   Optional[str] = None
#     approval_request_id: Optional[str] = None

#     # ── Error signal ──────────────────────────────────────────────────────
#     error: Optional[str] = None

#     class Config:
#         arbitrary_types_allowed = True





























# Code Generated by Sidekick is for learning and experimentation purposes only.
"""
Requirements Workflow State Schema.

Reducer rules (LangGraph merges state between nodes using these):
  messages                      → add_messages  (append-only LangChain message list)
  gaps                          → replace_gaps  (FIX Bug 3: replace, never accumulate)
  clarification_qa              → operator.add  (accumulate full audit trail across rounds)
  clarification_round_boundaries→ operator.add  (accumulate start-index per round)
  All other fields              → last-write-wins (plain assignment)
"""

import operator
from typing import Annotated, Any, Dict, List, Optional
from pydantic import BaseModel, Field
from langgraph.graph.message import add_messages


# ── Sub-schemas ───────────────────────────────────────────────────────────────

class Gap(BaseModel):
    id:                       str
    description:              str
    related_requirement_area: str
    suggested_question:       str


class ClarificationQA(BaseModel):
    question_id: str
    question:    str
    context:     str
    answer:      str


class RequirementItem(BaseModel):
    id:             str
    category:       str    # functional | non_functional | constraint | out_of_scope
    title:          str
    description:    str
    source_section: Optional[str] = None   # "doc_id:section_id"
    priority:       str = "medium"          # high | medium | low


class RequirementsDocument(BaseModel):
    goals:                       List[str]             = Field(default_factory=list)
    personas:                    List[Dict[str, str]]  = Field(default_factory=list)
    functional_requirements:     List[RequirementItem] = Field(default_factory=list)
    non_functional_requirements: List[RequirementItem] = Field(default_factory=list)
    constraints:                 List[str]             = Field(default_factory=list)
    out_of_scope:                List[str]             = Field(default_factory=list)
    open_questions:              List[str]             = Field(default_factory=list)


# ── Custom reducers ───────────────────────────────────────────────────────────

def replace_gaps(old: List[Gap], new: List[Gap]) -> List[Gap]:
    """
    FIX Bug 3: Replace gaps entirely on each reflection round.

    operator.add was wrong here. Gaps represent the agent's CURRENT
    assessment of what is unknown — they are not a ledger of historical
    unknowns. After round 2, round-1 gaps that were answered by the user
    should be gone. Using operator.add meant resolved gaps persisted in
    state forever, causing the draft_requirements node to see stale gaps
    and either re-ask answered questions or generate contradictory
    requirements.

    Replace semantics: if the incoming list is non-empty, it becomes the
    new authoritative gap list. If the node emits an empty list (meaning
    all gaps resolved), we preserve that empty list — reflection_passed
    will be set True simultaneously.

    We do NOT fall back to `old` on empty because an empty new list is a
    valid terminal state (no gaps remain). Falling back would hide
    successful gap resolution from downstream nodes.
    """
    return new


# ── Main state class ──────────────────────────────────────────────────────────

class RequirementsState(BaseModel):
    """
    Full state for the Requirements Gathering workflow.
    LangGraph serialises/deserialises this via the SQLite checkpointer.
    """

    # ── Identity (set once at graph entry, never mutated) ─────────────────
    run_id:       str
    project_id:   str
    document_ids: List[str]

    # ── LangChain message history (append-only via add_messages reducer) ──
    messages: Annotated[List[Any], add_messages] = Field(default_factory=list)

    # ── Raw extraction results (doc_id → extracted text summary) ──────────
    raw_extracts: Dict[str, str] = Field(default_factory=dict)

    # ── Reflection state ──────────────────────────────────────────────────
    # FIX Bug 3: replace_gaps replaces the list each round instead of
    # appending. See replace_gaps() docstring above for full rationale.
    gaps:                  Annotated[List[Gap], replace_gaps] = Field(default_factory=list)
    reflection_iterations: int  = 0
    reflection_passed:     bool = False

    # ── HITL clarification ────────────────────────────────────────────────
    # clarification_qa: operator.add is CORRECT here. We want a full
    # audit trail of every Q&A pair across all rounds — the draft node
    # uses the complete history to inform requirements generation.
    clarification_qa: Annotated[List[ClarificationQA], operator.add] = Field(
        default_factory=list
    )

    # FIX Bug 4 (state side): track where each round's Q&A starts in the
    # clarification_qa list. When a new HITL round begins, the node appends
    # len(clarification_qa) *before* appending new answers — that index is
    # the slice start for this round's Q&A.
    #
    # Example after 3 rounds of 2, 3, and 2 questions:
    #   clarification_round_boundaries = [0, 2, 5]
    #   Round 0 Q&A: clarification_qa[0:2]
    #   Round 1 Q&A: clarification_qa[2:5]
    #   Round 2 Q&A: clarification_qa[5:]
    #
    # nodes.py: incorporate_answers should use:
    #   start = state.clarification_round_boundaries[-1]
    #   latest_round_qa = state.clarification_qa[start:]
    # instead of the broken: state.clarification_qa[round_index * 3:]
    clarification_round_boundaries: Annotated[List[int], operator.add] = Field(
        default_factory=list
    )

    clarification_rounds_used: int  = 0
    clarification_capped:      bool = False

    # ── Requirements draft → final ────────────────────────────────────────
    draft_requirements: Optional[RequirementsDocument] = None
    final_requirements: Optional[RequirementsDocument] = None

    # ── Output artifact paths (populated by finalise node) ────────────────
    requirements_md_path:  Optional[str] = None
    requirements_json_path: Optional[str] = None

    # ── Approval gate ─────────────────────────────────────────────────────
    approval_decision:   Optional[str] = None   # "approve" | "reject"
    approval_feedback:   Optional[str] = None
    approval_request_id: Optional[str] = None

    # ── Error signal ──────────────────────────────────────────────────────
    error: Optional[str] = None

    class Config:
        arbitrary_types_allowed = True
